# <font color=#DC143C size="+3">Automated generation of Wick's-theorem contributions </font> 
<font color=#9D9D9C size ="+2.25"> at third order in perturbation theory for Gorkov's polarization propagator</font> </br> <font color=#000000 size ="+1">with three one-body interaction vertices</font>

 ## <font color=#FA8072>Conventions</font>

<p align="justify">From the application of Wick's theorem to the following matrix element (cf. expansion formula of Gorkov's polarization propagator), </p>

$\Pi_{acdb}^{g_1g_3g_4g_2}(t,t')\lvert_{\mathrm{third~order}}\equiv +i \left(\frac{-i}{\hbar}\right)^3 \frac{1}{3!}\int\mathrm{d}t_1 \int\mathrm{d}t_2 \int\mathrm{d}t_3 \langle \Phi_0 \lvert T\{U(t_1)U(t_2)U(t_3) {A_{I}}_a^{g_1}(t){A_{I}}_b^{g_2}(t'){A_{I}}_d^{\dagger g_4}(t') {A_{I}}_c^{\dagger g_3}(t)\}\lvert\Phi_0\rangle_{\mathrm{conn}}$

the fully-contracted terms consisting of 10 second-quantization operators are generated. The one-body potential insertions, $U(t_1)$, $U(t_2)$ and $U(t_3)$, take the form

$U(t_1) = \frac{1}{2}\sum_{ef}[u_{ef}^{11}{a_I}_e^{\dagger}(t_1){a_I}_f(t_1)+u_{ef}^{22}{a_I}_{\bar{e}}(t_1){a_I}_{\bar{f}}^{\dagger}(t_1)+u_{ef}^{12}{a_I}_e^{\dagger}(t_1){a_I}_{\bar{f}}^{\dagger}(t_1)+u_{ef}^{21}{a_I}_{\bar{e}}(t_1){a_I}_f(t_1)]~,$

$U(t_2) = \frac{1}{2}\sum_{gh}[u_{gh}^{11}{a_I}_g^{\dagger}(t_2){a_I}_h(t_2)+u_{gh}^{22}{a_I}_{\bar{g}}(t_2){a_I}_{\bar{h}}^{\dagger}(t_2)+u_{gh}^{12}{a_I}_g^{\dagger}(t_2){a_I}_{\bar{h}}^{\dagger}(t_2)+u_{gh}^{21}{a_I}_{\bar{g}}(t_2){a_I}_h(t_2)]~,$

$U(t_3) = \frac{1}{2}\sum_{ij}[u_{ij}^{11}{a_I}_i^{\dagger}(t_3){a_I}_j(t_3)+u_{ij}^{22}{a_I}_{\bar{i}}(t_3){a_I}_{\bar{j}}^{\dagger}(t_3)+u_{ij}^{12}{a_I}_i^{\dagger}(t_3){a_I}_{\bar{j}}^{\dagger}(t_3)+u_{ij}^{21}{a_I}_{\bar{i}}(t_3){a_I}_j(t_3)]~.$

<p align="justify">Due to the presence of three one-body interaction vertices, the number of distinct fully-contracted terms corresponds to 9!! = 945. The results of the generation process hold identically for all the 4 Nambu components of the one-body potential and are the same for each of the 16 Nambu components of Gorkov's polarization propagator. A significant part of these Wick's-theorem contributions has to be discarded, since it corresponds either to disconnected diagrams or to exchange diagrams that are cancelled by the subtractive term of the polarization propagator.  At any order, no conjoint diagram containing only one-body interaction vertices exists. Additionally, since the one-body potential is not invariant under transposition of the two single-particle indices, the filtration process accounts only for inter-vertex permutation. </p>

In [1]:
9*7*5*3*1

945

The alphabetic single-particle indices of the second-quantization operators are converted into positive integers by means of the following map:

<table>
    <tr>
        <th> e </th> 
        <th> f </th>
        <th> g </th>
        <th> h </th>
        <th> i </th>
        <th> j </th>
        <th> a </th> 
        <th> b </th>
        <th> d </th>
        <th> c </th>
    </tr>
    <tr>
        <th> 1 </th> 
        <th> 2 </th>
        <th> 3 </th>
        <th> 4 </th>
        <th> 5 </th> 
        <th> 6 </th>
        <th> 7 </th>
        <th> 8 </th>
        <th> 9 </th> 
        <th> 10 </th>
    </tr>
</table>

as such, the single particle indices are stored into arrays (cf. 'Acomb', 'Acombsort', 'AdisjBogoDiag' et c.).

 ## <font color=#FA8072>Generation of the third-order fully-contracted terms</font>

The third-order fully-contracted terms are found to be $945$ in total, consistently with the formula $4n+2m+3!!$ with $n=0$ and $m=3$. Binary contractions belonging to the same fully contracted term (index $i$ in the array initialization) are denoted by the index $j$. The two single particle indices within the same contraction are distinguished by the index $k$. The process produces no repeated pairs, by construction.

In [5]:
l = 1;
Acomb = Table[0, {i, 1, 950}, {j, 1, 5}, {k, 1, 2}];
Acomb[[l]] = {{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}};
For[g = 1, g <= 9, g++,
  growind = 1;
  gcolind = 2;
  For[h = 1, h <= 7, h++,
   hrowind = 2;
   hcolind = 2;
   For[i = 1, i <= 5, i++,
    irowind = 3;
    icolind = 2;
    For[j = 1, j <= 3, j++,
     jrowind = 4;
     jcolind = 2;
     Acomb[[l]] = Acomb[[1]];
     If[g != 1,
      growpiv = Floor[g/2] + 1;
      gcolpiv = - Floor[g/2] + Ceiling[g/2] + 1;
      Acomb[[l, growind, gcolind]] = Acomb[[1, growpiv, gcolpiv]];
      Acomb[[l, growpiv, gcolpiv]] = Acomb[[1, growind, gcolind]]];
     If[h != 1,
      hrowpiv = Floor[h/2] + 2;
      hcolpiv = - Floor[h/2] + Ceiling[h/2] + 1;
      Atemp1 = Acomb[[l, hrowind, hcolind]];
      Atemp2 = Acomb[[l, hrowpiv, hcolpiv]];
      Acomb[[l, hrowind, hcolind]] = Atemp2;
      Acomb[[l, hrowpiv, hcolpiv]] = Atemp1];
     If[i != 1,
      irowpiv = Floor[i/2] + 3;
      icolpiv = - Floor[i/2] + Ceiling[i/2] + 1;
      Atemp1 = Acomb[[l, irowind, icolind]];
      Atemp2 = Acomb[[l, irowpiv, icolpiv]];
      Acomb[[l, irowind, icolind]] = Atemp2;
      Acomb[[l, irowpiv, icolpiv]] = Atemp1];
     If[j != 1,
      jrowpiv = Floor[j/2] + 4;
      jcolpiv = - Floor[j/2] + Ceiling[j/2] + 1;
      Atemp1 = Acomb[[l, jrowind, jcolind]];
      Atemp2 = Acomb[[l, jrowpiv, jcolpiv]];
      Acomb[[l, jrowind, jcolind]] = Atemp2;
      Acomb[[l, jrowpiv, jcolpiv]] = Atemp1];
     l++]]];
  If[g == 9, Print["Loop ", g, " completed and ", l - 1, " Wick's-theorem contributions generated."]]];

Loop 9 completed and 945 Wick's-theorem contributions generated.


Sorting code for the generated fully-contracted terms. Single-particle indices within the same contraction are sorted in ascending order.

In [9]:
Acombsort = Table[0, {i, 1, 945}, {j, 1, 5}, {k, 1, 2}];
For[s = 1, s <= 945, s++,
  If[Acomb[[s, 1, 1]] > Acomb[[s, 1, 2]],
   Acombsort[[s, 1, 1]] = Acomb[[s, 1, 2]];
   Acombsort[[s, 1, 2]] = Acomb[[s, 1, 1]],
   Acombsort[[s, 1]] = Acomb[[s, 1]];];
  If[Acomb[[s, 2, 1]] > Acomb[[s, 2, 2]],
   Acombsort[[s, 2, 1]] = Acomb[[s, 2, 2]];
   Acombsort[[s, 2, 2]] = Acomb[[s, 2, 1]],
   Acombsort[[s, 2]] = Acomb[[s, 2]];];
  If[Acomb[[s, 3, 1]] > Acomb[[s, 3, 2]],
   Acombsort[[s, 3, 1]] = Acomb[[s, 3, 2]];
   Acombsort[[s, 3, 2]] = Acomb[[s, 3, 1]],
   Acombsort[[s, 3]] = Acomb[[s, 3]];];
  If[Acomb[[s, 4, 1]] > Acomb[[s, 4, 2]],
   Acombsort[[s, 4, 1]] = Acomb[[s, 4, 2]];
   Acombsort[[s, 4, 2]] = Acomb[[s, 4, 1]],
   Acombsort[[s, 4]] = Acomb[[s, 4]];];
  If[Acomb[[s, 5, 1]] > Acomb[[s, 5, 2]],
   Acombsort[[s, 5, 1]] = Acomb[[s, 5, 2]];
   Acombsort[[s, 5, 2]] = Acomb[[s, 5, 1]],
   Acombsort[[s, 5]] = Acomb[[s, 5]];];];

# <font color=#71797E>Disjoint Diagrams</font>

The disjoint  diagrams at second order are 720 in total. These are distributed as follows: <br>
i) $48$ Bogoliubov diagrams dressed in the antidiagonal; <br>
ii) $48$ Bogoliubov diagrams dressed in the diagonal; <br>
iii) $96$ Bogoliubov diagrams dressed in both the diagonal and the antidiagonal; <br>
iv) $48$ Direct diagrams dressed in the left propagator; <br>
v) $48$ Direct diagrams dressed in the right propagator; <br>
vi) $96$ Direct diagrams dressed in both the left and the right propagator; <br>
vii) $48$ Exchange diagrams dressed in the propagator above; <br>
viii) $48$ Exchange diagrams dressed in the propagator below; <br>
ix) $96$ Exchange diagrams dressed in both the above and below propagator.

Total number of disjoint diagrams:

In [3]:
3 (96 + 48 + 48)

576

In [30]:
AdisjBogoDiag = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjBogoAntidiag = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjBogoliubov = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirLeft = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirRight = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirect = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchAbove = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchBelow = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchange = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
l = 1;
m = 1;
n = 1;
o = 1;
p = 1;
q = 1;
r = 1;
s = 1;
t = 1;
For[i = 1, i <= 945, i++,
 Link12 = False; 
 Link13 = False;
 Link23 = False;
 DiscV1 = False;
 DiscV2 = False;
 DiscV3 = False;
 Conn7V1 = False;
 Conn7V2 = False;
 Conn7V3 = False;
 Conn8V1 = False;
 Conn8V2 = False;
 Conn8V3 = False;
 Conn9V1 = False;
 Conn9V2 = False;
 Conn9V3 = False;
 Conn10V1 = False;
 Conn10V2 = False;
 Conn10V3 = False;
 Bridge78 = False;
 Bridge79 = False;
 Bridge710 = False;
 Bridge89 = False;
 Bridge810 = False;
 Bridge910 = False;
 SelfBinding12 = False;
 SelfBinding34 = False;
 SelfBinding56 = False;
 For[j = 1, j <= 5, j++,
  If[Acombsort[[i, j]] == {7, 8}, Bridge78 = True];
   If[Acombsort[[i, j]] == {7, 9}, Bridge79 = True];
  If[Acombsort[[i, j]] == {7, 10}, Bridge710 = True];
  If[Acombsort[[i, j]] == {8, 9}, Bridge89 = True];
  If[Acombsort[[i, j]] == {8, 10}, Bridge810 = True];
  If[Acombsort[[i, j]] == {9, 10}, Bridge910 = True];
  If[Acombsort[[i, j]] == {1, 2}  , SelfBinding12 = True];
  If[Acombsort[[i, j]] == {3, 4}  , SelfBinding34 = True];
  If[Acombsort[[i, j]] == {5, 6}  , SelfBinding56 = True];
  If[Acombsort[[i, j]] == {1, 3} || Acombsort[[i, j]] == {1, 4} || 
    Acombsort[[i, j]] == {2, 3} || Acombsort[[i, j]] == {2, 4} , 
   Link12 = True;];
  If[Acombsort[[i, j]] == {1, 5} || Acombsort[[i, j]] == {1, 6} || 
    Acombsort[[i, j]] == {2, 5} || Acombsort[[i, j]] == {2, 6} , 
   Link13 = True;];
  If[Acombsort[[i, j]] == {3, 5} || Acombsort[[i, j]] == {3, 6} || 
    Acombsort[[i, j]] == {4, 5} || Acombsort[[i, j]] == {4, 6} , 
   Link23 = True;];
  ];
 If[SelfBinding12 == True , DiscV1 = True];
 If[SelfBinding34 == True , DiscV2 = True];
 If[SelfBinding56 == True , DiscV3 = True];
 If[Bridge78 == False && Bridge79 == False && Bridge710 == False && 
   Bridge89 == False && Bridge810 == False && Bridge910 == False && 
   DiscV1 == False && DiscV2 == False && DiscV3 == False,
  For[j = 1, j <= 5, j++,
    If[(Link12 == True && Link13 == False && Link23 == False ) || ( 
        Link12 == False && Link13 == True && Link23 == False) || ( 
        Link12 == False && Link13 == False && Link23 == True) ,
      If[Acombsort[[i, j]] == {1, 7} || Acombsort[[i, j]] == {2, 7} , 
       Conn7V1 = True];
      If[Acombsort[[i, j]] == {1, 8} || Acombsort[[i, j]] == {2, 8} , 
       Conn8V1 = True];
      If[Acombsort[[i, j]] == {1, 9} || Acombsort[[i, j]] == {2, 9} , 
       Conn9V1 = True];
      If[
       Acombsort[[i, j]] == {1, 10} || Acombsort[[i, j]] == {2, 10} , 
       Conn10V1 = True];
      If[Acombsort[[i, j]] == {3, 7} || Acombsort[[i, j]] == {4, 7} , 
       Conn7V2 = True];
      If[Acombsort[[i, j]] == {3, 8} || Acombsort[[i, j]] == {4, 8} , 
       Conn8V2 = True];
      If[Acombsort[[i, j]] == {3, 9} || Acombsort[[i, j]] == {4, 9} , 
       Conn9V2 = True];
      If[
       Acombsort[[i, j]] == {3, 10} || Acombsort[[i, j]] == {4, 10} , 
       Conn10V2 = True];
      If[Acombsort[[i, j]] == {5, 7} || Acombsort[[i, j]] == {6, 7} , 
       Conn7V3 = True];
      If[Acombsort[[i, j]] == {5, 8} || Acombsort[[i, j]] == {6, 8} , 
       Conn8V3 = True];
      If[Acombsort[[i, j]] == {5, 9} || Acombsort[[i, j]] == {6, 9} , 
       Conn9V3 = True];
      If[
       Acombsort[[i, j]] == {5, 10} || Acombsort[[i, j]] == {6, 10} , 
       Conn10V3 = True];
      ];
    ];
  ]; 
 If[Conn7V1 == True && Conn8V1 == True && Conn9V1 == False && 
   Conn10V1 == False && Link23 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V3 == True && Conn8V3 == True && Conn9V3 == False && 
   Conn10V3 == False && Link12 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V2 == True && Conn8V2 == True && Conn9V2 == False && 
   Conn10V2 == False && Link13 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V1 == False && Conn8V1 == False && Conn9V1 == True && 
   Conn10V1 == True && Link23 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V3 == False && Conn8V3 == False && Conn9V3 == True && 
   Conn10V3 == True && Link12 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V2 == False && Conn8V2 == False && Conn9V2 == True && 
   Conn10V2 == True && Link13 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Conn7V1 == True && Conn8V1 == False && Conn9V1 == True && 
   Conn10V1 == False && Link23 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V1 == False && Conn8V1 == True && Conn9V1 == False && 
   Conn10V1 == True && Link23 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V2 == True && Conn8V2 == False && Conn9V2 == True && 
   Conn10V2 == False && Link13 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V2 == False && Conn8V2 == True && Conn9V2 == False && 
   Conn10V2 == True && Link13 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V3 == True && Conn8V3 == False && Conn9V3 == True && 
   Conn10V3 == False && Link12 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V3 == False && Conn8V3 == True && Conn9V3 == False && 
   Conn10V3 == True && Link12 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Conn7V1 == True && Conn8V1 == False && Conn9V1 == False && 
   Conn10V1 == True && Link23 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Conn7V1 == False && Conn8V1 == True && Conn9V1 == True && 
   Conn10V1 == False && Link23 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Conn7V2 == True && Conn8V2 == False && Conn9V2 == False && 
   Conn10V2 == True && Link13 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Conn7V2 == False && Conn8V2 == True && Conn9V2 == True && 
   Conn10V2 == False && Link13 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Conn7V3 == True && Conn8V3 == False && Conn9V3 == False && 
   Conn10V3 == True && Link12 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Conn7V3 == False && Conn8V3 == True && Conn9V3 == True && 
   Conn10V3 == False && Link12 == True, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Link12 == True && Link13 == True && Bridge79 == True && 
   Bridge810 == False, AdisjDirRight[[p]] = Acombsort[[i]]; p++];
 If[Link12 == True && Link23 == True && Bridge79 == True && 
   Bridge810 == False, AdisjDirRight[[p]] = Acombsort[[i]]; p++];
 If[Link13 == True && Link23 == True && Bridge79 == True && 
   Bridge810 == False, AdisjDirRight[[p]] = Acombsort[[i]]; p++];
 If[Link12 == True && Link13 == True && Bridge79 == False && 
   Bridge810 == True, AdisjDirLeft[[o]] = Acombsort[[i]]; o++];
 If[Link12 == True && Link23 == True && Bridge79 == False && 
   Bridge810 == True, AdisjDirLeft[[o]] = Acombsort[[i]]; o++];
 If[Link13 == True && Link23 == True && Bridge79 == False && 
   Bridge810 == True, AdisjDirLeft[[o]] = Acombsort[[i]]; o++];
 If[Link12 == True &&  Link13 == True && Bridge78 == True && 
   Bridge910 == False, AdisjBogoAntidiag[[l]] = Acombsort[[i]]; l++];
 If[Link12 == True && Link23 == True && Bridge78 == True && 
   Bridge910 == False, AdisjBogoAntidiag[[l]] = Acombsort[[i]]; l++];
 If[Link13 == True && Link23 == True && Bridge78 == True && 
   Bridge910 == False, AdisjBogoAntidiag[[l]] = Acombsort[[i]]; l++];
 If[Link12 == True && Link13 == True && Bridge78 == False && 
   Bridge910 == True, AdisjBogoDiag[[m]] = Acombsort[[i]]; m++];
 If[Link12 == True && Link23 == True && Bridge78 == False && 
   Bridge910 == True, AdisjBogoDiag[[m]] = Acombsort[[i]]; m++];
 If[Link13 == True && Link23 == True && Bridge78 == False && 
   Bridge910 == True, AdisjBogoDiag[[m]] = Acombsort[[i]]; m++];
 If[Link12 == True && Link13 == True && Bridge710 == False && 
   Bridge89 == True, AdisjExchAbove[[r]] = Acombsort[[i]]; r++];
 If[Link12 == True && Link23 == True && Bridge710 == False && 
   Bridge89 == True, AdisjExchAbove[[r]] = Acombsort[[i]]; r++];
 If[Link13 == True && Link23 == True && Bridge710 == False && 
   Bridge89 == True, AdisjExchAbove[[r]] = Acombsort[[i]]; r++];
 If[ Link12 == True && Link13 == True && Bridge710 == True && 
   Bridge89 == False, AdisjExchBelow[[s]] = Acombsort[[i]]; s++];
 If[ Link12 == True && Link23 == True && Bridge710 == True && 
   Bridge89 == False, AdisjExchBelow[[s]] = Acombsort[[i]]; s++];
 If[ Link13 == True && Link23 == True && Bridge710 == True && 
   Bridge89 == False, AdisjExchBelow[[s]] = Acombsort[[i]]; s++];
 If[i == 945, 
  Print["Loop ", i, " completed and ", l - 1, 
   " antidiagonally-dressed Bogoliubov contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", m - 1, 
   " diagonally-dressed Bogoliubov contributions found."] ];
 If[ i == 945, 
  Print["Loop ", i, " completed and ", n - 1, 
   " diagonally-and-antidiagonally-dressed Bogoliubov contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", r - 1, 
   " above-dressed exchange contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", s - 1, 
   " below-dressed exchange contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", t - 1, 
   " above-and-below-dressed exchange contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", o - 1, 
   " left-dressed direct contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", p - 1, 
   " right-dressed direct contributions found."] ];
 If[i == 945, 
  Print["Loop ", i, " completed and ", q - 1, 
   " left-and-right-dressed direct contributions found."] ];]

Loop 945 completed and 48 antidiagonally-dressed Bogoliubov contributions\
 
>    found.
Loop 945 completed and 48 diagonally-dressed Bogoliubov contributions found.
Loop 945 completed and 96 diagonally-and-antidiagonally-dressed Bogoliubov\
 
>    contributions found.
Loop 945 completed and 48 above-dressed exchange contributions found.
Loop 945 completed and 48 below-dressed exchange contributions found.
Loop 945 completed and 96 above-and-below-dressed exchange contributions\
 
>    found.
Loop 945 completed and 48 left-dressed direct contributions found.
Loop 945 completed and 48 right-dressed direct contributions found.
Loop 945 completed and 96 left-and-right-dressed direct contributions found.


 ## <font color=#FA8072>Disjoint direct diagrams with dressed single-particle propagator on the left</font>

Direct diagrams with unperturbed 1-body propagator on the right are processed. Their initial number is 48 in total.

### <font color=#E9967A>Left-dressed disjoint direct diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent left-dressed disjoint direct contributions with non-identical vertices at second order remains equal to $48$.

In [49]:
For[u = 1, u <= 48, u++, Print["CombDirLeft[[", u, "]]=", AdisjDirLeft[[u]], ";"]];

CombDirLeft[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 9}, {8, 10}};
CombDirLeft[[2]]={{1, 3}, {2, 5}, {4, 9}, {6, 7}, {8, 10}};
CombDirLeft[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 9}, {8, 10}};
CombDirLeft[[4]]={{1, 3}, {2, 6}, {5, 9}, {4, 7}, {8, 10}};
CombDirLeft[[5]]={{1, 3}, {2, 7}, {4, 5}, {6, 9}, {8, 10}};
CombDirLeft[[6]]={{1, 3}, {2, 7}, {5, 9}, {4, 6}, {8, 10}};
CombDirLeft[[7]]={{1, 3}, {2, 9}, {5, 7}, {4, 6}, {8, 10}};
CombDirLeft[[8]]={{1, 3}, {2, 9}, {4, 5}, {6, 7}, {8, 10}};
CombDirLeft[[9]]={{1, 4}, {3, 5}, {2, 7}, {6, 9}, {8, 10}};
CombDirLeft[[10]]={{1, 4}, {3, 5}, {2, 9}, {6, 7}, {8, 10}};
CombDirLeft[[11]]={{1, 4}, {3, 6}, {5, 7}, {2, 9}, {8, 10}};
CombDirLeft[[12]]={{1, 4}, {3, 6}, {5, 9}, {2, 7}, {8, 10}};
CombDirLeft[[13]]={{1, 4}, {3, 7}, {2, 5}, {6, 9}, {8, 10}};
CombDirLeft[[14]]={{1, 4}, {3, 7}, {5, 9}, {2, 6}, {8, 10}};
CombDirLeft[[15]]={{1, 4}, {3, 9}, {5, 7}, {2, 6}, {8, 10}};
CombDirLeft[[16]]={{1, 4}, {3, 9}, {2, 5}, {6, 7}, {8, 10}};
CombDirLeft[[17]]={{1, 5}, {2, 3}

In [50]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only 48 third-order left-dressed disjoint direct diagrams with non-identical one-body vertices. The multiplicity check is fulfilled by construction.

### <font color=#E9967A>Left-dressed disjoint direct diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $24$ inequivalent fully-contracted terms corresponding to left-dressed disjoint direct diagrams are found.  

In [51]:
AdcdlVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcdlVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcdlVertex[[1]] = AdisjDirLeft[[1]];
MultdcdlVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirLeft[[u, i, j]];
   If[AdisjDirLeft[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirLeft[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirLeft[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirLeft[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirLeft[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirLeft[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdlVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdlVertex[[v]] = MultdcdlVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdlVertex[[s]] = AdisjDirLeft[[u]]; 
   MultdcdlVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, " inequivalent left-dressed direct contributions found."]];
 ]

Loop 48 completed and 24 inequivalent left-dressed direct contributions found.


In [60]:
For[u = 1, u <= 24, u++, Print["CombDirLeft[[", u, "]]=", AdcdlVertex[[u]], ";"]];

CombDirLeft[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 9}, {8, 10}};
CombDirLeft[[2]]={{1, 3}, {2, 5}, {4, 9}, {6, 7}, {8, 10}};
CombDirLeft[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 9}, {8, 10}};
CombDirLeft[[4]]={{1, 3}, {2, 6}, {5, 9}, {4, 7}, {8, 10}};
CombDirLeft[[5]]={{1, 4}, {3, 5}, {2, 7}, {6, 9}, {8, 10}};
CombDirLeft[[6]]={{1, 4}, {3, 5}, {2, 9}, {6, 7}, {8, 10}};
CombDirLeft[[7]]={{1, 4}, {3, 6}, {5, 7}, {2, 9}, {8, 10}};
CombDirLeft[[8]]={{1, 4}, {3, 6}, {5, 9}, {2, 7}, {8, 10}};
CombDirLeft[[9]]={{1, 4}, {3, 7}, {2, 5}, {6, 9}, {8, 10}};
CombDirLeft[[10]]={{1, 4}, {3, 7}, {5, 9}, {2, 6}, {8, 10}};
CombDirLeft[[11]]={{1, 4}, {3, 9}, {5, 7}, {2, 6}, {8, 10}};
CombDirLeft[[12]]={{1, 4}, {3, 9}, {2, 5}, {6, 7}, {8, 10}};
CombDirLeft[[13]]={{1, 5}, {3, 6}, {2, 7}, {4, 9}, {8, 10}};
CombDirLeft[[14]]={{1, 5}, {3, 6}, {2, 9}, {4, 7}, {8, 10}};
CombDirLeft[[15]]={{1, 5}, {3, 7}, {2, 4}, {6, 9}, {8, 10}};
CombDirLeft[[16]]={{1, 5}, {3, 7}, {2, 9}, {4, 6}, {8, 10}};
CombDirLeft[[17]]={{1, 5}, {3, 9}

In [61]:
For[u = 1, u <= 24, u++, 
  Print["GGFMult[[", u, "]]=", MultdcdlVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent third-order left-dressed disjoint direct diagrams with two identical one-body vertices. The multiplicity check is fulfilled.

In [62]:
Sum[MultdcdlVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Left-dressed disjoint direct diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $8$ inequivalent fully-contracted terms corresponding to left-dressed disjoint direct diagrams are found. 

In [63]:
AdcdlVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcdlVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcdlVertex[[1]] = AdisjDirLeft[[1]];
MultdcdlVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirLeft[[u, i, j]];
   If[AdisjDirLeft[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirLeft[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirLeft[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirLeft[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirLeft[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[AdisjDirLeft[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjDirLeft[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjDirLeft[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjDirLeft[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjDirLeft[[u, i, j]] >= 3 && AdisjDirLeft[[u, i, j]] <= 4) ||
      AdisjDirLeft[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[AdisjDirLeft[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjDirLeft[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjDirLeft[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjDirLeft[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjDirLeft[[u, i, j]] <= 2 || AdisjDirLeft[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[AdisjDirLeft[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjDirLeft[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjDirLeft[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjDirLeft[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjDirLeft[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjDirLeft[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjDirLeft[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[AdisjDirLeft[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjDirLeft[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjDirLeft[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjDirLeft[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjDirLeft[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjDirLeft[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjDirLeft[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjDirLeft[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdlVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdlVertex[[v]] = MultdcdlVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdlVertex[[s]] = AdisjDirLeft[[u]]; 
   MultdcdlVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent left-dressed direct contributions found."]];
 ]

Loop 48 completed and 8 inequivalent left-dressed direct contributions found.


In [72]:
For[u = 1, u <= 8, u++, Print["CombDirLeft[[", u, "]]=", AdcdlVertex[[u]], ";"]];

CombDirLeft[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 9}, {8, 10}};
CombDirLeft[[2]]={{1, 3}, {2, 5}, {4, 9}, {6, 7}, {8, 10}};
CombDirLeft[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 9}, {8, 10}};
CombDirLeft[[4]]={{1, 3}, {2, 6}, {5, 9}, {4, 7}, {8, 10}};
CombDirLeft[[5]]={{1, 4}, {3, 6}, {5, 7}, {2, 9}, {8, 10}};
CombDirLeft[[6]]={{1, 4}, {3, 6}, {5, 9}, {2, 7}, {8, 10}};
CombDirLeft[[7]]={{1, 4}, {3, 7}, {5, 9}, {2, 6}, {8, 10}};
CombDirLeft[[8]]={{1, 4}, {3, 9}, {5, 7}, {2, 6}, {8, 10}};


In [73]:
For[u = 1, u <= 8, u++, Print["GGFMult[[", u, "]]=", MultdcdlVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order left-dressed disjoint direct diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [74]:
Sum[MultdcdlVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint direct diagrams with dressed single-particle propagator on the right</font>

Direct diagrams with unperturbed 1-body propagator on the left are processed. Their initial number is 48 in total.

### <font color=#E9967A>Right-dressed disjoint direct diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent right-dressed disjoint direct contributions with non-identical vertices at second order remains equal to $8$.

In [75]:
For[u = 1, u <= 48, u++, Print["CombDirRight[[", u, "]]=", AdisjDirRight[[u]], ";"]];

CombDirRight[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 9}, {6, 10}};
CombDirRight[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 9}, {6, 8}};
CombDirRight[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 9}, {4, 10}};
CombDirRight[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 9}, {4, 8}};
CombDirRight[[5]]={{1, 3}, {2, 8}, {4, 5}, {7, 9}, {6, 10}};
CombDirRight[[6]]={{1, 3}, {2, 8}, {5, 10}, {7, 9}, {4, 6}};
CombDirRight[[7]]={{1, 3}, {2, 10}, {5, 8}, {7, 9}, {4, 6}};
CombDirRight[[8]]={{1, 3}, {2, 10}, {4, 5}, {7, 9}, {6, 8}};
CombDirRight[[9]]={{1, 4}, {3, 5}, {2, 8}, {7, 9}, {6, 10}};
CombDirRight[[10]]={{1, 4}, {3, 5}, {2, 10}, {7, 9}, {6, 8}};
CombDirRight[[11]]={{1, 4}, {3, 6}, {5, 8}, {7, 9}, {2, 10}};
CombDirRight[[12]]={{1, 4}, {3, 6}, {5, 10}, {7, 9}, {2, 8}};
CombDirRight[[13]]={{1, 4}, {3, 8}, {2, 5}, {7, 9}, {6, 10}};
CombDirRight[[14]]={{1, 4}, {3, 8}, {5, 10}, {7, 9}, {2, 6}};
CombDirRight[[15]]={{1, 4}, {3, 10}, {5, 8}, {7, 9}, {2, 6}};
CombDirRight[[16]]={{1, 4}, {3, 10}, {2, 5}, {7, 9}, {6, 8}};
CombDirRight[[17]

In [76]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only $48$ second-order right-dressed disjoint direct diagrams with non-identical one-body vertices. The multiplicity check is fulfilled by construction.

### <font color=#E9967A>Right-dressed disjoint direct diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $24$ inequivalent fully-contracted terms corresponding to right-dressed disjoint direct diagrams are found.

In [77]:
AdcdrVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcdrVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcdrVertex[[1]] = AdisjDirRight[[1]];
MultdcdrVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirRight[[u, i, j]];
   If[AdisjDirRight[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirRight[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirRight[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirRight[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirRight[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirRight[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdrVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdrVertex[[v]] = MultdcdrVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdrVertex[[s]] = AdisjDirRight[[u]]; 
   MultdcdrVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent right-dressed direct contributions found."]];
 ]

Loop 48 completed and 24 inequivalent right-dressed direct contributions\
 
>    found.


In [86]:
For[u = 1, u <= 24, u++, Print["CombDirRight[[", u, "]]=", AdcdrVertex[[u]], ";"]];

CombDirRight[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 9}, {6, 10}};
CombDirRight[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 9}, {6, 8}};
CombDirRight[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 9}, {4, 10}};
CombDirRight[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 9}, {4, 8}};
CombDirRight[[5]]={{1, 4}, {3, 5}, {2, 8}, {7, 9}, {6, 10}};
CombDirRight[[6]]={{1, 4}, {3, 5}, {2, 10}, {7, 9}, {6, 8}};
CombDirRight[[7]]={{1, 4}, {3, 6}, {5, 8}, {7, 9}, {2, 10}};
CombDirRight[[8]]={{1, 4}, {3, 6}, {5, 10}, {7, 9}, {2, 8}};
CombDirRight[[9]]={{1, 4}, {3, 8}, {2, 5}, {7, 9}, {6, 10}};
CombDirRight[[10]]={{1, 4}, {3, 8}, {5, 10}, {7, 9}, {2, 6}};
CombDirRight[[11]]={{1, 4}, {3, 10}, {5, 8}, {7, 9}, {2, 6}};
CombDirRight[[12]]={{1, 4}, {3, 10}, {2, 5}, {7, 9}, {6, 8}};
CombDirRight[[13]]={{1, 5}, {3, 6}, {2, 8}, {7, 9}, {4, 10}};
CombDirRight[[14]]={{1, 5}, {3, 6}, {2, 10}, {7, 9}, {4, 8}};
CombDirRight[[15]]={{1, 5}, {3, 8}, {2, 4}, {7, 9}, {6, 10}};
CombDirRight[[16]]={{1, 5}, {3, 8}, {2, 10}, {7, 9}, {4, 6}};
CombDirRight[[17]

In [87]:
For[u = 1, u <= 24, u++, Print["GGFMult[[", u, "]]=", MultdcdrVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent third-order right-dressed disjoint direct diagrams with two identical one-body vertices. The multiplicity check is fulfilled.

In [88]:
Sum[MultdcdrVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Right-dressed disjoint direct diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $8$ inequivalent fully-contracted terms corresponding to right-dressed disjoint direct diagrams are found. 

In [89]:
AdcdrVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcdrVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcdrVertex[[1]] = AdisjDirRight[[1]];
MultdcdrVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirRight[[u, i, j]];
   If[AdisjDirRight[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirRight[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirRight[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirRight[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirRight[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirRight[[u, i, j]]];
   If[AdisjDirRight[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjDirRight[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjDirRight[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjDirRight[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjDirRight[[u, i, j]] >= 3 && 
       AdisjDirRight[[u, i, j]] <= 4) || 
     AdisjDirRight[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjDirRight[[u, i, j]]];
   If[AdisjDirRight[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjDirRight[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjDirRight[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjDirRight[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjDirRight[[u, i, j]] <= 2 || AdisjDirRight[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjDirRight[[u, i, j]]];
   If[AdisjDirRight[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjDirRight[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjDirRight[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjDirRight[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjDirRight[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjDirRight[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjDirRight[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjDirRight[[u, i, j]]];
   If[AdisjDirRight[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjDirRight[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjDirRight[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjDirRight[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjDirRight[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjDirRight[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjDirRight[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjDirRight[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdrVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdrVertex[[v]] = MultdcdrVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdrVertex[[s]] = AdisjDirRight[[u]]; 
   MultdcdrVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent right-dressed direct contributions found."]];
 ]

Loop 48 completed and 8 inequivalent right-dressed direct contributions found.


In [98]:
For[u = 1, u <= 8, u++, Print["CombDirRight[[", u, "]]=", AdcdrVertex[[u]], ";"]];

CombDirRight[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 9}, {6, 10}};
CombDirRight[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 9}, {6, 8}};
CombDirRight[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 9}, {4, 10}};
CombDirRight[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 9}, {4, 8}};
CombDirRight[[5]]={{1, 4}, {3, 6}, {5, 8}, {7, 9}, {2, 10}};
CombDirRight[[6]]={{1, 4}, {3, 6}, {5, 10}, {7, 9}, {2, 8}};
CombDirRight[[7]]={{1, 4}, {3, 8}, {5, 10}, {7, 9}, {2, 6}};
CombDirRight[[8]]={{1, 4}, {3, 10}, {5, 8}, {7, 9}, {2, 6}};


In [99]:
For[u = 1, u <= 8, u++, Print["GGFMult[[", u, "]]=", MultdcdrVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order right-dressed disjoint direct diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [100]:
Sum[MultdcdrVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint direct diagrams with left-and-right-dressed single-particle propagators</font>

Direct diagrams with perturbed 1-body propagators on the left and the right are processed. Their initial number is $96$ in total.

### <font color=#E9967A>Left-and-right-dressed disjoint direct diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent left-and-right-dressed disjoint direct contributions with three non-identical vertices at third order remains equal to $96$.

In [101]:
For[u = 1, u <= 96, u++, Print["CombDir[[", u, "]]=", AdisjDirect[[u]], ";"]];

CombDir[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 9}, {6, 10}};
CombDir[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 9}, {6, 8}};
CombDir[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 9}, {4, 10}};
CombDir[[4]]={{1, 3}, {2, 8}, {5, 9}, {6, 7}, {4, 10}};
CombDir[[5]]={{1, 3}, {2, 9}, {5, 8}, {4, 7}, {6, 10}};
CombDir[[6]]={{1, 3}, {2, 9}, {5, 10}, {4, 7}, {6, 8}};
CombDir[[7]]={{1, 3}, {2, 10}, {5, 7}, {6, 9}, {4, 8}};
CombDir[[8]]={{1, 3}, {2, 10}, {5, 9}, {6, 7}, {4, 8}};
CombDir[[9]]={{1, 4}, {3, 7}, {5, 8}, {2, 9}, {6, 10}};
CombDir[[10]]={{1, 4}, {3, 7}, {5, 10}, {2, 9}, {6, 8}};
CombDir[[11]]={{1, 4}, {3, 8}, {5, 7}, {6, 9}, {2, 10}};
CombDir[[12]]={{1, 4}, {3, 8}, {5, 9}, {6, 7}, {2, 10}};
CombDir[[13]]={{1, 4}, {3, 9}, {5, 8}, {2, 7}, {6, 10}};
CombDir[[14]]={{1, 4}, {3, 9}, {5, 10}, {2, 7}, {6, 8}};
CombDir[[15]]={{1, 4}, {3, 10}, {5, 7}, {6, 9}, {2, 8}};
CombDir[[16]]={{1, 4}, {3, 10}, {5, 9}, {6, 7}, {2, 8}};
CombDir[[17]]={{1, 5}, {3, 7}, {2, 8}, {4, 9}, {6, 10}};
CombDir[[18]]={{1, 5}, {3, 7}, {2, 10}, 

In [102]:
For[u = 1, u <= 96, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;
GGFMult[[49]]=1;
GGFMult[[50]]=1;
GGFMult[[51]]=1;
GGFMult[[52]]=1;
GGFMult[[53]]=1;
GGFMult[[54]]=1;
GGFMult[[55]]=1;
GGFMult[[56]]=1;
GGFMult[[57]]=1;
GGFMult[[58]]=1;
GGFMult[[59]]=1;
GGFMul

There are only $96$ third-order left-and-right-dressed disjoint direct diagrams with non-identical one-body vertices. The multiplicity check is fulfilled.

### <font color=#E9967A>Left-and-right-dressed disjoint direct diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $48$ inequivalent fully-contracted terms corresponding to left-and-right-dressed disjoint direct diagrams are found.

In [112]:
AdcdVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdcdVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcdVertex[[1]] = AdisjDirect[[1]];
MultdcdVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirect[[u, i, j]];
   If[AdisjDirect[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirect[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirect[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirect[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirect[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirect[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdVertex[[v]] = MultdcdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdVertex[[s]] = AdisjDirect[[u]]; 
   MultdcdVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent left-and-right-dressed direct contributions found."]];
 ]

Loop 96 completed and 48 inequivalent left-and-right-dressed direct\
 
>    contributions found.


In [121]:
For[u = 1, u <= 48, u++, Print["CombDir[[", u, "]]=", AdcdVertex[[u]], ";"]];

CombDir[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 9}, {6, 10}};
CombDir[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 9}, {6, 8}};
CombDir[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 9}, {4, 10}};
CombDir[[4]]={{1, 3}, {2, 8}, {5, 9}, {6, 7}, {4, 10}};
CombDir[[5]]={{1, 4}, {3, 7}, {5, 8}, {2, 9}, {6, 10}};
CombDir[[6]]={{1, 4}, {3, 7}, {5, 10}, {2, 9}, {6, 8}};
CombDir[[7]]={{1, 4}, {3, 8}, {5, 7}, {6, 9}, {2, 10}};
CombDir[[8]]={{1, 4}, {3, 8}, {5, 9}, {6, 7}, {2, 10}};
CombDir[[9]]={{1, 4}, {3, 9}, {5, 8}, {2, 7}, {6, 10}};
CombDir[[10]]={{1, 4}, {3, 9}, {5, 10}, {2, 7}, {6, 8}};
CombDir[[11]]={{1, 4}, {3, 10}, {5, 7}, {6, 9}, {2, 8}};
CombDir[[12]]={{1, 4}, {3, 10}, {5, 9}, {6, 7}, {2, 8}};
CombDir[[13]]={{1, 5}, {3, 7}, {2, 8}, {4, 9}, {6, 10}};
CombDir[[14]]={{1, 5}, {3, 7}, {2, 10}, {4, 9}, {6, 8}};
CombDir[[15]]={{1, 5}, {3, 8}, {2, 7}, {6, 9}, {4, 10}};
CombDir[[16]]={{1, 5}, {3, 8}, {2, 9}, {6, 7}, {4, 10}};
CombDir[[17]]={{1, 5}, {3, 9}, {2, 8}, {4, 7}, {6, 10}};
CombDir[[18]]={{1, 5}, {3, 9}, {2, 10}, 

In [122]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", MultdcdVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;
GGFMult[[25]]=2;
GGFMult[[26]]=2;
GGFMult[[27]]=2;
GGFMult[[28]]=2;
GGFMult[[29]]=2;
GGFMult[[30]]=2;
GGFMult[[31]]=2;
GGFMult[[32]]=2;
GGFMult[[33]]=2;
GGFMult[[34]]=2;
GGFMult[[35]]=2;
GGFMult[[36]]=2;
GGFMult[[37]]=2;
GGFMult[[38]]=2;
GGFMult[[39]]=2;
GGFMult[[40]]=2;
GGFMult[[41]]=2;
GGFMult[[42]]=2;
GGFMult[[43]]=2;
GGFMult[[44]]=2;
GGFMult[[45]]=2;
GGFMult[[46]]=2;
GGFMult[[47]]=2;
GGFMult[[48]]=2;


There are only $48$ inequivalent third-order left-and-right-dressed disjoint direct diagrams with two identical one-body vertices. The multiplicity check is fulfilled.

In [123]:
Sum[MultdcdVertex[[u]], {u, 1, 48}]

96

### <font color=#E9967A>Left-and-right-dressed disjoint direct diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $16$ inequivalent fully-contracted terms corresponding to left-and-right-dressed disjoint direct diagrams are found. 

In [133]:
AdcdVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdcdVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcdVertex[[1]] = AdisjDirect[[1]];
MultdcdVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjDirect[[u, i, j]];
   If[AdisjDirect[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjDirect[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjDirect[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjDirect[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjDirect[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirect[[u, i, j]]];
   If[AdisjDirect[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjDirect[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjDirect[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjDirect[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjDirect[[u, i, j]] >= 3 && AdisjDirect[[u, i, j]] <= 4) || 
     AdisjDirect[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjDirect[[u, i, j]]];
   If[AdisjDirect[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjDirect[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjDirect[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjDirect[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjDirect[[u, i, j]] <= 2 || AdisjDirect[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjDirect[[u, i, j]]];
   If[AdisjDirect[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjDirect[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjDirect[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjDirect[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjDirect[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjDirect[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjDirect[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjDirect[[u, i, j]]];
   If[AdisjDirect[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjDirect[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjDirect[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjDirect[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjDirect[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjDirect[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjDirect[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjDirect[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdVertex[[v]] = MultdcdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcdVertex[[s]] = AdisjDirect[[u]]; 
   MultdcdVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent left-and-right-dressed direct contributions found."]];
 ]

Loop 96 completed and 16 inequivalent left-and-right-dressed direct\
 
>    contributions found.


In [142]:
For[u = 1, u <= 16, u++, Print["CombDir[[", u, "]]=", AdcdVertex[[u]], ";"]];

CombDir[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 9}, {6, 10}};
CombDir[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 9}, {6, 8}};
CombDir[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 9}, {4, 10}};
CombDir[[4]]={{1, 3}, {2, 8}, {5, 9}, {6, 7}, {4, 10}};
CombDir[[5]]={{1, 4}, {3, 7}, {5, 8}, {2, 9}, {6, 10}};
CombDir[[6]]={{1, 4}, {3, 7}, {5, 10}, {2, 9}, {6, 8}};
CombDir[[7]]={{1, 4}, {3, 8}, {5, 7}, {6, 9}, {2, 10}};
CombDir[[8]]={{1, 4}, {3, 8}, {5, 9}, {6, 7}, {2, 10}};
CombDir[[9]]={{1, 4}, {3, 9}, {5, 8}, {2, 7}, {6, 10}};
CombDir[[10]]={{1, 4}, {3, 9}, {5, 10}, {2, 7}, {6, 8}};
CombDir[[11]]={{1, 4}, {3, 10}, {5, 7}, {6, 9}, {2, 8}};
CombDir[[12]]={{1, 4}, {3, 10}, {5, 9}, {6, 7}, {2, 8}};
CombDir[[13]]={{1, 7}, {3, 8}, {5, 9}, {2, 6}, {4, 10}};
CombDir[[14]]={{1, 7}, {3, 8}, {5, 10}, {2, 9}, {4, 6}};
CombDir[[15]]={{1, 7}, {3, 9}, {5, 10}, {2, 4}, {6, 8}};
CombDir[[16]]={{1, 8}, {3, 9}, {5, 10}, {4, 7}, {2, 6}};


In [143]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdcdVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;
GGFMult[[9]]=6;
GGFMult[[10]]=6;
GGFMult[[11]]=6;
GGFMult[[12]]=6;
GGFMult[[13]]=6;
GGFMult[[14]]=6;
GGFMult[[15]]=6;
GGFMult[[16]]=6;


There are only $16$ inequivalent third-order left-and-right-dressed disjoint direct diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [144]:
Sum[MultdcdVertex[[u]], {u, 1, 16}]

96

## <font color=#FA8072>Disjoint exchange diagrams with dressed single-particle propagator above</font>

Exchange diagrams with unperturbed 1-body propagator below are processed. Their initial number is $48$ in total.

### <font color=#E9967A>Above-dressed disjoint exchange diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent above-dressed disjoint exchange contributions with non-identical vertices at third order remains equal to $48$.

In [145]:
For[u = 1, u <= 48, u++, Print["CombExcAbove[[", u, "]]=", AdisjExchAbove[[u]], ";"]];

CombExcAbove[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 10}, {8, 9}};
CombExcAbove[[2]]={{1, 3}, {2, 5}, {4, 10}, {6, 7}, {8, 9}};
CombExcAbove[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 10}, {8, 9}};
CombExcAbove[[4]]={{1, 3}, {2, 6}, {5, 10}, {4, 7}, {8, 9}};
CombExcAbove[[5]]={{1, 3}, {2, 7}, {4, 5}, {6, 10}, {8, 9}};
CombExcAbove[[6]]={{1, 3}, {2, 7}, {5, 10}, {4, 6}, {8, 9}};
CombExcAbove[[7]]={{1, 3}, {2, 10}, {5, 7}, {4, 6}, {8, 9}};
CombExcAbove[[8]]={{1, 3}, {2, 10}, {4, 5}, {6, 7}, {8, 9}};
CombExcAbove[[9]]={{1, 4}, {3, 5}, {2, 7}, {6, 10}, {8, 9}};
CombExcAbove[[10]]={{1, 4}, {3, 5}, {2, 10}, {6, 7}, {8, 9}};
CombExcAbove[[11]]={{1, 4}, {3, 6}, {5, 7}, {2, 10}, {8, 9}};
CombExcAbove[[12]]={{1, 4}, {3, 6}, {5, 10}, {2, 7}, {8, 9}};
CombExcAbove[[13]]={{1, 4}, {3, 7}, {2, 5}, {6, 10}, {8, 9}};
CombExcAbove[[14]]={{1, 4}, {3, 7}, {5, 10}, {2, 6}, {8, 9}};
CombExcAbove[[15]]={{1, 4}, {3, 10}, {5, 7}, {2, 6}, {8, 9}};
CombExcAbove[[16]]={{1, 4}, {3, 10}, {2, 5}, {6, 7}, {8, 9}};
CombExcAbove[[17]

In [146]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only $48$ third-order above-dressed disjoint exchange diagrams with non-identical one-body vertices. The multiplicity check is fulfilled.

### <font color=#E9967A>Above-dressed disjoint exchange diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $48$ inequivalent fully-contracted terms corresponding to above-dressed disjoint exchange diagrams are found.

In [147]:
AdceaVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdceaVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdceaVertex[[1]] = AdisjExchAbove[[1]];
MultdceaVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchAbove[[u, i, j]];
   If[AdisjExchAbove[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchAbove[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchAbove[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchAbove[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchAbove[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchAbove[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdceaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceaVertex[[v]] = MultdceaVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdceaVertex[[s]] = AdisjExchAbove[[u]]; 
   MultdceaVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-dressed exchange contributions found."]];
 ]

Loop 48 completed and 24 inequivalent above-dressed exchange contributions\
 
>    found.


In [156]:
For[u = 1, u <= 24, u++, Print["CombExchAbove[[", u, "]]=", AdceaVertex[[u]], ";"]];

CombExchAbove[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 10}, {8, 9}};
CombExchAbove[[2]]={{1, 3}, {2, 5}, {4, 10}, {6, 7}, {8, 9}};
CombExchAbove[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 10}, {8, 9}};
CombExchAbove[[4]]={{1, 3}, {2, 6}, {5, 10}, {4, 7}, {8, 9}};
CombExchAbove[[5]]={{1, 4}, {3, 5}, {2, 7}, {6, 10}, {8, 9}};
CombExchAbove[[6]]={{1, 4}, {3, 5}, {2, 10}, {6, 7}, {8, 9}};
CombExchAbove[[7]]={{1, 4}, {3, 6}, {5, 7}, {2, 10}, {8, 9}};
CombExchAbove[[8]]={{1, 4}, {3, 6}, {5, 10}, {2, 7}, {8, 9}};
CombExchAbove[[9]]={{1, 4}, {3, 7}, {2, 5}, {6, 10}, {8, 9}};
CombExchAbove[[10]]={{1, 4}, {3, 7}, {5, 10}, {2, 6}, {8, 9}};
CombExchAbove[[11]]={{1, 4}, {3, 10}, {5, 7}, {2, 6}, {8, 9}};
CombExchAbove[[12]]={{1, 4}, {3, 10}, {2, 5}, {6, 7}, {8, 9}};
CombExchAbove[[13]]={{1, 5}, {3, 6}, {2, 7}, {4, 10}, {8, 9}};
CombExchAbove[[14]]={{1, 5}, {3, 6}, {2, 10}, {4, 7}, {8, 9}};
CombExchAbove[[15]]={{1, 5}, {3, 7}, {2, 4}, {6, 10}, {8, 9}};
CombExchAbove[[16]]={{1, 5}, {3, 7}, {2, 10}, {4, 6}, {8, 9}};
C

In [157]:
For[u = 1, u <= 24, u++, Print["GGFMult[[", u, "]]=", MultdceaVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent second-order above-dressed disjoint exchange diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [158]:
Sum[MultdceaVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Above-dressed disjoint exchange diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $8$ inequivalent fully-contracted terms corresponding to above-dressed disjoint exchange diagrams are found. 

In [159]:
AdceaVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdceaVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdceaVertex[[1]] = AdisjExchAbove[[1]];
MultdceaVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchAbove[[u, i, j]];
   If[AdisjExchAbove[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchAbove[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchAbove[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchAbove[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchAbove[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[AdisjExchAbove[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjExchAbove[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjExchAbove[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjExchAbove[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjExchAbove[[u, i, j]] >= 3 && 
       AdisjExchAbove[[u, i, j]] <= 4) || 
     AdisjExchAbove[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[AdisjExchAbove[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjExchAbove[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjExchAbove[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjExchAbove[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjExchAbove[[u, i, j]] <= 2 || 
     AdisjExchAbove[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[AdisjExchAbove[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjExchAbove[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjExchAbove[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjExchAbove[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjExchAbove[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjExchAbove[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjExchAbove[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[AdisjExchAbove[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjExchAbove[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjExchAbove[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjExchAbove[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjExchAbove[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjExchAbove[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjExchAbove[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjExchAbove[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdceaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceaVertex[[v]] = MultdceaVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdceaVertex[[s]] = AdisjExchAbove[[u]]; 
   MultdceaVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-dressed exchange contributions found."]];
 ]

Loop 48 completed and 8 inequivalent above-dressed exchange contributions\
 
>    found.


In [168]:
For[u = 1, u <= 8, u++, Print["CombExcAbove[[", u, "]]=", AdceaVertex[[u]], ";"]];

CombExcAbove[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 10}, {8, 9}};
CombExcAbove[[2]]={{1, 3}, {2, 5}, {4, 10}, {6, 7}, {8, 9}};
CombExcAbove[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 10}, {8, 9}};
CombExcAbove[[4]]={{1, 3}, {2, 6}, {5, 10}, {4, 7}, {8, 9}};
CombExcAbove[[5]]={{1, 4}, {3, 6}, {5, 7}, {2, 10}, {8, 9}};
CombExcAbove[[6]]={{1, 4}, {3, 6}, {5, 10}, {2, 7}, {8, 9}};
CombExcAbove[[7]]={{1, 4}, {3, 7}, {5, 10}, {2, 6}, {8, 9}};
CombExcAbove[[8]]={{1, 4}, {3, 10}, {5, 7}, {2, 6}, {8, 9}};


In [169]:
For[u = 1, u <= 8, u++, Print["GGFMult[[", u, "]]=", MultdceaVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order above-dressed disjoint exchange diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [170]:
Sum[MultdceaVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint exchange diagrams with dressed single-particle propagator below</font>

Exchange diagrams with unperturbed 1-body propagator above are processed. Their initial number is $48$ in total.

### <font color=#E9967A>Below-dressed disjoint exchange diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent below-dressed disjoint exchange contributions with non-identical vertices at second order remains equal to $48$.

In [171]:
For[u = 1, u <= 48, u++, Print["CombExcBelow[[", u, "]]=", AdisjExchBelow[[u]], ";"]];

CombExcBelow[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 10}, {6, 9}};
CombExcBelow[[2]]={{1, 3}, {2, 5}, {4, 9}, {7, 10}, {6, 8}};
CombExcBelow[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 10}, {4, 9}};
CombExcBelow[[4]]={{1, 3}, {2, 6}, {5, 9}, {7, 10}, {4, 8}};
CombExcBelow[[5]]={{1, 3}, {2, 8}, {4, 5}, {7, 10}, {6, 9}};
CombExcBelow[[6]]={{1, 3}, {2, 8}, {5, 9}, {7, 10}, {4, 6}};
CombExcBelow[[7]]={{1, 3}, {2, 9}, {5, 8}, {7, 10}, {4, 6}};
CombExcBelow[[8]]={{1, 3}, {2, 9}, {4, 5}, {7, 10}, {6, 8}};
CombExcBelow[[9]]={{1, 4}, {3, 5}, {2, 8}, {7, 10}, {6, 9}};
CombExcBelow[[10]]={{1, 4}, {3, 5}, {2, 9}, {7, 10}, {6, 8}};
CombExcBelow[[11]]={{1, 4}, {3, 6}, {5, 8}, {7, 10}, {2, 9}};
CombExcBelow[[12]]={{1, 4}, {3, 6}, {5, 9}, {7, 10}, {2, 8}};
CombExcBelow[[13]]={{1, 4}, {3, 8}, {2, 5}, {7, 10}, {6, 9}};
CombExcBelow[[14]]={{1, 4}, {3, 8}, {5, 9}, {7, 10}, {2, 6}};
CombExcBelow[[15]]={{1, 4}, {3, 9}, {5, 8}, {7, 10}, {2, 6}};
CombExcBelow[[16]]={{1, 4}, {3, 9}, {2, 5}, {7, 10}, {6, 8}};
CombExcBelow[[17]

In [172]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only $48$ second-order below-dressed disjoint exchange diagrams with non-identical one-body vertices. The multiplicity check is fulfilled by construction.

### <font color=#E9967A>Below-dressed disjoint exchange diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $24$ inequivalent fully-contracted terms corresponding to below-dressed disjoint exchange diagrams are found.  

In [173]:
AdcebVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcebVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcebVertex[[1]] = AdisjExchBelow[[1]];
MultdcebVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchBelow[[u, i, j]];
   If[AdisjExchBelow[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchBelow[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchBelow[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchBelow[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchBelow[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchBelow[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcebVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcebVertex[[v]] = MultdcebVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcebVertex[[s]] = AdisjExchBelow[[u]]; 
   MultdcebVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent below-dressed exchange contributions found."]];
 ]

Loop 48 completed and 24 inequivalent below-dressed exchange contributions\
 
>    found.


In [182]:
For[u = 1, u <= 24, u++, Print["CombExchBelow[[", u, "]]=", AdcebVertex[[u]], ";"]];

CombExchBelow[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 10}, {6, 9}};
CombExchBelow[[2]]={{1, 3}, {2, 5}, {4, 9}, {7, 10}, {6, 8}};
CombExchBelow[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 10}, {4, 9}};
CombExchBelow[[4]]={{1, 3}, {2, 6}, {5, 9}, {7, 10}, {4, 8}};
CombExchBelow[[5]]={{1, 4}, {3, 5}, {2, 8}, {7, 10}, {6, 9}};
CombExchBelow[[6]]={{1, 4}, {3, 5}, {2, 9}, {7, 10}, {6, 8}};
CombExchBelow[[7]]={{1, 4}, {3, 6}, {5, 8}, {7, 10}, {2, 9}};
CombExchBelow[[8]]={{1, 4}, {3, 6}, {5, 9}, {7, 10}, {2, 8}};
CombExchBelow[[9]]={{1, 4}, {3, 8}, {2, 5}, {7, 10}, {6, 9}};
CombExchBelow[[10]]={{1, 4}, {3, 8}, {5, 9}, {7, 10}, {2, 6}};
CombExchBelow[[11]]={{1, 4}, {3, 9}, {5, 8}, {7, 10}, {2, 6}};
CombExchBelow[[12]]={{1, 4}, {3, 9}, {2, 5}, {7, 10}, {6, 8}};
CombExchBelow[[13]]={{1, 5}, {3, 6}, {2, 8}, {7, 10}, {4, 9}};
CombExchBelow[[14]]={{1, 5}, {3, 6}, {2, 9}, {7, 10}, {4, 8}};
CombExchBelow[[15]]={{1, 5}, {3, 8}, {2, 4}, {7, 10}, {6, 9}};
CombExchBelow[[16]]={{1, 5}, {3, 8}, {2, 9}, {7, 10}, {4, 6}};
C

In [183]:
For[u = 1, u <= 24, u++, Print["GGFMult[[", u, "]]=", MultdcebVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent second-order below-dressed disjoint exchange diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [184]:
Sum[MultdcebVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Below-dressed disjoint exchange diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $8$ inequivalent fully-contracted terms corresponding to below-dressed disjoint exchange diagrams are found. 

In [185]:
AdcebVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcebVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcebVertex[[1]] = AdisjExchBelow[[1]];
MultdcebVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchBelow[[u, i, j]];
   If[AdisjExchBelow[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchBelow[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchBelow[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchBelow[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchBelow[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[AdisjExchBelow[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjExchBelow[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjExchBelow[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjExchBelow[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjExchBelow[[u, i, j]] >= 3 && 
       AdisjExchBelow[[u, i, j]] <= 4) || 
     AdisjExchBelow[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[AdisjExchBelow[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjExchBelow[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjExchBelow[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjExchBelow[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjExchBelow[[u, i, j]] <= 2 || 
     AdisjExchBelow[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[AdisjExchBelow[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjExchBelow[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjExchBelow[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjExchBelow[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjExchBelow[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjExchBelow[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjExchBelow[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[AdisjExchBelow[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjExchBelow[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjExchBelow[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjExchBelow[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjExchBelow[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjExchBelow[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjExchBelow[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjExchBelow[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcebVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcebVertex[[v]] = MultdcebVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcebVertex[[s]] = AdisjExchBelow[[u]]; 
   MultdcebVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent below-dressed exchange contributions found."]];
 ]

Loop 48 completed and 8 inequivalent below-dressed exchange contributions\
 
>    found.


In [194]:
For[u = 1, u <= 8, u++, 
  Print["CombExcBelow[[", u, "]]=", AdcebVertex[[u]], ";"]];

CombExcBelow[[1]]={{1, 3}, {2, 5}, {4, 8}, {7, 10}, {6, 9}};
CombExcBelow[[2]]={{1, 3}, {2, 5}, {4, 9}, {7, 10}, {6, 8}};
CombExcBelow[[3]]={{1, 3}, {2, 6}, {5, 8}, {7, 10}, {4, 9}};
CombExcBelow[[4]]={{1, 3}, {2, 6}, {5, 9}, {7, 10}, {4, 8}};
CombExcBelow[[5]]={{1, 4}, {3, 6}, {5, 8}, {7, 10}, {2, 9}};
CombExcBelow[[6]]={{1, 4}, {3, 6}, {5, 9}, {7, 10}, {2, 8}};
CombExcBelow[[7]]={{1, 4}, {3, 8}, {5, 9}, {7, 10}, {2, 6}};
CombExcBelow[[8]]={{1, 4}, {3, 9}, {5, 8}, {7, 10}, {2, 6}};


In [195]:
For[u = 1, u <= 8, u++, 
  Print["GGFMult[[", u, "]]=", MultdcebVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order below-dressed disjoint exchange diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [196]:
Sum[MultdcebVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint exchange diagrams with dressed single-particle propagators above and below</font>

Exchange diagrams with unperturbed 1-body propagators above and below are processed. Their initial number is $96$ in total.

### <font color=#E9967A>Above-and-below-dressed disjoint exchange diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent above-and-below-dressed disjoint exchange contributions with non-identical vertices at third order remains equal to $96$.

In [197]:
For[u = 1, u <= 96, u++, Print["CombExchange[[", u, "]]=", AdisjExchange[[u]], ";"]];

CombExchange[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 10}, {6, 9}};
CombExchange[[2]]={{1, 3}, {2, 7}, {5, 9}, {4, 10}, {6, 8}};
CombExchange[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 10}, {4, 9}};
CombExchange[[4]]={{1, 3}, {2, 8}, {5, 10}, {6, 7}, {4, 9}};
CombExchange[[5]]={{1, 3}, {2, 9}, {5, 7}, {6, 10}, {4, 8}};
CombExchange[[6]]={{1, 3}, {2, 9}, {5, 10}, {6, 7}, {4, 8}};
CombExchange[[7]]={{1, 3}, {2, 10}, {5, 8}, {4, 7}, {6, 9}};
CombExchange[[8]]={{1, 3}, {2, 10}, {5, 9}, {4, 7}, {6, 8}};
CombExchange[[9]]={{1, 4}, {3, 7}, {5, 8}, {2, 10}, {6, 9}};
CombExchange[[10]]={{1, 4}, {3, 7}, {5, 9}, {2, 10}, {6, 8}};
CombExchange[[11]]={{1, 4}, {3, 8}, {5, 7}, {6, 10}, {2, 9}};
CombExchange[[12]]={{1, 4}, {3, 8}, {5, 10}, {6, 7}, {2, 9}};
CombExchange[[13]]={{1, 4}, {3, 9}, {5, 7}, {6, 10}, {2, 8}};
CombExchange[[14]]={{1, 4}, {3, 9}, {5, 10}, {6, 7}, {2, 8}};
CombExchange[[15]]={{1, 4}, {3, 10}, {5, 8}, {2, 7}, {6, 9}};
CombExchange[[16]]={{1, 4}, {3, 10}, {5, 9}, {2, 7}, {6, 8}};
CombExchange[[17]

In [198]:
For[u = 1, u <= 96, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;
GGFMult[[49]]=1;
GGFMult[[50]]=1;
GGFMult[[51]]=1;
GGFMult[[52]]=1;
GGFMult[[53]]=1;
GGFMult[[54]]=1;
GGFMult[[55]]=1;
GGFMult[[56]]=1;
GGFMult[[57]]=1;
GGFMult[[58]]=1;
GGFMult[[59]]=1;
GGFMul

There are only 96 third-order below-dressed disjoint exchange diagrams with non-identical one-body vertices. The multiplicity check is fulfilled by construction.

### <font color=#E9967A>Above-and-below-dressed disjoint exchange diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $48$ inequivalent fully-contracted terms corresponding to above-and-below-dressed disjoint exchange diagrams are found.  

In [209]:
AdceVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdceVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdceVertex[[1]] = AdisjExchange[[1]];
MultdceVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchange[[u, i, j]];
   If[AdisjExchange[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchange[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchange[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchange[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchange[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchange[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdceVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceVertex[[v]] = MultdceVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdceVertex[[s]] = AdisjExchange[[u]]; 
   MultdceVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-and-below-dressed exchange contributions found."]];
 ]

Loop 96 completed and 48 inequivalent above-and-below-dressed exchange\
 
>    contributions found.


In [208]:
For[u = 1, u <= 48, u++, Print["CombExc[[", u, "]]=", AdceVertex[[u]], ";"]];

CombExc[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 10}, {6, 9}};
CombExc[[2]]={{1, 3}, {2, 7}, {5, 9}, {4, 10}, {6, 8}};
CombExc[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 10}, {4, 9}};
CombExc[[4]]={{1, 3}, {2, 8}, {5, 10}, {6, 7}, {4, 9}};
CombExc[[5]]={{1, 4}, {3, 7}, {5, 8}, {2, 10}, {6, 9}};
CombExc[[6]]={{1, 4}, {3, 7}, {5, 9}, {2, 10}, {6, 8}};
CombExc[[7]]={{1, 4}, {3, 8}, {5, 7}, {6, 10}, {2, 9}};
CombExc[[8]]={{1, 4}, {3, 8}, {5, 10}, {6, 7}, {2, 9}};
CombExc[[9]]={{1, 4}, {3, 9}, {5, 7}, {6, 10}, {2, 8}};
CombExc[[10]]={{1, 4}, {3, 9}, {5, 10}, {6, 7}, {2, 8}};
CombExc[[11]]={{1, 4}, {3, 10}, {5, 8}, {2, 7}, {6, 9}};
CombExc[[12]]={{1, 4}, {3, 10}, {5, 9}, {2, 7}, {6, 8}};
CombExc[[13]]={{1, 5}, {3, 7}, {2, 8}, {4, 10}, {6, 9}};
CombExc[[14]]={{1, 5}, {3, 7}, {2, 9}, {4, 10}, {6, 8}};
CombExc[[15]]={{1, 5}, {3, 8}, {2, 7}, {6, 10}, {4, 9}};
CombExc[[16]]={{1, 5}, {3, 8}, {2, 10}, {6, 7}, {4, 9}};
CombExc[[17]]={{1, 5}, {3, 9}, {2, 7}, {6, 10}, {4, 8}};
CombExc[[18]]={{1, 5}, {3, 9}, {2, 10}, 

In [218]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", MultdceVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;
GGFMult[[25]]=2;
GGFMult[[26]]=2;
GGFMult[[27]]=2;
GGFMult[[28]]=2;
GGFMult[[29]]=2;
GGFMult[[30]]=2;
GGFMult[[31]]=2;
GGFMult[[32]]=2;
GGFMult[[33]]=2;
GGFMult[[34]]=2;
GGFMult[[35]]=2;
GGFMult[[36]]=2;
GGFMult[[37]]=2;
GGFMult[[38]]=2;
GGFMult[[39]]=2;
GGFMult[[40]]=2;
GGFMult[[41]]=2;
GGFMult[[42]]=2;
GGFMult[[43]]=2;
GGFMult[[44]]=2;
GGFMult[[45]]=2;
GGFMult[[46]]=2;
GGFMult[[47]]=2;
GGFMult[[48]]=2;


There are only $48$ inequivalent second-order above-and-below-dressed disjoint exchange diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [219]:
Sum[MultdceVertex[[u]], {u, 1, 48}]

96

### <font color=#E9967A>Above-and-below-dressed disjoint exchange diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $16$ inequivalent fully-contracted terms corresponding to above-and-below-dressed disjoint exchange diagrams are found. 

In [229]:
AdceVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdceVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdceVertex[[1]] = AdisjExchange[[1]];
MultdceVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjExchange[[u, i, j]];
   If[AdisjExchange[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjExchange[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjExchange[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjExchange[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjExchange[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchange[[u, i, j]]];
   If[AdisjExchange[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjExchange[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjExchange[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjExchange[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjExchange[[u, i, j]] >= 3 && 
       AdisjExchange[[u, i, j]] <= 4) || 
     AdisjExchange[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjExchange[[u, i, j]]];
   If[AdisjExchange[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjExchange[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjExchange[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjExchange[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjExchange[[u, i, j]] <= 2 || AdisjExchange[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjExchange[[u, i, j]]];
   If[AdisjExchange[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjExchange[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjExchange[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjExchange[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjExchange[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjExchange[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjExchange[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjExchange[[u, i, j]]];
   If[AdisjExchange[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjExchange[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjExchange[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjExchange[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjExchange[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjExchange[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjExchange[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjExchange[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdceVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceVertex[[v]] = MultdceVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdceVertex[[s]] = AdisjExchange[[u]]; 
   MultdceVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-and-below-dressed exchange contributions found."]];
 ]

Loop 96 completed and 16 inequivalent above-and-below-dressed exchange\
 
>    contributions found.


In [238]:
For[u = 1, u <= 16, u++, Print["CombExc[[", u, "]]=", AdceVertex[[u]], ";"]];

CombExc[[1]]={{1, 3}, {2, 7}, {5, 8}, {4, 10}, {6, 9}};
CombExc[[2]]={{1, 3}, {2, 7}, {5, 9}, {4, 10}, {6, 8}};
CombExc[[3]]={{1, 3}, {2, 8}, {5, 7}, {6, 10}, {4, 9}};
CombExc[[4]]={{1, 3}, {2, 8}, {5, 10}, {6, 7}, {4, 9}};
CombExc[[5]]={{1, 4}, {3, 7}, {5, 8}, {2, 10}, {6, 9}};
CombExc[[6]]={{1, 4}, {3, 7}, {5, 9}, {2, 10}, {6, 8}};
CombExc[[7]]={{1, 4}, {3, 8}, {5, 7}, {6, 10}, {2, 9}};
CombExc[[8]]={{1, 4}, {3, 8}, {5, 10}, {6, 7}, {2, 9}};
CombExc[[9]]={{1, 4}, {3, 9}, {5, 7}, {6, 10}, {2, 8}};
CombExc[[10]]={{1, 4}, {3, 9}, {5, 10}, {6, 7}, {2, 8}};
CombExc[[11]]={{1, 4}, {3, 10}, {5, 8}, {2, 7}, {6, 9}};
CombExc[[12]]={{1, 4}, {3, 10}, {5, 9}, {2, 7}, {6, 8}};
CombExc[[13]]={{1, 7}, {3, 8}, {5, 9}, {2, 10}, {4, 6}};
CombExc[[14]]={{1, 7}, {3, 8}, {5, 10}, {2, 6}, {4, 9}};
CombExc[[15]]={{1, 7}, {3, 9}, {5, 10}, {2, 6}, {4, 8}};
CombExc[[16]]={{1, 8}, {3, 9}, {5, 10}, {6, 7}, {2, 4}};


In [239]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdceVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;
GGFMult[[9]]=6;
GGFMult[[10]]=6;
GGFMult[[11]]=6;
GGFMult[[12]]=6;
GGFMult[[13]]=6;
GGFMult[[14]]=6;
GGFMult[[15]]=6;
GGFMult[[16]]=6;


There are only $16$ inequivalent third-order below-dressed disjoint exchange diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [240]:
Sum[MultdceVertex[[u]], {u, 1, 16}]

96

## <font color=#FA8072>Disjoint Bogoliubov diagrams with dressed single-particle propagator on the antidiagonal</font>

Bogoliubov diagrams with unperturbed 1-body propagator on the diagonal are processed. Their initial number is $48$ in total.

### <font color=#E9967A>Antidiagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent antidiagonally-dressed disjoint Bogoliubov contributions with non-identical vertices at third order remains equal to $48$.

In [241]:
For[u = 1, u <= 48, u++, Print["CombBogAntidiag[[", u, "]]=", AdisjBogoAntidiag[[u]], ";"]];

CombBogAntidiag[[1]]={{1, 3}, {2, 5}, {4, 9}, {7, 8}, {6, 10}};
CombBogAntidiag[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 8}, {6, 9}};
CombBogAntidiag[[3]]={{1, 3}, {2, 6}, {5, 9}, {7, 8}, {4, 10}};
CombBogAntidiag[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 8}, {4, 9}};
CombBogAntidiag[[5]]={{1, 3}, {2, 9}, {4, 5}, {7, 8}, {6, 10}};
CombBogAntidiag[[6]]={{1, 3}, {2, 9}, {5, 10}, {7, 8}, {4, 6}};
CombBogAntidiag[[7]]={{1, 3}, {2, 10}, {5, 9}, {7, 8}, {4, 6}};
CombBogAntidiag[[8]]={{1, 3}, {2, 10}, {4, 5}, {7, 8}, {6, 9}};
CombBogAntidiag[[9]]={{1, 4}, {3, 5}, {2, 9}, {7, 8}, {6, 10}};
CombBogAntidiag[[10]]={{1, 4}, {3, 5}, {2, 10}, {7, 8}, {6, 9}};
CombBogAntidiag[[11]]={{1, 4}, {3, 6}, {5, 9}, {7, 8}, {2, 10}};
CombBogAntidiag[[12]]={{1, 4}, {3, 6}, {5, 10}, {7, 8}, {2, 9}};
CombBogAntidiag[[13]]={{1, 4}, {3, 9}, {2, 5}, {7, 8}, {6, 10}};
CombBogAntidiag[[14]]={{1, 4}, {3, 9}, {5, 10}, {7, 8}, {2, 6}};
CombBogAntidiag[[15]]={{1, 4}, {3, 10}, {5, 9}, {7, 8}, {2, 6}};
CombBogAntidiag[[16]]={{1, 4}, {3,

In [242]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only $48$ third-order antidiagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices. The multiplicity check is fulfilled.

### <font color=#E9967A>Antidiagonally-dressed disjoint Bogoliubov diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $24$ inequivalent fully-contracted terms corresponding to antidiagonally-dressed disjoint Bogoliubov diagrams are found.    

In [252]:
AdcbaVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcbaVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcbaVertex[[1]] = AdisjBogoAntidiag[[1]];
MultdcbaVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoAntidiag[[u, i, j]];
   If[AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoAntidiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbaVertex[[v]] = MultdcbaVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; 
   AdcbaVertex[[s]] = AdisjBogoAntidiag[[u]]; MultdcbaVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent antidiagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 48 completed and 24 inequivalent antidiagonally-dressed Bogoliubov\
 
>    contributions found.


In [261]:
For[u = 1, u <= 24, u++, Print["CombBogAntidiag[[", u, "]]=", AdcbaVertex[[u]], ";"]];

CombBogAntidiag[[1]]={{1, 3}, {2, 5}, {4, 9}, {7, 8}, {6, 10}};
CombBogAntidiag[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 8}, {6, 9}};
CombBogAntidiag[[3]]={{1, 3}, {2, 6}, {5, 9}, {7, 8}, {4, 10}};
CombBogAntidiag[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 8}, {4, 9}};
CombBogAntidiag[[5]]={{1, 4}, {3, 5}, {2, 9}, {7, 8}, {6, 10}};
CombBogAntidiag[[6]]={{1, 4}, {3, 5}, {2, 10}, {7, 8}, {6, 9}};
CombBogAntidiag[[7]]={{1, 4}, {3, 6}, {5, 9}, {7, 8}, {2, 10}};
CombBogAntidiag[[8]]={{1, 4}, {3, 6}, {5, 10}, {7, 8}, {2, 9}};
CombBogAntidiag[[9]]={{1, 4}, {3, 9}, {2, 5}, {7, 8}, {6, 10}};
CombBogAntidiag[[10]]={{1, 4}, {3, 9}, {5, 10}, {7, 8}, {2, 6}};
CombBogAntidiag[[11]]={{1, 4}, {3, 10}, {5, 9}, {7, 8}, {2, 6}};
CombBogAntidiag[[12]]={{1, 4}, {3, 10}, {2, 5}, {7, 8}, {6, 9}};
CombBogAntidiag[[13]]={{1, 5}, {3, 6}, {2, 9}, {7, 8}, {4, 10}};
CombBogAntidiag[[14]]={{1, 5}, {3, 6}, {2, 10}, {7, 8}, {4, 9}};
CombBogAntidiag[[15]]={{1, 5}, {3, 9}, {2, 4}, {7, 8}, {6, 10}};
CombBogAntidiag[[16]]={{1, 5}, {3,

In [262]:
For[u = 1, u <= 24, u++, Print["GGFMult[[", u, "]]=", MultdcbaVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent third-order antidiagonally-dressed disjoint Bogoliubov diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [263]:
Sum[MultdcbaVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Antidiagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, 8 inequivalent fully-contracted terms corresponding to antidiagonally-dressed disjoint Bogoliubov diagrams are found.  

In [275]:
AdcbaVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcbaVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcbaVertex[[1]] = AdisjBogoAntidiag[[1]];
MultdcbaVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoAntidiag[[u, i, j]];
   If[AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoAntidiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjBogoAntidiag[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjBogoAntidiag[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjBogoAntidiag[[u, i, j]] >= 3 && 
       AdisjBogoAntidiag[[u, i, j]] <= 4) || 
     AdisjBogoAntidiag[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjBogoAntidiag[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjBogoAntidiag[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjBogoAntidiag[[u, i, j]] <= 2 || 
     AdisjBogoAntidiag[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjBogoAntidiag[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjBogoAntidiag[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjBogoAntidiag[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjBogoAntidiag[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjBogoAntidiag[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjBogoAntidiag[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbaVertex[[v]] = MultdcbaVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; 
   AdcbaVertex[[s]] = AdisjBogoAntidiag[[u]]; MultdcbaVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent antidiagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 48 completed and 8 inequivalent antidiagonally-dressed Bogoliubov\
 
>    contributions found.


In [273]:
For[u = 1, u <= 8, u++, Print["CombBogAntidiag[[", u, "]]=", AdcbaVertex[[u]], ";"]];

CombBogAntidiag[[1]]={{1, 3}, {2, 5}, {4, 9}, {7, 8}, {6, 10}};
CombBogAntidiag[[2]]={{1, 3}, {2, 5}, {4, 10}, {7, 8}, {6, 9}};
CombBogAntidiag[[3]]={{1, 3}, {2, 6}, {5, 9}, {7, 8}, {4, 10}};
CombBogAntidiag[[4]]={{1, 3}, {2, 6}, {5, 10}, {7, 8}, {4, 9}};
CombBogAntidiag[[5]]={{1, 4}, {3, 6}, {5, 9}, {7, 8}, {2, 10}};
CombBogAntidiag[[6]]={{1, 4}, {3, 6}, {5, 10}, {7, 8}, {2, 9}};
CombBogAntidiag[[7]]={{1, 4}, {3, 9}, {5, 10}, {7, 8}, {2, 6}};
CombBogAntidiag[[8]]={{1, 4}, {3, 10}, {5, 9}, {7, 8}, {2, 6}};


In [274]:
For[u = 1, u <= 8, u++, Print["GGFMult[[", u, "]]=", MultdcbaVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order antidiagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [284]:
Sum[MultdcbaVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint Bogoliubov diagrams with dressed single-particle propagator on the diagonal</font>

Bogoliubov diagrams with unperturbed 1-body propagator on the antidiagonal are processed. Their initial number is $8$ in total.

### <font color=#E9967A>Diagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent diagonally-dressed disjoint Bogoliubov contributions with non-identical vertices at third order remains equal to $48$.

In [285]:
For[u = 1, u <= 48, u++, Print["CombBogDiag[[", u, "]]=", AdisjBogoDiag[[u]], ";"]];

CombBogDiag[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 8}, {9, 10}};
CombBogDiag[[2]]={{1, 3}, {2, 5}, {4, 8}, {6, 7}, {9, 10}};
CombBogDiag[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 8}, {9, 10}};
CombBogDiag[[4]]={{1, 3}, {2, 6}, {5, 8}, {4, 7}, {9, 10}};
CombBogDiag[[5]]={{1, 3}, {2, 7}, {4, 5}, {6, 8}, {9, 10}};
CombBogDiag[[6]]={{1, 3}, {2, 7}, {5, 8}, {4, 6}, {9, 10}};
CombBogDiag[[7]]={{1, 3}, {2, 8}, {5, 7}, {4, 6}, {9, 10}};
CombBogDiag[[8]]={{1, 3}, {2, 8}, {4, 5}, {6, 7}, {9, 10}};
CombBogDiag[[9]]={{1, 4}, {3, 5}, {2, 7}, {6, 8}, {9, 10}};
CombBogDiag[[10]]={{1, 4}, {3, 5}, {2, 8}, {6, 7}, {9, 10}};
CombBogDiag[[11]]={{1, 4}, {3, 6}, {5, 7}, {2, 8}, {9, 10}};
CombBogDiag[[12]]={{1, 4}, {3, 6}, {5, 8}, {2, 7}, {9, 10}};
CombBogDiag[[13]]={{1, 4}, {3, 7}, {2, 5}, {6, 8}, {9, 10}};
CombBogDiag[[14]]={{1, 4}, {3, 7}, {5, 8}, {2, 6}, {9, 10}};
CombBogDiag[[15]]={{1, 4}, {3, 8}, {5, 7}, {2, 6}, {9, 10}};
CombBogDiag[[16]]={{1, 4}, {3, 8}, {2, 5}, {6, 7}, {9, 10}};
CombBogDiag[[17]]={{1, 5}, {2, 3}

In [286]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;


There are only $48$ third-order diagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices. The multiplicity check is fulfilled.

### <font color=#E9967A>Diagonally-dressed disjoint Bogoliubov diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $24$ inequivalent fully-contracted terms corresponding to diagonally-dressed disjoint Bogoliubov diagrams are found.    

In [296]:
AdcbdVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcbdVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcbdVertex[[1]] = AdisjBogoDiag[[1]];
MultdcbdVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoDiag[[u, i, j]];
   If[AdisjBogoDiag[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoDiag[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoDiag[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoDiag[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoDiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoDiag[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbdVertex[[v]] = MultdcbdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcbdVertex[[s]] = AdisjBogoDiag[[u]]; 
   MultdcbdVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 48 completed and 24 inequivalent diagonally-dressed Bogoliubov\
 
>    contributions found.


In [305]:
For[u = 1, u <= 24, u++, Print["CombBogDiag[[", u, "]]=", AdcbdVertex[[u]], ";"]];

CombBogDiag[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 8}, {9, 10}};
CombBogDiag[[2]]={{1, 3}, {2, 5}, {4, 8}, {6, 7}, {9, 10}};
CombBogDiag[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 8}, {9, 10}};
CombBogDiag[[4]]={{1, 3}, {2, 6}, {5, 8}, {4, 7}, {9, 10}};
CombBogDiag[[5]]={{1, 4}, {3, 5}, {2, 7}, {6, 8}, {9, 10}};
CombBogDiag[[6]]={{1, 4}, {3, 5}, {2, 8}, {6, 7}, {9, 10}};
CombBogDiag[[7]]={{1, 4}, {3, 6}, {5, 7}, {2, 8}, {9, 10}};
CombBogDiag[[8]]={{1, 4}, {3, 6}, {5, 8}, {2, 7}, {9, 10}};
CombBogDiag[[9]]={{1, 4}, {3, 7}, {2, 5}, {6, 8}, {9, 10}};
CombBogDiag[[10]]={{1, 4}, {3, 7}, {5, 8}, {2, 6}, {9, 10}};
CombBogDiag[[11]]={{1, 4}, {3, 8}, {5, 7}, {2, 6}, {9, 10}};
CombBogDiag[[12]]={{1, 4}, {3, 8}, {2, 5}, {6, 7}, {9, 10}};
CombBogDiag[[13]]={{1, 5}, {3, 6}, {2, 7}, {4, 8}, {9, 10}};
CombBogDiag[[14]]={{1, 5}, {3, 6}, {2, 8}, {4, 7}, {9, 10}};
CombBogDiag[[15]]={{1, 5}, {3, 7}, {2, 4}, {6, 8}, {9, 10}};
CombBogDiag[[16]]={{1, 5}, {3, 7}, {2, 8}, {4, 6}, {9, 10}};
CombBogDiag[[17]]={{1, 5}, {3, 8}

In [306]:
For[u = 1, u <= 24, u++, Print["GGFMult[[", u, "]]=", MultdcbdVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;


There are only $24$ inequivalent third-order diagonally-dressed disjoint Bogoliubov diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [307]:
Sum[MultdcbdVertex[[u]], {u, 1, 24}]

48

### <font color=#E9967A>Diagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by 5. In the end of the process, 8 inequivalent fully-contracted terms corresponding to diagonally-dressed disjoint Bogoliubov diagrams are found.  

In [317]:
AdcbdVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcbdVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcbdVertex[[1]] = AdisjBogoDiag[[1]];
MultdcbdVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoDiag[[u, i, j]];
   If[AdisjBogoDiag[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoDiag[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoDiag[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoDiag[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoDiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[AdisjBogoDiag[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjBogoDiag[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjBogoDiag[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjBogoDiag[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjBogoDiag[[u, i, j]] >= 3 && 
       AdisjBogoDiag[[u, i, j]] <= 4) || 
     AdisjBogoDiag[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[AdisjBogoDiag[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjBogoDiag[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjBogoDiag[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjBogoDiag[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjBogoDiag[[u, i, j]] <= 2 || AdisjBogoDiag[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[AdisjBogoDiag[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjBogoDiag[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjBogoDiag[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjBogoDiag[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjBogoDiag[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjBogoDiag[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjBogoDiag[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[AdisjBogoDiag[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjBogoDiag[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjBogoDiag[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjBogoDiag[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjBogoDiag[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjBogoDiag[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjBogoDiag[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjBogoDiag[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbdVertex[[v]] = MultdcbdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcbdVertex[[s]] = AdisjBogoDiag[[u]]; 
   MultdcbdVertex[[v]] = 1];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 48 completed and 8 inequivalent diagonally-dressed Bogoliubov\
 
>    contributions found.


In [326]:
For[u = 1, u <= 8, u++, Print["CombBogDiag[[", u, "]]=", AdcbdVertex[[u]], ";"]];

CombBogDiag[[1]]={{1, 3}, {2, 5}, {4, 7}, {6, 8}, {9, 10}};
CombBogDiag[[2]]={{1, 3}, {2, 5}, {4, 8}, {6, 7}, {9, 10}};
CombBogDiag[[3]]={{1, 3}, {2, 6}, {5, 7}, {4, 8}, {9, 10}};
CombBogDiag[[4]]={{1, 3}, {2, 6}, {5, 8}, {4, 7}, {9, 10}};
CombBogDiag[[5]]={{1, 4}, {3, 6}, {5, 7}, {2, 8}, {9, 10}};
CombBogDiag[[6]]={{1, 4}, {3, 6}, {5, 8}, {2, 7}, {9, 10}};
CombBogDiag[[7]]={{1, 4}, {3, 7}, {5, 8}, {2, 6}, {9, 10}};
CombBogDiag[[8]]={{1, 4}, {3, 8}, {5, 7}, {2, 6}, {9, 10}};


In [327]:
For[u = 1, u <= 8, u++, Print["GGFMult[[", u, "]]=", MultdcbdVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;


There are only $8$ inequivalent third-order diagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [328]:
Sum[MultdcbdVertex[[u]], {u, 1, 8}]

48

## <font color=#FA8072>Disjoint Bogoliubov diagrams with dressed single-particle propagators on the diagonal and the antidiagonal</font>

Bogoliubov diagrams with perturbed 1-body propagators on the diagonal and antidiagonal are processed. Their initial number is $96$ in total.

### <font color=#E9967A>Diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent diagonally-and-antidiagonally-dressed disjoint Bogoliubov contributions with non-identical vertices at third order remains equal to $96$.

In [329]:
For[u = 1, u <= 96, u++, Print["CombBog[[", u, "]]=", AdisjBogoliubov[[u]], ";"]];

CombBog[[1]]={{1, 3}, {2, 7}, {5, 9}, {4, 8}, {6, 10}};
CombBog[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 8}, {6, 9}};
CombBog[[3]]={{1, 3}, {2, 8}, {5, 9}, {4, 7}, {6, 10}};
CombBog[[4]]={{1, 3}, {2, 8}, {5, 10}, {4, 7}, {6, 9}};
CombBog[[5]]={{1, 3}, {2, 9}, {5, 7}, {6, 8}, {4, 10}};
CombBog[[6]]={{1, 3}, {2, 9}, {5, 8}, {6, 7}, {4, 10}};
CombBog[[7]]={{1, 3}, {2, 10}, {5, 7}, {6, 8}, {4, 9}};
CombBog[[8]]={{1, 3}, {2, 10}, {5, 8}, {6, 7}, {4, 9}};
CombBog[[9]]={{1, 4}, {3, 7}, {5, 9}, {2, 8}, {6, 10}};
CombBog[[10]]={{1, 4}, {3, 7}, {5, 10}, {2, 8}, {6, 9}};
CombBog[[11]]={{1, 4}, {3, 8}, {5, 9}, {2, 7}, {6, 10}};
CombBog[[12]]={{1, 4}, {3, 8}, {5, 10}, {2, 7}, {6, 9}};
CombBog[[13]]={{1, 4}, {3, 9}, {5, 7}, {6, 8}, {2, 10}};
CombBog[[14]]={{1, 4}, {3, 9}, {5, 8}, {6, 7}, {2, 10}};
CombBog[[15]]={{1, 4}, {3, 10}, {5, 7}, {6, 8}, {2, 9}};
CombBog[[16]]={{1, 4}, {3, 10}, {5, 8}, {6, 7}, {2, 9}};
CombBog[[17]]={{1, 5}, {3, 7}, {2, 9}, {4, 8}, {6, 10}};
CombBog[[18]]={{1, 5}, {3, 7}, {2, 10}, 

In [330]:
For[u = 1, u <= 96, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;
GGFMult[[49]]=1;
GGFMult[[50]]=1;
GGFMult[[51]]=1;
GGFMult[[52]]=1;
GGFMult[[53]]=1;
GGFMult[[54]]=1;
GGFMult[[55]]=1;
GGFMult[[56]]=1;
GGFMult[[57]]=1;
GGFMult[[58]]=1;
GGFMult[[59]]=1;
GGFMul

There are only $96$ third-order diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with non-identical one-body vertices. The multiplicity check is fulfilled.

### <font color=#E9967A>Diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $48$ inequivalent fully-contracted terms corresponding to diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams are found.    

In [340]:
AdcbVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdcbVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdcbVertex[[1]] = AdisjBogoliubov[[1]];
MultdcbVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoliubov[[u, i, j]];
   If[AdisjBogoliubov[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoliubov[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoliubov[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoliubov[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoliubov[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoliubov[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbVertex[[v]] = MultdcbVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcbVertex[[s]] = AdisjBogoliubov[[u]]; 
   MultdcbVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-and-antidiagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 96 completed and 48 inequivalent diagonally-and-antidiagonally-dressed\
 
>    Bogoliubov contributions found.


In [349]:
For[u = 1, u <= 48, u++, 
  Print["CombBog[[", u, "]]=", AdcbVertex[[u]], ";"]];

CombBog[[1]]={{1, 3}, {2, 7}, {5, 9}, {4, 8}, {6, 10}};
CombBog[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 8}, {6, 9}};
CombBog[[3]]={{1, 3}, {2, 9}, {5, 7}, {6, 8}, {4, 10}};
CombBog[[4]]={{1, 3}, {2, 9}, {5, 8}, {6, 7}, {4, 10}};
CombBog[[5]]={{1, 4}, {3, 7}, {5, 9}, {2, 8}, {6, 10}};
CombBog[[6]]={{1, 4}, {3, 7}, {5, 10}, {2, 8}, {6, 9}};
CombBog[[7]]={{1, 4}, {3, 8}, {5, 9}, {2, 7}, {6, 10}};
CombBog[[8]]={{1, 4}, {3, 8}, {5, 10}, {2, 7}, {6, 9}};
CombBog[[9]]={{1, 4}, {3, 9}, {5, 7}, {6, 8}, {2, 10}};
CombBog[[10]]={{1, 4}, {3, 9}, {5, 8}, {6, 7}, {2, 10}};
CombBog[[11]]={{1, 4}, {3, 10}, {5, 7}, {6, 8}, {2, 9}};
CombBog[[12]]={{1, 4}, {3, 10}, {5, 8}, {6, 7}, {2, 9}};
CombBog[[13]]={{1, 5}, {3, 7}, {2, 9}, {4, 8}, {6, 10}};
CombBog[[14]]={{1, 5}, {3, 7}, {2, 10}, {4, 8}, {6, 9}};
CombBog[[15]]={{1, 5}, {3, 8}, {2, 9}, {4, 7}, {6, 10}};
CombBog[[16]]={{1, 5}, {3, 8}, {2, 10}, {4, 7}, {6, 9}};
CombBog[[17]]={{1, 5}, {3, 9}, {2, 7}, {6, 8}, {4, 10}};
CombBog[[18]]={{1, 5}, {3, 9}, {2, 8}, {

In [350]:
For[u = 1, u <= 48, u++, 
  Print["GGFMult[[", u, "]]=", MultdcbVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=2;
GGFMult[[6]]=2;
GGFMult[[7]]=2;
GGFMult[[8]]=2;
GGFMult[[9]]=2;
GGFMult[[10]]=2;
GGFMult[[11]]=2;
GGFMult[[12]]=2;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;
GGFMult[[25]]=2;
GGFMult[[26]]=2;
GGFMult[[27]]=2;
GGFMult[[28]]=2;
GGFMult[[29]]=2;
GGFMult[[30]]=2;
GGFMult[[31]]=2;
GGFMult[[32]]=2;
GGFMult[[33]]=2;
GGFMult[[34]]=2;
GGFMult[[35]]=2;
GGFMult[[36]]=2;
GGFMult[[37]]=2;
GGFMult[[38]]=2;
GGFMult[[39]]=2;
GGFMult[[40]]=2;
GGFMult[[41]]=2;
GGFMult[[42]]=2;
GGFMult[[43]]=2;
GGFMult[[44]]=2;
GGFMult[[45]]=2;
GGFMult[[46]]=2;
GGFMult[[47]]=2;
GGFMult[[48]]=2;


There are only $48$ inequivalent third-order diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with identical one-body vertices. The multiplicity check is fulfilled.

In [351]:
Sum[MultdcbdVertex[[u]], {u, 1, 48}]

48

### <font color=#E9967A>Diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$. In the end of the process, $16$ inequivalent fully-contracted terms corresponding to diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams are found.  

In [361]:
AdcbVertex = Table[0, {i, 1, 96}, {j, 1, 5}, {k, 1, 2}];
MultdcbVertex = Table[0, {i, 1, 96}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdcbVertex[[1]] = AdisjBogoliubov[[1]];
MultdcbVertex[[1]] = 1;
For[u = 1, u <= 96, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = AdisjBogoliubov[[u, i, j]];
   If[AdisjBogoliubov[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[AdisjBogoliubov[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[AdisjBogoliubov[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[AdisjBogoliubov[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[AdisjBogoliubov[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[AdisjBogoliubov[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[AdisjBogoliubov[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[AdisjBogoliubov[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[AdisjBogoliubov[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(AdisjBogoliubov[[u, i, j]] >= 3 && 
       AdisjBogoliubov[[u, i, j]] <= 4) || 
     AdisjBogoliubov[[u, i, j]] >= 7, 
    Temp[[3, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[AdisjBogoliubov[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[AdisjBogoliubov[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[AdisjBogoliubov[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[AdisjBogoliubov[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[AdisjBogoliubov[[u, i, j]] <= 2 || 
     AdisjBogoliubov[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[AdisjBogoliubov[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[AdisjBogoliubov[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[AdisjBogoliubov[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[AdisjBogoliubov[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[AdisjBogoliubov[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[AdisjBogoliubov[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[AdisjBogoliubov[[u, i, j]] >= 7, 
    Temp[[5, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[AdisjBogoliubov[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[AdisjBogoliubov[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[AdisjBogoliubov[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[AdisjBogoliubov[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[AdisjBogoliubov[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[AdisjBogoliubov[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[AdisjBogoliubov[[u, i, j]] >= 7, 
    Temp[[6, i, j]] = AdisjBogoliubov[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbVertex[[v]] = MultdcbVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdcbVertex[[s]] = AdisjBogoliubov[[u]]; 
   MultdcbVertex[[v]] = 1];
  ];
 If[u == 96, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-and-antidiagonally-dressed Bogoliubov contributions found."]];
 ]

Loop 96 completed and 16 inequivalent diagonally-and-antidiagonally-dressed\
 
>    Bogoliubov contributions found.


In [370]:
For[u = 1, u <= 16, u++, Print["CombBog[[", u, "]]=", AdcbVertex[[u]], ";"]];

CombBog[[1]]={{1, 3}, {2, 7}, {5, 9}, {4, 8}, {6, 10}};
CombBog[[2]]={{1, 3}, {2, 7}, {5, 10}, {4, 8}, {6, 9}};
CombBog[[3]]={{1, 3}, {2, 9}, {5, 7}, {6, 8}, {4, 10}};
CombBog[[4]]={{1, 3}, {2, 9}, {5, 8}, {6, 7}, {4, 10}};
CombBog[[5]]={{1, 4}, {3, 7}, {5, 9}, {2, 8}, {6, 10}};
CombBog[[6]]={{1, 4}, {3, 7}, {5, 10}, {2, 8}, {6, 9}};
CombBog[[7]]={{1, 4}, {3, 8}, {5, 9}, {2, 7}, {6, 10}};
CombBog[[8]]={{1, 4}, {3, 8}, {5, 10}, {2, 7}, {6, 9}};
CombBog[[9]]={{1, 4}, {3, 9}, {5, 7}, {6, 8}, {2, 10}};
CombBog[[10]]={{1, 4}, {3, 9}, {5, 8}, {6, 7}, {2, 10}};
CombBog[[11]]={{1, 4}, {3, 10}, {5, 7}, {6, 8}, {2, 9}};
CombBog[[12]]={{1, 4}, {3, 10}, {5, 8}, {6, 7}, {2, 9}};
CombBog[[13]]={{1, 7}, {3, 8}, {5, 9}, {2, 4}, {6, 10}};
CombBog[[14]]={{1, 7}, {3, 8}, {5, 10}, {2, 4}, {6, 9}};
CombBog[[15]]={{1, 7}, {3, 9}, {5, 10}, {2, 8}, {4, 6}};
CombBog[[16]]={{1, 8}, {3, 9}, {5, 10}, {2, 7}, {4, 6}};


In [371]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdcbVertex[[u]], ";"]];

GGFMult[[1]]=6;
GGFMult[[2]]=6;
GGFMult[[3]]=6;
GGFMult[[4]]=6;
GGFMult[[5]]=6;
GGFMult[[6]]=6;
GGFMult[[7]]=6;
GGFMult[[8]]=6;
GGFMult[[9]]=6;
GGFMult[[10]]=6;
GGFMult[[11]]=6;
GGFMult[[12]]=6;
GGFMult[[13]]=6;
GGFMult[[14]]=6;
GGFMult[[15]]=6;
GGFMult[[16]]=6;


There are only $16$ inequivalent third-order diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [372]:
Sum[MultdcbVertex[[u]], {u, 1, 16}]

96

# <font color=#71797E>Disconnected Diagrams</font>

Third-order disconnected diagrams are $369$ in total. The filtration process is necessary.

In [373]:
Adisc = Table[0, {i, 1, 945}, {j, 1, 5}, {k, 1, 2}];
l = 1;
For[i = 1, i <= 945, i++, 
 SelfBinding12 = False;
 SelfBinding34 = False;
 SelfBinding56 = False;
 Bridge13 = False;
 Bridge14 = False;
 Bridge15 = False;
 Bridge16 = False;
 Bridge23 = False;
 Bridge24 = False;
 Bridge25 = False;
 Bridge26 = False;
 Bridge35 = False;
 Bridge36 = False;
 Bridge45 = False;
 Bridge46 = False;
 For[j = 1, j <= 5, j++,
  If[Acombsort[[i, j]] == {1, 3}  , Bridge13 = True];
  If[Acombsort[[i, j]] == {1, 4}  , Bridge14 = True];
  If[Acombsort[[i, j]] == {1, 5}  , Bridge15 = True];
  If[Acombsort[[i, j]] == {1, 6}  , Bridge16 = True];
  If[Acombsort[[i, j]] == {2, 3}  , Bridge23 = True];
  If[Acombsort[[i, j]] == {2, 4}  , Bridge24 = True];
  If[Acombsort[[i, j]] == {2, 5}  , Bridge25 = True];
  If[Acombsort[[i, j]] == {2, 6}  , Bridge26 = True];
  If[Acombsort[[i, j]] == {3, 5}  , Bridge35 = True];
  If[Acombsort[[i, j]] == {3, 6}  , Bridge36 = True];
  If[Acombsort[[i, j]] == {4, 5}  , Bridge45 = True];
  If[Acombsort[[i, j]] == {4, 6}  , Bridge46 = True];
  If[Acombsort[[i, j]] == {1, 2}  , SelfBinding12 = True];
  If[Acombsort[[i, j]] == {3, 4}  , SelfBinding34 = True];
  If[Acombsort[[i, j]] == {5, 6}  , SelfBinding56 = True];
  ];
 If[SelfBinding12 == True || SelfBinding34 == True || 
   SelfBinding56 == True, Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge13 == True && Bridge24 == True && SelfBinding56 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge23 == True && Bridge14 == True && SelfBinding56 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge15 == True && Bridge26 == True && SelfBinding34 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge25 == True && Bridge16 == True && SelfBinding34 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge35 == True && Bridge46 == True && SelfBinding12 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge36 == True && Bridge45 == True && SelfBinding12 == False, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge13 == True && Bridge25 == True && Bridge46 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge13 == True && Bridge26 == True && Bridge45 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge14 == True && Bridge25 == True && Bridge36 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge14 == True && Bridge26 == True && Bridge35 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge15 == True && Bridge23 == True && Bridge46 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge15 == True && Bridge24 == True && Bridge36 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge16 == True && Bridge23 == True && Bridge45 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[Bridge16 == True && Bridge24 == True && Bridge35 == True, 
  Adisc[[l]] = Acombsort[[i]]; l++];
 If[i == 945, 
  Print["Loop ", i, " completed and ", l - 1, 
   " disconnected contributions found."] ];]

Loop 945 completed and 369 disconnected contributions found.


Total number of disconnected diagrams:

In [2]:
945 - 576

369

### <font color=#E9967A>Disconnected diagrams with non-identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are distinct, no vertex exchange is possible. Additionally, since single-particle index transpositions within each one-body vertex are forbidden, no filtration process is necessary. Thus, the number of inequivalent disconnected contributions with non-identical vertices at third order remains equal to $369$.

In [376]:
For[u = 1, u <= 369, u++, Print["CombDisc[[", u, "]]=", Adisc[[u]], ";"]];

CombDisc[[1]]={{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}};
CombDisc[[2]]={{1, 2}, {3, 4}, {5, 6}, {7, 9}, {8, 10}};
CombDisc[[3]]={{1, 2}, {3, 4}, {5, 6}, {7, 10}, {8, 9}};
CombDisc[[4]]={{1, 2}, {3, 4}, {5, 7}, {6, 8}, {9, 10}};
CombDisc[[5]]={{1, 2}, {3, 4}, {5, 7}, {6, 9}, {8, 10}};
CombDisc[[6]]={{1, 2}, {3, 4}, {5, 7}, {6, 10}, {8, 9}};
CombDisc[[7]]={{1, 2}, {3, 4}, {5, 8}, {6, 7}, {9, 10}};
CombDisc[[8]]={{1, 2}, {3, 4}, {5, 8}, {7, 9}, {6, 10}};
CombDisc[[9]]={{1, 2}, {3, 4}, {5, 8}, {7, 10}, {6, 9}};
CombDisc[[10]]={{1, 2}, {3, 4}, {5, 9}, {7, 8}, {6, 10}};
CombDisc[[11]]={{1, 2}, {3, 4}, {5, 9}, {6, 7}, {8, 10}};
CombDisc[[12]]={{1, 2}, {3, 4}, {5, 9}, {7, 10}, {6, 8}};
CombDisc[[13]]={{1, 2}, {3, 4}, {5, 10}, {7, 8}, {6, 9}};
CombDisc[[14]]={{1, 2}, {3, 4}, {5, 10}, {7, 9}, {6, 8}};
CombDisc[[15]]={{1, 2}, {3, 4}, {5, 10}, {6, 7}, {8, 9}};
CombDisc[[16]]={{1, 2}, {3, 5}, {4, 6}, {7, 8}, {9, 10}};
CombDisc[[17]]={{1, 2}, {3, 5}, {4, 6}, {7, 9}, {8, 10}};
CombDisc[[18]]={{1, 2},

CombDisc[[142]]={{1, 4}, {2, 3}, {5, 7}, {6, 8}, {9, 10}};
CombDisc[[143]]={{1, 4}, {2, 3}, {5, 7}, {6, 9}, {8, 10}};
CombDisc[[144]]={{1, 4}, {2, 3}, {5, 7}, {6, 10}, {8, 9}};
CombDisc[[145]]={{1, 4}, {2, 3}, {5, 8}, {6, 7}, {9, 10}};
CombDisc[[146]]={{1, 4}, {2, 3}, {5, 8}, {7, 9}, {6, 10}};
CombDisc[[147]]={{1, 4}, {2, 3}, {5, 8}, {7, 10}, {6, 9}};
CombDisc[[148]]={{1, 4}, {2, 3}, {5, 9}, {7, 8}, {6, 10}};
CombDisc[[149]]={{1, 4}, {2, 3}, {5, 9}, {6, 7}, {8, 10}};
CombDisc[[150]]={{1, 4}, {2, 3}, {5, 9}, {7, 10}, {6, 8}};
CombDisc[[151]]={{1, 4}, {2, 3}, {5, 10}, {7, 8}, {6, 9}};
CombDisc[[152]]={{1, 4}, {2, 3}, {5, 10}, {7, 9}, {6, 8}};
CombDisc[[153]]={{1, 4}, {2, 3}, {5, 10}, {6, 7}, {8, 9}};
CombDisc[[154]]={{1, 4}, {3, 5}, {2, 6}, {7, 8}, {9, 10}};
CombDisc[[155]]={{1, 4}, {3, 5}, {2, 6}, {7, 9}, {8, 10}};
CombDisc[[156]]={{1, 4}, {3, 5}, {2, 6}, {7, 10}, {8, 9}};
CombDisc[[157]]={{1, 4}, {3, 6}, {2, 5}, {7, 8}, {9, 10}};
CombDisc[[158]]={{1, 4}, {3, 6}, {2, 5}, {7, 9}, {8, 10}

CombDisc[[281]]={{1, 8}, {3, 4}, {5, 9}, {6, 7}, {2, 10}};
CombDisc[[282]]={{1, 8}, {3, 4}, {5, 9}, {7, 10}, {2, 6}};
CombDisc[[283]]={{1, 8}, {3, 4}, {5, 10}, {2, 7}, {6, 9}};
CombDisc[[284]]={{1, 8}, {3, 4}, {5, 10}, {7, 9}, {2, 6}};
CombDisc[[285]]={{1, 8}, {3, 4}, {5, 10}, {6, 7}, {2, 9}};
CombDisc[[286]]={{1, 8}, {3, 5}, {4, 6}, {2, 7}, {9, 10}};
CombDisc[[287]]={{1, 8}, {3, 5}, {4, 6}, {7, 9}, {2, 10}};
CombDisc[[288]]={{1, 8}, {3, 5}, {4, 6}, {7, 10}, {2, 9}};
CombDisc[[289]]={{1, 8}, {3, 6}, {4, 5}, {2, 7}, {9, 10}};
CombDisc[[290]]={{1, 8}, {3, 6}, {4, 5}, {7, 9}, {2, 10}};
CombDisc[[291]]={{1, 8}, {3, 6}, {4, 5}, {7, 10}, {2, 9}};
CombDisc[[292]]={{1, 8}, {3, 7}, {5, 6}, {2, 4}, {9, 10}};
CombDisc[[293]]={{1, 8}, {3, 7}, {5, 6}, {4, 9}, {2, 10}};
CombDisc[[294]]={{1, 8}, {3, 7}, {5, 6}, {4, 10}, {2, 9}};
CombDisc[[295]]={{1, 8}, {2, 3}, {5, 6}, {4, 7}, {9, 10}};
CombDisc[[296]]={{1, 8}, {2, 3}, {5, 6}, {7, 9}, {4, 10}};
CombDisc[[297]]={{1, 8}, {2, 3}, {5, 6}, {7, 10}, {4, 9}

In [377]:
For[u = 1, u <= 369, u++, Print["GGFMult[[", u, "]]=", 1, ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=1;
GGFMult[[17]]=1;
GGFMult[[18]]=1;
GGFMult[[19]]=1;
GGFMult[[20]]=1;
GGFMult[[21]]=1;
GGFMult[[22]]=1;
GGFMult[[23]]=1;
GGFMult[[24]]=1;
GGFMult[[25]]=1;
GGFMult[[26]]=1;
GGFMult[[27]]=1;
GGFMult[[28]]=1;
GGFMult[[29]]=1;
GGFMult[[30]]=1;
GGFMult[[31]]=1;
GGFMult[[32]]=1;
GGFMult[[33]]=1;
GGFMult[[34]]=1;
GGFMult[[35]]=1;
GGFMult[[36]]=1;
GGFMult[[37]]=1;
GGFMult[[38]]=1;
GGFMult[[39]]=1;
GGFMult[[40]]=1;
GGFMult[[41]]=1;
GGFMult[[42]]=1;
GGFMult[[43]]=1;
GGFMult[[44]]=1;
GGFMult[[45]]=1;
GGFMult[[46]]=1;
GGFMult[[47]]=1;
GGFMult[[48]]=1;
GGFMult[[49]]=1;
GGFMult[[50]]=1;
GGFMult[[51]]=1;
GGFMult[[52]]=1;
GGFMult[[53]]=1;
GGFMult[[54]]=1;
GGFMult[[55]]=1;
GGFMult[[56]]=1;
GGFMult[[57]]=1;
GGFMult[[58]]=1;
GGFMult[[59]]=1;
GGFMul

There are only $369$ third-order disconnected diagrams with non-identical one-body vertex. The multiplicity check is fulfilled by construction.

### <font color=#E9967A>Disconnected diagrams with two identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. Without loss of generality, let us assume that fully contracted terms which are mapped one another by the single-particle-index transposition $e \mapsto g \wedge f \mapsto h$ are equivalent, thus one of the two can be dropped, incrementing the associated multiplicity by unity. In the end of the process, $207$ inequivalent fully-contracted terms corresponding to disconnected diagrams are found.     

In [378]:
AdVertex = Table[0, {i, 1, 369}, {j, 1, 5}, {k, 1, 2}];
MultdVertex = Table[0, {i, 1, 369}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 2}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 2}, {k, 1, 5}];

s = 1;
AdVertex[[1]] = Adisc[[1]];
MultdVertex[[1]] = 1;
For[u = 1, u <= 369, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = Adisc[[u, i, j]];
   If[Adisc[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[Adisc[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[Adisc[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[Adisc[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[Adisc[[u, i, j]] >= 5, Temp[[2, i, j]] = Adisc[[u, i, j]]];
   ]];
 For[i = 1, i <= 2, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 2, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 2, j++,
      For[k = 1, k <= 5, k++,
        If[AdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdVertex[[v]] = MultdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdVertex[[s]] = Adisc[[u]]; 
   MultdVertex[[v]] = 1];
  ];
 If[u == 369, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent disconnected contributions found."]];
 ]

Loop 369 completed and 207 inequivalent disconnected contributions found.


In [387]:
For[u = 1, u <= 207, u++, Print["CombDisc[[", u, "]]=", AdVertex[[u]], ";"]];

CombDisc[[1]]={{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}};
CombDisc[[2]]={{1, 2}, {3, 4}, {5, 6}, {7, 9}, {8, 10}};
CombDisc[[3]]={{1, 2}, {3, 4}, {5, 6}, {7, 10}, {8, 9}};
CombDisc[[4]]={{1, 2}, {3, 4}, {5, 7}, {6, 8}, {9, 10}};
CombDisc[[5]]={{1, 2}, {3, 4}, {5, 7}, {6, 9}, {8, 10}};
CombDisc[[6]]={{1, 2}, {3, 4}, {5, 7}, {6, 10}, {8, 9}};
CombDisc[[7]]={{1, 2}, {3, 4}, {5, 8}, {6, 7}, {9, 10}};
CombDisc[[8]]={{1, 2}, {3, 4}, {5, 8}, {7, 9}, {6, 10}};
CombDisc[[9]]={{1, 2}, {3, 4}, {5, 8}, {7, 10}, {6, 9}};
CombDisc[[10]]={{1, 2}, {3, 4}, {5, 9}, {7, 8}, {6, 10}};
CombDisc[[11]]={{1, 2}, {3, 4}, {5, 9}, {6, 7}, {8, 10}};
CombDisc[[12]]={{1, 2}, {3, 4}, {5, 9}, {7, 10}, {6, 8}};
CombDisc[[13]]={{1, 2}, {3, 4}, {5, 10}, {7, 8}, {6, 9}};
CombDisc[[14]]={{1, 2}, {3, 4}, {5, 10}, {7, 9}, {6, 8}};
CombDisc[[15]]={{1, 2}, {3, 4}, {5, 10}, {6, 7}, {8, 9}};
CombDisc[[16]]={{1, 2}, {3, 5}, {4, 6}, {7, 8}, {9, 10}};
CombDisc[[17]]={{1, 2}, {3, 5}, {4, 6}, {7, 9}, {8, 10}};
CombDisc[[18]]={{1, 2},

CombDisc[[142]]={{1, 4}, {2, 3}, {5, 10}, {7, 8}, {6, 9}};
CombDisc[[143]]={{1, 4}, {2, 3}, {5, 10}, {7, 9}, {6, 8}};
CombDisc[[144]]={{1, 4}, {2, 3}, {5, 10}, {6, 7}, {8, 9}};
CombDisc[[145]]={{1, 4}, {3, 5}, {2, 6}, {7, 8}, {9, 10}};
CombDisc[[146]]={{1, 4}, {3, 5}, {2, 6}, {7, 9}, {8, 10}};
CombDisc[[147]]={{1, 4}, {3, 5}, {2, 6}, {7, 10}, {8, 9}};
CombDisc[[148]]={{1, 4}, {3, 6}, {2, 5}, {7, 8}, {9, 10}};
CombDisc[[149]]={{1, 4}, {3, 6}, {2, 5}, {7, 9}, {8, 10}};
CombDisc[[150]]={{1, 4}, {3, 6}, {2, 5}, {7, 10}, {8, 9}};
CombDisc[[151]]={{1, 4}, {3, 7}, {5, 6}, {2, 8}, {9, 10}};
CombDisc[[152]]={{1, 4}, {3, 7}, {5, 6}, {2, 9}, {8, 10}};
CombDisc[[153]]={{1, 4}, {3, 7}, {5, 6}, {2, 10}, {8, 9}};
CombDisc[[154]]={{1, 4}, {3, 8}, {5, 6}, {2, 7}, {9, 10}};
CombDisc[[155]]={{1, 4}, {3, 8}, {5, 6}, {7, 9}, {2, 10}};
CombDisc[[156]]={{1, 4}, {3, 8}, {5, 6}, {7, 10}, {2, 9}};
CombDisc[[157]]={{1, 4}, {3, 9}, {5, 6}, {7, 8}, {2, 10}};
CombDisc[[158]]={{1, 4}, {3, 9}, {5, 6}, {2, 7}, {8, 10}

In [388]:
For[u = 1, u <= 207, u++, Print["GGFMult[[", u, "]]=", MultdVertex[[u]], ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=1;
GGFMult[[5]]=1;
GGFMult[[6]]=1;
GGFMult[[7]]=1;
GGFMult[[8]]=1;
GGFMult[[9]]=1;
GGFMult[[10]]=1;
GGFMult[[11]]=1;
GGFMult[[12]]=1;
GGFMult[[13]]=1;
GGFMult[[14]]=1;
GGFMult[[15]]=1;
GGFMult[[16]]=2;
GGFMult[[17]]=2;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=2;
GGFMult[[21]]=2;
GGFMult[[22]]=2;
GGFMult[[23]]=2;
GGFMult[[24]]=2;
GGFMult[[25]]=2;
GGFMult[[26]]=2;
GGFMult[[27]]=2;
GGFMult[[28]]=2;
GGFMult[[29]]=2;
GGFMult[[30]]=2;
GGFMult[[31]]=2;
GGFMult[[32]]=2;
GGFMult[[33]]=2;
GGFMult[[34]]=2;
GGFMult[[35]]=2;
GGFMult[[36]]=2;
GGFMult[[37]]=2;
GGFMult[[38]]=2;
GGFMult[[39]]=2;
GGFMult[[40]]=2;
GGFMult[[41]]=2;
GGFMult[[42]]=2;
GGFMult[[43]]=2;
GGFMult[[44]]=2;
GGFMult[[45]]=2;
GGFMult[[46]]=2;
GGFMult[[47]]=2;
GGFMult[[48]]=2;
GGFMult[[49]]=2;
GGFMult[[50]]=2;
GGFMult[[51]]=2;
GGFMult[[52]]=2;
GGFMult[[53]]=2;
GGFMult[[54]]=2;
GGFMult[[55]]=2;
GGFMult[[56]]=2;
GGFMult[[57]]=2;
GGFMult[[58]]=2;
GGFMult[[59]]=2;
GGFMul

There are only $207$ inequivalent third-order disconnected diagrams with identical one-body vertex. The multiplicity check is fulfilled.

In [389]:
Sum[MultdVertex[[u]], {u, 1, 207}]

369

### <font color=#E9967A>Disconnected diagrams with three identical one-body vertices</font>

Depending on the components of the one-body potential into play, symmetry rules may apply and reduce the total number of fully-contracted terms. When the multiplied Nambu components of the one-body potential are identical, vertex exchange is possible, hence the filtration process is necessary. When the three one-body vertices are identical, the fully contracted terms which are mapped one another by the single-particle-index transpositions 

<center> $e \mapsto g \wedge f \mapsto h~\equiv~(eg)(fh)(i)(j)$, <br>
$e \mapsto i \wedge f \mapsto j~\equiv~(ei)(fj)(g)(h)$, <br>
$g \mapsto i \wedge h \mapsto j~\equiv~(gi)(hj)(e)(f)$, <br>
$e \mapsto g \wedge f \mapsto h \wedge g \mapsto i \wedge h 
\mapsto j \wedge i \mapsto e \wedge j \mapsto f~\equiv~(egi)(fhj)$, <br>
$e \mapsto i \wedge f \mapsto j \wedge g \mapsto e \wedge h \mapsto f \wedge i \mapsto g \wedge j \mapsto h \equiv (ige)(jhf)$, </center>

are equivalent, thus one of the six can be dropped, incrementing the associated multiplicity by $5$ units. In the end of the process, $87$ inequivalent fully-contracted terms corresponding to disconnected diagrams are found.  

In [390]:
AdVertex = Table[0, {i, 1, 369}, {j, 1, 5}, {k, 1, 2}];
MultdVertex = Table[0, {i, 1, 369}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 6}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 6}, {k, 1, 5}];

s = 1;
AdVertex[[1]] = Adisc[[1]];
MultdVertex[[1]] = 1;
For[u = 1, u <= 369, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   Temp[[1, i, j]] = Adisc[[u, i, j]];
   If[Adisc[[u, i, j]] == 1, Temp[[2, i, j]] = 3];
   If[Adisc[[u, i, j]] == 2, Temp[[2, i, j]] = 4];
   If[Adisc[[u, i, j]] == 3, Temp[[2, i, j]] = 1];
   If[Adisc[[u, i, j]] == 4, Temp[[2, i, j]] = 2];
   If[Adisc[[u, i, j]] >= 5, Temp[[2, i, j]] = Adisc[[u, i, j]]];
   If[Adisc[[u, i, j]] == 1, Temp[[3, i, j]] = 5];
   If[Adisc[[u, i, j]] == 2, Temp[[3, i, j]] = 6];
   If[Adisc[[u, i, j]] == 5, Temp[[3, i, j]] = 1];
   If[Adisc[[u, i, j]] == 6, Temp[[3, i, j]] = 2];
   If[(Adisc[[u, i, j]] >= 3 && Adisc[[u, i, j]] <= 4) || 
     Adisc[[u, i, j]] >= 7, Temp[[3, i, j]] = Adisc[[u, i, j]]];
   If[Adisc[[u, i, j]] == 3, Temp[[4, i, j]] = 5];
   If[Adisc[[u, i, j]] == 4, Temp[[4, i, j]] = 6];
   If[Adisc[[u, i, j]] == 5, Temp[[4, i, j]] = 3];
   If[Adisc[[u, i, j]] == 6, Temp[[4, i, j]] = 4];
   If[Adisc[[u, i, j]] <= 2 || Adisc[[u, i, j]] >= 7, 
    Temp[[4, i, j]] = Adisc[[u, i, j]]];
   If[Adisc[[u, i, j]] == 1, Temp[[5, i, j]] = 3];
   If[Adisc[[u, i, j]] == 2, Temp[[5, i, j]] = 4];
   If[Adisc[[u, i, j]] == 3, Temp[[5, i, j]] = 5];
   If[Adisc[[u, i, j]] == 4, Temp[[5, i, j]] = 6];
   If[Adisc[[u, i, j]] == 5, Temp[[5, i, j]] = 1];
   If[Adisc[[u, i, j]] == 6, Temp[[5, i, j]] = 2];
   If[Adisc[[u, i, j]] >= 7, Temp[[5, i, j]] = Adisc[[u, i, j]]];
   If[Adisc[[u, i, j]] == 1, Temp[[6, i, j]] = 5];
   If[Adisc[[u, i, j]] == 2, Temp[[6, i, j]] = 6];
   If[Adisc[[u, i, j]] == 3, Temp[[6, i, j]] = 1];
   If[Adisc[[u, i, j]] == 4, Temp[[6, i, j]] = 2];
   If[Adisc[[u, i, j]] == 5, Temp[[6, i, j]] = 3];
   If[Adisc[[u, i, j]] == 6, Temp[[6, i, j]] = 4];
   If[Adisc[[u, i, j]] >= 7, Temp[[6, i, j]] = Adisc[[u, i, j]]];
   ]];
 For[i = 1, i <= 6, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];
  If[Temp[[i, 5, 1]] > Temp[[i, 5, 2]], t2 = Temp[[i, 5, 2]]; 
   t1 = Temp[[i, 5, 1]]; Temp[[i, 5, 1]] = t2; Temp[[i, 5, 2]] = t1];
  ];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 6, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 6, j++,
      For[k = 1, k <= 5, k++,
        If[AdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[5, 1]] + IfTemp[[5, 2]] + IfTemp[[5, 3]] + 
      IfTemp[[5, 4]] + IfTemp[[5, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[6, 1]] + IfTemp[[6, 2]] + IfTemp[[6, 3]] + 
      IfTemp[[6, 4]] + IfTemp[[6, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdVertex[[v]] = MultdVertex[[v]] + 1];
   ];
  If[Ifrepeat == False , s++; AdVertex[[s]] = Adisc[[u]]; 
   MultdVertex[[v]] = 1];
  ];
 If[u == 369, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent disconnected contributions found."]];
 ]

Loop 369 completed and 87 inequivalent disconnected contributions found.


In [399]:
For[u = 1, u <= 87, u++, Print["CombDisc[[", u, "]]=", AdVertex[[u]], ";"]];

CombDisc[[1]]={{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}};
CombDisc[[2]]={{1, 2}, {3, 4}, {5, 6}, {7, 9}, {8, 10}};
CombDisc[[3]]={{1, 2}, {3, 4}, {5, 6}, {7, 10}, {8, 9}};
CombDisc[[4]]={{1, 2}, {3, 4}, {5, 7}, {6, 8}, {9, 10}};
CombDisc[[5]]={{1, 2}, {3, 4}, {5, 7}, {6, 9}, {8, 10}};
CombDisc[[6]]={{1, 2}, {3, 4}, {5, 7}, {6, 10}, {8, 9}};
CombDisc[[7]]={{1, 2}, {3, 4}, {5, 8}, {6, 7}, {9, 10}};
CombDisc[[8]]={{1, 2}, {3, 4}, {5, 8}, {7, 9}, {6, 10}};
CombDisc[[9]]={{1, 2}, {3, 4}, {5, 8}, {7, 10}, {6, 9}};
CombDisc[[10]]={{1, 2}, {3, 4}, {5, 9}, {7, 8}, {6, 10}};
CombDisc[[11]]={{1, 2}, {3, 4}, {5, 9}, {6, 7}, {8, 10}};
CombDisc[[12]]={{1, 2}, {3, 4}, {5, 9}, {7, 10}, {6, 8}};
CombDisc[[13]]={{1, 2}, {3, 4}, {5, 10}, {7, 8}, {6, 9}};
CombDisc[[14]]={{1, 2}, {3, 4}, {5, 10}, {7, 9}, {6, 8}};
CombDisc[[15]]={{1, 2}, {3, 4}, {5, 10}, {6, 7}, {8, 9}};
CombDisc[[16]]={{1, 2}, {3, 5}, {4, 6}, {7, 8}, {9, 10}};
CombDisc[[17]]={{1, 2}, {3, 5}, {4, 6}, {7, 9}, {8, 10}};
CombDisc[[18]]={{1, 2},

In [400]:
For[u = 1, u <= 87, u++, Print["GGFMult[[", u, "]]=", MultdVertex[[u]], ";"]];

GGFMult[[1]]=1;
GGFMult[[2]]=1;
GGFMult[[3]]=1;
GGFMult[[4]]=3;
GGFMult[[5]]=3;
GGFMult[[6]]=3;
GGFMult[[7]]=3;
GGFMult[[8]]=3;
GGFMult[[9]]=3;
GGFMult[[10]]=3;
GGFMult[[11]]=3;
GGFMult[[12]]=3;
GGFMult[[13]]=3;
GGFMult[[14]]=3;
GGFMult[[15]]=3;
GGFMult[[16]]=3;
GGFMult[[17]]=3;
GGFMult[[18]]=3;
GGFMult[[19]]=6;
GGFMult[[20]]=6;
GGFMult[[21]]=6;
GGFMult[[22]]=6;
GGFMult[[23]]=6;
GGFMult[[24]]=6;
GGFMult[[25]]=3;
GGFMult[[26]]=3;
GGFMult[[27]]=3;
GGFMult[[28]]=6;
GGFMult[[29]]=6;
GGFMult[[30]]=6;
GGFMult[[31]]=6;
GGFMult[[32]]=6;
GGFMult[[33]]=6;
GGFMult[[34]]=6;
GGFMult[[35]]=6;
GGFMult[[36]]=6;
GGFMult[[37]]=6;
GGFMult[[38]]=6;
GGFMult[[39]]=6;
GGFMult[[40]]=6;
GGFMult[[41]]=6;
GGFMult[[42]]=6;
GGFMult[[43]]=6;
GGFMult[[44]]=6;
GGFMult[[45]]=6;
GGFMult[[46]]=6;
GGFMult[[47]]=6;
GGFMult[[48]]=6;
GGFMult[[49]]=6;
GGFMult[[50]]=6;
GGFMult[[51]]=6;
GGFMult[[52]]=6;
GGFMult[[53]]=6;
GGFMult[[54]]=6;
GGFMult[[55]]=6;
GGFMult[[56]]=6;
GGFMult[[57]]=6;
GGFMult[[58]]=3;
GGFMult[[59]]=3;
GGFMul

There are only $87$ inequivalent third-order disconnected diagrams with three identical one-body vertices. The multiplicity check is fulfilled.

In [401]:
Sum[MultdVertex[[u]], {u, 1, 87}]

369