# <font color=#DC143C size="+3">Automated generation of Wick's-theorem contributions </font> 
<font color=#9D9D9C size ="+2.25"> at second order in perturbation theory for Gorkov's polarization propagator</font> </br> <font color=#000000 size ="+1">with a one-body and a two-body interaction vertex</font>

 ## <font color=#FA8072>Conventions</font>

<p align="justify">From the application of Wick's theorem to the following matrix element (cf. expansion formula of Gorkov's polarization propagator), </p>

$\Pi_{acdb}^{g_1g_3g_4g_2}(t,t')\lvert_{\mathrm{second~order}}\equiv +2i\left(\frac{-i}{\hbar}\right)^2 \frac{1}{2!}\int\mathrm{d}t_1 \int\mathrm{d}t_2 \langle \Phi_0 \lvert T\{\bar{V}(t_1) U(t_2) {A_{I}}_a^{g_1}(t){A_{I}}_b^{g_2}(t'){A_{I}}_d^{\dagger g_4}(t') {A_{I}}_c^{\dagger g_3}(t)\}\lvert\Phi_0\rangle_{\mathrm{conn}}$

the fully-contracted terms consisting of $10$ second-quantization operators are generated. The nuclear-potential insertions of one and two-body type, $U(t_2)$ and $\bar{V}(t_1)$, take the form

$\bar{V}(t_1) = \frac{1}{4} \sum_{pqrs} \bar{v}_{pqrs} {a_I}_p^{\dagger}(t_1){a_I}_q^{\dagger}(t_1) {a_I}_s(t_1) {a_I}_r(t_1)~,$

$U(t_2) = \frac{1}{2}\sum_{ef}[u_{ef}^{11}{a_I}_e^{\dagger}(t_2){a_I}_f(t_2)+u_{ef}^{22}{a_I}_{\bar{e}}(t_2){a_I}_{\bar{f}}^{\dagger}(t_2)+u_{ef}^{12}{a_I}_e^{\dagger}(t_2){a_I}_{\bar{f}}^{\dagger}(t_2)+u_{ef}^{21}{a_I}_{\bar{e}}(t_2){a_I}_f(t_2)]~.$

<p align="justify"> Due to the presence of a one-body interaction vertex and a two-body interaction vertex, the number of distinct fully-contracted terms corresponds to $9!! = 945$. The results of the generation process hold identically for all the $4$ Nambu components of the one-body potential and are the same for each of the $16$ Nambu components of Gorkov's polarization propagator.  A significant part of these Wick's-theorem contributions has to be discarded, since it corresponds either to disconnected diagrams or to exchange diagrams that are cancelled by the subtractive term of the polarization propagator.  At second order, also conjoint diagrams containing one- and two-body interaction vertices exist. Additionally, since the one-body potential is not invariant under permutation of the two indices, the filtration process accounts only for the intra-vertex transpositions of single-particle indices belonging to the two-body vertex.</p>

In [1]:
9*7*5*3*1

945

The alphabetic single-particle indices of the second-quantization operators are converted into positive integers by means of the following map:

<table>
    <tr>
        <th> p </th> 
        <th> q </th>
        <th> s </th> 
        <th> r </th>
        <th> e </th> 
        <th> f </th>        
        <th> a </th> 
        <th> b </th>
        <th> d </th>
        <th> c </th>
    </tr>
    <tr>
        <th> 1 </th> 
        <th> 2 </th>
        <th> 3 </th>
        <th> 4 </th>
        <th> 5 </th> 
        <th> 6 </th>
        <th> 7 </th> 
        <th> 8 </th>
        <th> 9 </th> 
        <th> 10 </th>
    </tr>
</table>

as such, the single particle indices are stored into arrays (cf. 'Acomb', 'Acombsort', 'AdisjBogoDiag' et c.).

 ## <font color=#FA8072>Generation of the first-order fully-contracted terms</font>

The second-order fully-contracted terms are found to be 945 in total, consistently with the formula $4n+2m+3!!$ with $n=1$ and $m=1$. Binary contractions belonging to the same fully contracted term (index $i$ in the array initialization) are denoted by the index $j$. The two single particle indices within the same contraction are distinguished by the index $k$. The process produces no repeated pairs, by construction.

In [3]:
l = 1;
Acomb = Table[0, {i, 1, 950}, {j, 1, 5}, {k, 1, 2}];
Acomb[[l]] = {{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}};
For[g = 1, g <= 9, g++,
  growind = 1;
  gcolind = 2;
  For[h = 1, h <= 7, h++,
   hrowind = 2;
   hcolind = 2;
   For[i = 1, i <= 5, i++,
    irowind = 3;
    icolind = 2;
    For[j = 1, j <= 3, j++,
     jrowind = 4;
     jcolind = 2;
     Acomb[[l]] = Acomb[[1]];
     If[g != 1,
      growpiv = Floor[g/2] + 1;
      gcolpiv = - Floor[g/2] + Ceiling[g/2] + 1;
      Acomb[[l, growind, gcolind]] = Acomb[[1, growpiv, gcolpiv]];
      Acomb[[l, growpiv, gcolpiv]] = Acomb[[1, growind, gcolind]]];
     If[h != 1,
      hrowpiv = Floor[h/2] + 2;
      hcolpiv = - Floor[h/2] + Ceiling[h/2] + 1;
      Atemp1 = Acomb[[l, hrowind, hcolind]];
      Atemp2 = Acomb[[l, hrowpiv, hcolpiv]];
      Acomb[[l, hrowind, hcolind]] = Atemp2;
      Acomb[[l, hrowpiv, hcolpiv]] = Atemp1];
     If[i != 1,
      irowpiv = Floor[i/2] + 3;
      icolpiv = - Floor[i/2] + Ceiling[i/2] + 1;
      Atemp1 = Acomb[[l, irowind, icolind]];
      Atemp2 = Acomb[[l, irowpiv, icolpiv]];
      Acomb[[l, irowind, icolind]] = Atemp2;
      Acomb[[l, irowpiv, icolpiv]] = Atemp1];
     If[j != 1,
      jrowpiv = Floor[j/2] + 4;
      jcolpiv = - Floor[j/2] + Ceiling[j/2] + 1;
      Atemp1 = Acomb[[l, jrowind, jcolind]];
      Atemp2 = Acomb[[l, jrowpiv, jcolpiv]];
      Acomb[[l, jrowind, jcolind]] = Atemp2;
      Acomb[[l, jrowpiv, jcolpiv]] = Atemp1];
     l++]]];
  If[g == 9, 
   Print["Loop ", g, " completed and ", l - 1, 
    " Wick's-theorem contributions generated."]]];


Loop 9 completed and 945 Wick's-theorem contributions generated.


Sorting code for the generated fully-contracted terms. Single-particle indices within the same contraction are sorted in ascending order.

In [7]:
Acombsort = Table[0, {i, 1, 945}, {j, 1, 5}, {k, 1, 2}];
For[s = 1, s <= 945, s++,
  If[Acomb[[s, 1, 1]] > Acomb[[s, 1, 2]],
   Acombsort[[s, 1, 1]] = Acomb[[s, 1, 2]];
   Acombsort[[s, 1, 2]] = Acomb[[s, 1, 1]],
   Acombsort[[s, 1]] = Acomb[[s, 1]];];
  If[Acomb[[s, 2, 1]] > Acomb[[s, 2, 2]],
   Acombsort[[s, 2, 1]] = Acomb[[s, 2, 2]];
   Acombsort[[s, 2, 2]] = Acomb[[s, 2, 1]],
   Acombsort[[s, 2]] = Acomb[[s, 2]];];
  If[Acomb[[s, 3, 1]] > Acomb[[s, 3, 2]],
   Acombsort[[s, 3, 1]] = Acomb[[s, 3, 2]];
   Acombsort[[s, 3, 2]] = Acomb[[s, 3, 1]],
   Acombsort[[s, 3]] = Acomb[[s, 3]];];
  If[Acomb[[s, 4, 1]] > Acomb[[s, 4, 2]],
   Acombsort[[s, 4, 1]] = Acomb[[s, 4, 2]];
   Acombsort[[s, 4, 2]] = Acomb[[s, 4, 1]],
   Acombsort[[s, 4]] = Acomb[[s, 4]];];
  If[Acomb[[s, 5, 1]] > Acomb[[s, 5, 2]],
   Acombsort[[s, 5, 1]] = Acomb[[s, 5, 2]];
   Acombsort[[s, 5, 2]] = Acomb[[s, 5, 1]],
   Acombsort[[s, 5]] = Acomb[[s, 5]];];];

# <font color=#71797E>Conjoint Diagrams</font>

The conjoint contributions at second order containing a one-body and a two-body interaction vertex are $216$ in total and all belong to the composite type.

In [9]:
Aconjsort = Table[0, {i, 1, 945}, {j, 1, 5}, {k, 1, 2}];
l = 1;
For[i = 1, i <= 945, i++, 
 IfConjoint = False;
 Link12 = False;
 Conn7V2 = False;
 Conn8V2 = False;
 Conn9V2 = False;
 Conn10V2 = False;
 For[j = 1, j <= 5, j++,
  If[Acombsort[[i, j]] == {1, 7} || Acombsort[[i, j]] == {2, 7} || 
    Acombsort[[i, j]] == {3, 7} || Acombsort[[i, j]] == {4, 7} , 
   Conn7V2 = True];
  If[Acombsort[[i, j]] == {1, 8} || Acombsort[[i, j]] == {2, 8} || 
    Acombsort[[i, j]] == {3, 8} || Acombsort[[i, j]] == {4, 8} , 
   Conn8V2 = True];
  If[Acombsort[[i, j]] == {1, 9} || Acombsort[[i, j]] == {2, 9} || 
    Acombsort[[i, j]] == {3, 9} || Acombsort[[i, j]] == {4, 9} , 
   Conn9V2 = True];
  If[Acombsort[[i, j]] == {1, 10} || Acombsort[[i, j]] == {2, 10} || 
    Acombsort[[i, j]] == {3, 10} || Acombsort[[i, j]] == {4, 10} , 
   Conn10V2 = True];
  If[Acombsort[[i, j]] == {1, 5} || Acombsort[[i, j]] == {1, 6} || 
    Acombsort[[i, j]] == {2, 5} || Acombsort[[i, j]] == {2, 6} || 
    Acombsort[[i, j]] == {3, 5} || Acombsort[[i, j]] == {3, 6} || 
    Acombsort[[i, j]] == {4, 5} || Acombsort[[i, j]] == {4, 6}, 
   Link12 = True];
  ]; 
 If[Conn7V2 == True && Conn8V2 == True && Conn9V2 == True && 
   Link12 == True, IfConjoint = True];
 If[Conn7V2 == True && Conn8V2 == True && Conn10V2 == True &&  
   Link12 == True, IfConjoint = True];
 If[Conn7V2 == True && Conn9V2 == True && Conn10V2 == True &&  
   Link12 == True, IfConjoint = True];
 If[Conn8V2 == True && Conn9V2 == True && Conn10V2 == True &&  
   Link12 == True, IfConjoint = True];
 If[ IfConjoint == True, Aconjsort[[l]] = Acombsort[[i]]; l++]; 
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", l - 1, 
   " conjoint contributions found."] ]]

Loop 100 completed and 0 conjoint contributions found.
Loop 200 completed and 0 conjoint contributions found.
Loop 300 completed and 0 conjoint contributions found.
Loop 400 completed and 16 conjoint contributions found.
Loop 500 completed and 37 conjoint contributions found.
Loop 600 completed and 68 conjoint contributions found.
Loop 700 completed and 104 conjoint contributions found.
Loop 800 completed and 142 conjoint contributions found.
Loop 900 completed and 176 conjoint contributions found.
Loop 945 completed and 192 conjoint contributions found.


There are only $192$ second-order conjoint contributions.

In [12]:
For[u = 1, u <= 192, u++, Print[Aconjsort[[u]]]]

{{1, 5}, {3, 7}, {2, 8}, {4, 9}, {6, 10}}
{{1, 5}, {3, 7}, {2, 8}, {4, 10}, {6, 9}}
{{1, 5}, {3, 7}, {2, 9}, {4, 8}, {6, 10}}
{{1, 5}, {3, 7}, {2, 9}, {4, 10}, {6, 8}}
{{1, 5}, {3, 7}, {2, 10}, {4, 8}, {6, 9}}
{{1, 5}, {3, 7}, {2, 10}, {4, 9}, {6, 8}}
{{1, 5}, {3, 8}, {2, 7}, {6, 9}, {4, 10}}
{{1, 5}, {3, 8}, {2, 7}, {6, 10}, {4, 9}}
{{1, 5}, {3, 8}, {2, 9}, {4, 7}, {6, 10}}
{{1, 5}, {3, 8}, {2, 9}, {6, 7}, {4, 10}}
{{1, 5}, {3, 8}, {2, 10}, {4, 7}, {6, 9}}
{{1, 5}, {3, 8}, {2, 10}, {6, 7}, {4, 9}}
{{1, 5}, {3, 9}, {2, 7}, {6, 8}, {4, 10}}
{{1, 5}, {3, 9}, {2, 7}, {6, 10}, {4, 8}}
{{1, 5}, {3, 9}, {2, 8}, {6, 7}, {4, 10}}
{{1, 5}, {3, 9}, {2, 8}, {4, 7}, {6, 10}}
{{1, 5}, {3, 9}, {2, 10}, {4, 7}, {6, 8}}
{{1, 5}, {3, 9}, {2, 10}, {6, 7}, {4, 8}}
{{1, 5}, {3, 10}, {2, 7}, {6, 8}, {4, 9}}
{{1, 5}, {3, 10}, {2, 7}, {6, 9}, {4, 8}}
{{1, 5}, {3, 10}, {2, 8}, {6, 7}, {4, 9}}
{{1, 5}, {3, 10}, {2, 8}, {4, 7}, {6, 9}}
{{1, 5}, {3, 10}, {2, 9}, {6, 7}, {4, 8}}
{{1, 5}, {3, 10}, {2, 9}, {4, 7}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the conjoint composite diagrams. At first order, transpositions between single-particle indices of different vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [13]:
AccVertex = Table[0, {i, 1, 192}, {j, 1, 5}, {k, 1, 2}];
MultccVertex = Table[0, {i, 1, 192}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AccVertex[[1]] = Aconjsort[[1]];
MultccVertex[[1]] = 1;
For[u = 1, u <= 192, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[Aconjsort[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[Aconjsort[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[Aconjsort[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = Aconjsort[[u, i, j]]];
   If[Aconjsort[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[Aconjsort[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[Aconjsort[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[Aconjsort[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[Aconjsort[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = Aconjsort[[u, i, j]]];
   If[Aconjsort[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[Aconjsort[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[Aconjsort[[u, i, j]] >= 5 || Aconjsort[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = Aconjsort[[u, i, j]]];
   Temp[[4, i, j]] = Aconjsort[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AccVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultccVertex[[v]] = MultccVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AccVertex[[s]] = Aconjsort[[u]]; 
   MultccVertex[[s]] = 1;];
  ];
 If[u == 192, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent conjoint contributions found."]];
 ]

Loop 192 completed and 48 inequivalent conjoint contributions found.


In [22]:
For[u = 1, u <= 48, u++, Print["CombComp[[", u, "]]=", AccVertex[[u]], ";"]];

CombComp[[1]]={{1, 5}, {3, 7}, {2, 8}, {4, 9}, {6, 10}};
CombComp[[2]]={{1, 5}, {3, 7}, {2, 8}, {4, 10}, {6, 9}};
CombComp[[3]]={{1, 5}, {3, 7}, {2, 9}, {4, 8}, {6, 10}};
CombComp[[4]]={{1, 5}, {3, 7}, {2, 9}, {4, 10}, {6, 8}};
CombComp[[5]]={{1, 5}, {3, 7}, {2, 10}, {4, 8}, {6, 9}};
CombComp[[6]]={{1, 5}, {3, 7}, {2, 10}, {4, 9}, {6, 8}};
CombComp[[7]]={{1, 5}, {3, 8}, {2, 7}, {6, 9}, {4, 10}};
CombComp[[8]]={{1, 5}, {3, 8}, {2, 7}, {6, 10}, {4, 9}};
CombComp[[9]]={{1, 5}, {3, 8}, {2, 9}, {6, 7}, {4, 10}};
CombComp[[10]]={{1, 5}, {3, 8}, {2, 10}, {6, 7}, {4, 9}};
CombComp[[11]]={{1, 5}, {3, 9}, {2, 7}, {6, 8}, {4, 10}};
CombComp[[12]]={{1, 5}, {3, 9}, {2, 8}, {6, 7}, {4, 10}};
CombComp[[13]]={{1, 6}, {3, 7}, {5, 8}, {4, 9}, {2, 10}};
CombComp[[14]]={{1, 6}, {3, 7}, {5, 8}, {4, 10}, {2, 9}};
CombComp[[15]]={{1, 6}, {3, 7}, {5, 9}, {4, 8}, {2, 10}};
CombComp[[16]]={{1, 6}, {3, 7}, {5, 9}, {4, 10}, {2, 8}};
CombComp[[17]]={{1, 6}, {3, 7}, {5, 10}, {4, 8}, {2, 9}};
CombComp[[18]]={{1, 6},

In [23]:
For[u = 1, u <= 48, u++, Print["GGFMult[[", u, "]]=", MultccVertex[[u]], ";"]];

GGFMult[[1]]=4;
GGFMult[[2]]=4;
GGFMult[[3]]=4;
GGFMult[[4]]=4;
GGFMult[[5]]=4;
GGFMult[[6]]=4;
GGFMult[[7]]=4;
GGFMult[[8]]=4;
GGFMult[[9]]=4;
GGFMult[[10]]=4;
GGFMult[[11]]=4;
GGFMult[[12]]=4;
GGFMult[[13]]=4;
GGFMult[[14]]=4;
GGFMult[[15]]=4;
GGFMult[[16]]=4;
GGFMult[[17]]=4;
GGFMult[[18]]=4;
GGFMult[[19]]=4;
GGFMult[[20]]=4;
GGFMult[[21]]=4;
GGFMult[[22]]=4;
GGFMult[[23]]=4;
GGFMult[[24]]=4;
GGFMult[[25]]=4;
GGFMult[[26]]=4;
GGFMult[[27]]=4;
GGFMult[[28]]=4;
GGFMult[[29]]=4;
GGFMult[[30]]=4;
GGFMult[[31]]=4;
GGFMult[[32]]=4;
GGFMult[[33]]=4;
GGFMult[[34]]=4;
GGFMult[[35]]=4;
GGFMult[[36]]=4;
GGFMult[[37]]=4;
GGFMult[[38]]=4;
GGFMult[[39]]=4;
GGFMult[[40]]=4;
GGFMult[[41]]=4;
GGFMult[[42]]=4;
GGFMult[[43]]=4;
GGFMult[[44]]=4;
GGFMult[[45]]=4;
GGFMult[[46]]=4;
GGFMult[[47]]=4;
GGFMult[[48]]=4;


There are only $48$ second-order conjoint (composite) inequivalent contributions with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [24]:
Sum[MultccVertex[[u]], {u, 1, 48}]

192

# <font color=#71797E>Disjoint Diagrams</font>

<p align="justify">
The disjoint  diagrams at second order are $576$ in total. These are distributed as follows: <br>
i) $72$ Bogoliubov diagrams dressed in the antidiagonal; <br>
ii) $72$ Bogoliubov diagrams dressed in the diagonal; <br>
iii) $48$ Bogoliubov diagrams dressed in both the diagonal and the antidiagonal; <br>
iv) $72$ Direct diagrams dressed in the left propagator; <br>
v) $72$ Direct diagrams dressed in the right propagator; <br>
vi) $48$ Direct diagrams dressed in both the left and the right propagator; <br>
vii) $72$ Exchange diagrams dressed in the propagator above; <br>
viii) $72$ Exchange diagrams dressed in the propagator below; <br>
ix) $48$ Exchange diagrams dressed in both the above and below propagator; <br> </p>

Total number of disjoint diagrams:

In [2]:
945 - 192 - 177

576

In [25]:
AdisjBogoDiag = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjBogoAntidiag = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjBogoliubov = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirLeft = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirRight = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjDirect = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchAbove = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchBelow = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
AdisjExchange = Table[0, {i, 1, 576}, {j, 1, 5}, {k, 1, 2}];
l = 1;
m = 1;
n = 1;
o = 1;
p = 1;
q = 1;
r = 1;
s = 1;
t = 1;
For[i = 1, i <= 945, i++,
 Link12 = False; 
 Conn7V1 = False;
 Conn7V2 = False;
 Conn8V1 = False;
 Conn8V2 = False;
 Conn9V1 = False;
 Conn9V2 = False;
 Conn10V1 = False;
 Conn10V2 = False;
 Bridge78 = False;
 Bridge79 = False;
 Bridge710 = False;
 Bridge89 = False;
 Bridge810 = False;
 Bridge910 = False;
 For[j = 1, j <= 5, j++,
  If[Acombsort[[i, j]] == {7, 8}, Bridge78 = True];
  If[Acombsort[[i, j]] == {7, 9}, Bridge79 = True];
  If[Acombsort[[i, j]] == {7, 10}, Bridge710 = True];
  If[Acombsort[[i, j]] == {8, 9}, Bridge89 = True];
  If[Acombsort[[i, j]] == {8, 10}, Bridge810 = True];
  If[Acombsort[[i, j]] == {9, 10}, Bridge910 = True];
  If[Acombsort[[i, j]] == {5, 7} || Acombsort[[i, j]] == {6, 7}, 
   Conn7V1 = True];
  If[Acombsort[[i, j]] == {5, 8} || Acombsort[[i, j]] == {6, 8}, 
   Conn8V1 = True];
  If[Acombsort[[i, j]] == {5, 9} || Acombsort[[i, j]] == {6, 9}, 
   Conn9V1 = True];
  If[Acombsort[[i, j]] == {5, 10} || Acombsort[[i, j]] == {6, 10}, 
   Conn10V1 = True];
  If[Acombsort[[i, j]] == {1, 7} || Acombsort[[i, j]] == {2, 7} || 
    Acombsort[[i, j]] == {3, 7} || Acombsort[[i, j]] == {4, 7} , 
   Conn7V2 = True];
  If[Acombsort[[i, j]] == {1, 8} || Acombsort[[i, j]] == {2, 8} || 
    Acombsort[[i, j]] == {3, 8} || Acombsort[[i, j]] == {4, 8} , 
   Conn8V2 = True];
  If[Acombsort[[i, j]] == {1, 9} || Acombsort[[i, j]] == {2, 9} || 
    Acombsort[[i, j]] == {3, 9} || Acombsort[[i, j]] == {4, 9} , 
   Conn9V2 = True];
  If[Acombsort[[i, j]] == {1, 10} || Acombsort[[i, j]] == {2, 10} || 
    Acombsort[[i, j]] == {3, 10} || Acombsort[[i, j]] == {4, 10} , 
   Conn10V2 = True];
  If[Acombsort[[i, j]] == {1, 5} || Acombsort[[i, j]] == {1, 6} || 
    Acombsort[[i, j]] == {2, 5} || Acombsort[[i, j]] == {2, 6} || 
    Acombsort[[i, j]] == {3, 5} || 
    Acombsort[[i, j]] == {3, 6} || Acombsort[[i, j]] == {4, 5} || 
    Acombsort[[i, j]] == {4, 6}, Link12 = True;];
  ];
 If[Link12 == False && Conn7V2 == True && Conn8V2 == True && 
   Conn9V2 == False && Conn10V2 == False && Conn7V1 == False && 
   Conn8V1 == False && 
   Conn9V1 == True && Conn10V1 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Link12 == False && Conn7V1 == True && Conn8V1 == True && 
   Conn9V1 == False && Conn10V1 == False && Conn7V2 == False && 
   Conn8V2 == False && 
   Conn9V2 == True && Conn10V2 == True, 
  AdisjBogoliubov[[n]] = Acombsort[[i]]; n++];
 If[Link12 == False && Conn7V2 == True && Conn8V2 == False && 
   Conn9V2 == True && Conn10V2 == False && Conn7V1 == False && 
   Conn8V1 == True && 
   Conn9V1 == False && Conn10V1 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Link12 == False && Conn7V1 == True && Conn8V1 == False && 
   Conn9V1 == True && Conn10V1 == False && Conn7V2 == False && 
   Conn8V2 == True && 
   Conn9V2 == False && Conn10V2 == True, 
  AdisjDirect[[q]] = Acombsort[[i]]; q++];
 If[Link12 == False && Conn7V2 == True && Conn8V2 == False && 
   Conn9V2 == False && Conn10V2 == True && Conn7V1 == False && 
   Conn8V1 == True && 
   Conn9V1 == True && Conn10V1 == False, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Link12 == False && Conn7V1 == True && Conn8V1 == False && 
   Conn9V1 == False && Conn10V1 == True && Conn7V2 == False && 
   Conn8V2 == True && 
   Conn9V2 == True && Conn10V2 == False, 
  AdisjExchange[[t]] = Acombsort[[i]]; t++];
 If[Link12 == True && Bridge79 == True && Bridge810 == False, 
  AdisjDirRight[[p]] = Acombsort[[i]]; p++];
 If[Link12 == True && Bridge79 == False && Bridge810 == True, 
  AdisjDirLeft[[o]] = Acombsort[[i]]; o++];
 If[Link12 == True &&  Bridge78 == True && Bridge910 == False, 
  AdisjBogoAntidiag[[l]] = Acombsort[[i]]; l++];
 If[Link12 == True && Bridge78 == False && Bridge910 == True, 
  AdisjBogoDiag[[m]] = Acombsort[[i]]; m++];
 If[Link12 == True && Bridge710 == False && Bridge89 == True, 
  AdisjExchAbove[[r]] = Acombsort[[i]]; r++];
 If[ Link12 == True && Bridge710 == True && Bridge89 == False, 
  AdisjExchBelow[[s]] = Acombsort[[i]]; s++];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", l - 1, 
   " antidiagonally-dressed Bogoliubov contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", m - 1, 
   " diagonally-dressed Bogoliubov contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", n - 1, 
   " diagonally-and-antidiagonally-dressed Bogoliubov contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", r - 1, 
   " above-dressed exchange contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", s - 1, 
   " below-dressed exchange contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", t - 1, 
   " above-and-below-dressed exchange contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", o - 1, 
   " left-dressed direct contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", p - 1, 
   " right-dressed direct contributions found."] ];
 If[Mod[i, 100] == 0 || i == 945, 
  Print["Loop ", i, " completed and ", q - 1, 
   " left-and-right-dressed direct contributions found."] ];]

Loop 100 completed and 7 antidiagonally-dressed Bogoliubov contributions\
 
>    found.
Loop 100 completed and 8 diagonally-dressed Bogoliubov contributions found.
Loop 100 completed and 8 diagonally-and-antidiagonally-dressed Bogoliubov\
 
>    contributions found.
Loop 100 completed and 7 above-dressed exchange contributions found.
Loop 100 completed and 8 below-dressed exchange contributions found.
Loop 100 completed and 7 above-and-below-dressed exchange contributions found.
Loop 100 completed and 8 left-dressed direct contributions found.
Loop 100 completed and 7 right-dressed direct contributions found.
Loop 100 completed and 7 left-and-right-dressed direct contributions found.
Loop 200 completed and 14 antidiagonally-dressed Bogoliubov contributions\
 
>    found.
Loop 200 completed and 16 diagonally-dressed Bogoliubov contributions found.
Loop 200 completed and 15 diagonally-and-antidiagonally-dressed Bogoliubov\
 
>    contributions found.
Loop 200 completed and 14 above-dress

 ## <font color=#FA8072>Disjoint direct diagrams with dressed single-particle propagator on the left</font>

Direct diagrams with unperturbed 1-body propagator on the right are processed. Their initial number is $72$ in total.

In [44]:
For[u = 1, u <= 72, u++, Print[AdisjDirLeft[[u]]]];

{{1, 2}, {3, 5}, {4, 7}, {6, 9}, {8, 10}}
{{1, 2}, {3, 5}, {4, 9}, {6, 7}, {8, 10}}
{{1, 2}, {3, 6}, {5, 7}, {4, 9}, {8, 10}}
{{1, 2}, {3, 6}, {5, 9}, {4, 7}, {8, 10}}
{{1, 2}, {3, 7}, {4, 5}, {6, 9}, {8, 10}}
{{1, 2}, {3, 7}, {5, 9}, {4, 6}, {8, 10}}
{{1, 2}, {3, 9}, {5, 7}, {4, 6}, {8, 10}}
{{1, 2}, {3, 9}, {4, 5}, {6, 7}, {8, 10}}
{{1, 3}, {2, 5}, {4, 7}, {6, 9}, {8, 10}}
{{1, 3}, {2, 5}, {4, 9}, {6, 7}, {8, 10}}
{{1, 3}, {2, 6}, {5, 7}, {4, 9}, {8, 10}}
{{1, 3}, {2, 6}, {5, 9}, {4, 7}, {8, 10}}
{{1, 3}, {2, 7}, {4, 5}, {6, 9}, {8, 10}}
{{1, 3}, {2, 7}, {5, 9}, {4, 6}, {8, 10}}
{{1, 3}, {2, 9}, {5, 7}, {4, 6}, {8, 10}}
{{1, 3}, {2, 9}, {4, 5}, {6, 7}, {8, 10}}
{{1, 4}, {3, 5}, {2, 7}, {6, 9}, {8, 10}}
{{1, 4}, {3, 5}, {2, 9}, {6, 7}, {8, 10}}
{{1, 4}, {3, 6}, {5, 7}, {2, 9}, {8, 10}}
{{1, 4}, {3, 6}, {5, 9}, {2, 7}, {8, 10}}
{{1, 4}, {3, 7}, {2, 5}, {6, 9}, {8, 10}}
{{1, 4}, {3, 7}, {5, 9}, {2, 6}, {8, 10}}
{{1, 4}, {3, 9}, {5, 7}, {2, 6}, {8, 10}}
{{1, 4}, {3, 9}, {2, 5}, {6, 7}, {

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the left-dressed disjoint direct diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [45]:
AdcdlVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdcdlVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcdlVertex[[1]] = AdisjDirLeft[[1]];
MultdcdlVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjDirLeft[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjDirLeft[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjDirLeft[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[ AdisjDirLeft[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjDirLeft[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjDirLeft[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjDirLeft[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjDirLeft[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirLeft[[u, i, j]]];
   If[ AdisjDirLeft[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjDirLeft[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjDirLeft[[u, i, j]] >= 5 || AdisjDirLeft[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjDirLeft[[u, i, j]]];
   Temp[[4, i, j]] = AdisjDirLeft[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdlVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdlVertex[[v]] = MultdcdlVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcdlVertex[[s]] = AdisjDirLeft[[u]]; 
   MultdcdlVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent left-dressed disjoint direct contributions found."]];
 ]

Loop 72 completed and 22 inequivalent left-dressed disjoint direct\
 
>    contributions found.


In [54]:
For[u = 1, u <= 22, u++, Print["CombDirLeft[[", u, "]]=", AdcdlVertex[[u]], ";"]];

CombDirLeft[[1]]={{1, 2}, {3, 5}, {4, 7}, {6, 9}, {8, 10}};
CombDirLeft[[2]]={{1, 2}, {3, 5}, {4, 9}, {6, 7}, {8, 10}};
CombDirLeft[[3]]={{1, 2}, {3, 6}, {5, 7}, {4, 9}, {8, 10}};
CombDirLeft[[4]]={{1, 2}, {3, 6}, {5, 9}, {4, 7}, {8, 10}};
CombDirLeft[[5]]={{1, 3}, {2, 5}, {4, 7}, {6, 9}, {8, 10}};
CombDirLeft[[6]]={{1, 3}, {2, 5}, {4, 9}, {6, 7}, {8, 10}};
CombDirLeft[[7]]={{1, 3}, {2, 6}, {5, 7}, {4, 9}, {8, 10}};
CombDirLeft[[8]]={{1, 3}, {2, 6}, {5, 9}, {4, 7}, {8, 10}};
CombDirLeft[[9]]={{1, 3}, {2, 7}, {4, 5}, {6, 9}, {8, 10}};
CombDirLeft[[10]]={{1, 3}, {2, 7}, {5, 9}, {4, 6}, {8, 10}};
CombDirLeft[[11]]={{1, 3}, {2, 9}, {5, 7}, {4, 6}, {8, 10}};
CombDirLeft[[12]]={{1, 3}, {2, 9}, {4, 5}, {6, 7}, {8, 10}};
CombDirLeft[[13]]={{1, 5}, {3, 4}, {2, 7}, {6, 9}, {8, 10}};
CombDirLeft[[14]]={{1, 5}, {3, 4}, {2, 9}, {6, 7}, {8, 10}};
CombDirLeft[[15]]={{1, 5}, {3, 6}, {2, 7}, {4, 9}, {8, 10}};
CombDirLeft[[16]]={{1, 5}, {3, 6}, {2, 9}, {4, 7}, {8, 10}};
CombDirLeft[[17]]={{1, 5}, {3, 7}

In [55]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdcdlVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=4
GGFMult[[16]]=4
GGFMult[[17]]=4
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=4
GGFMult[[21]]=4
GGFMult[[22]]=4


There are $22$ second-order left-dressed disjoint direct diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [56]:
Sum[MultdcdlVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint direct diagrams with dressed single-particle propagator on the right</font>

Direct diagrams with unperturbed 1-body propagator on the left are processed. Their initial number is $72$ in total.

In [57]:
For[u = 1, u <= 72, u++, Print[AdisjDirRight[[u]]]];

{{1, 2}, {3, 5}, {4, 8}, {7, 9}, {6, 10}}
{{1, 2}, {3, 5}, {4, 10}, {7, 9}, {6, 8}}
{{1, 2}, {3, 6}, {5, 8}, {7, 9}, {4, 10}}
{{1, 2}, {3, 6}, {5, 10}, {7, 9}, {4, 8}}
{{1, 2}, {3, 8}, {4, 5}, {7, 9}, {6, 10}}
{{1, 2}, {3, 8}, {5, 10}, {7, 9}, {4, 6}}
{{1, 2}, {3, 10}, {5, 8}, {7, 9}, {4, 6}}
{{1, 2}, {3, 10}, {4, 5}, {7, 9}, {6, 8}}
{{1, 3}, {2, 5}, {4, 8}, {7, 9}, {6, 10}}
{{1, 3}, {2, 5}, {4, 10}, {7, 9}, {6, 8}}
{{1, 3}, {2, 6}, {5, 8}, {7, 9}, {4, 10}}
{{1, 3}, {2, 6}, {5, 10}, {7, 9}, {4, 8}}
{{1, 3}, {2, 8}, {4, 5}, {7, 9}, {6, 10}}
{{1, 3}, {2, 8}, {5, 10}, {7, 9}, {4, 6}}
{{1, 3}, {2, 10}, {5, 8}, {7, 9}, {4, 6}}
{{1, 3}, {2, 10}, {4, 5}, {7, 9}, {6, 8}}
{{1, 4}, {3, 5}, {2, 8}, {7, 9}, {6, 10}}
{{1, 4}, {3, 5}, {2, 10}, {7, 9}, {6, 8}}
{{1, 4}, {3, 6}, {5, 8}, {7, 9}, {2, 10}}
{{1, 4}, {3, 6}, {5, 10}, {7, 9}, {2, 8}}
{{1, 4}, {3, 8}, {2, 5}, {7, 9}, {6, 10}}
{{1, 4}, {3, 8}, {5, 10}, {7, 9}, {2, 6}}
{{1, 4}, {3, 10}, {5, 8}, {7, 9}, {2, 6}}
{{1, 4}, {3, 10}, {2, 5}, {7, 9}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the right-dressed disjoint direct diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [67]:
AdcdrVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdcdrVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcdrVertex[[1]] = AdisjDirRight[[1]];
MultdcdrVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjDirRight[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjDirRight[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjDirRight[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjDirRight[[u, i, j]]];
   If[ AdisjDirRight[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjDirRight[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjDirRight[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjDirRight[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjDirRight[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirRight[[u, i, j]]];
   If[ AdisjDirRight[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjDirRight[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjDirRight[[u, i, j]] >= 5 || 
     AdisjDirRight[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjDirRight[[u, i, j]]];
   Temp[[4, i, j]] = AdisjDirRight[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdrVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdrVertex[[v]] = MultdcdrVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcdrVertex[[s]] = AdisjDirRight[[u]]; 
   MultdcdrVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent right-dressed disjoint direct contributions found."]];
 ]

Loop 72 completed and 22 inequivalent right-dressed disjoint direct\
 
>    contributions found.


In [76]:
For[u = 1, u <= 22, u++, Print["CombDirRight[[", u, "]]=", AdcdrVertex[[u]], ";"]];

CombDirRight[[1]]={{1, 2}, {3, 5}, {4, 8}, {7, 9}, {6, 10}};
CombDirRight[[2]]={{1, 2}, {3, 5}, {4, 10}, {7, 9}, {6, 8}};
CombDirRight[[3]]={{1, 2}, {3, 6}, {5, 8}, {7, 9}, {4, 10}};
CombDirRight[[4]]={{1, 2}, {3, 6}, {5, 10}, {7, 9}, {4, 8}};
CombDirRight[[5]]={{1, 3}, {2, 5}, {4, 8}, {7, 9}, {6, 10}};
CombDirRight[[6]]={{1, 3}, {2, 5}, {4, 10}, {7, 9}, {6, 8}};
CombDirRight[[7]]={{1, 3}, {2, 6}, {5, 8}, {7, 9}, {4, 10}};
CombDirRight[[8]]={{1, 3}, {2, 6}, {5, 10}, {7, 9}, {4, 8}};
CombDirRight[[9]]={{1, 3}, {2, 8}, {4, 5}, {7, 9}, {6, 10}};
CombDirRight[[10]]={{1, 3}, {2, 8}, {5, 10}, {7, 9}, {4, 6}};
CombDirRight[[11]]={{1, 3}, {2, 10}, {5, 8}, {7, 9}, {4, 6}};
CombDirRight[[12]]={{1, 3}, {2, 10}, {4, 5}, {7, 9}, {6, 8}};
CombDirRight[[13]]={{1, 5}, {3, 4}, {2, 8}, {7, 9}, {6, 10}};
CombDirRight[[14]]={{1, 5}, {3, 4}, {2, 10}, {7, 9}, {6, 8}};
CombDirRight[[15]]={{1, 5}, {3, 6}, {2, 8}, {7, 9}, {4, 10}};
CombDirRight[[16]]={{1, 5}, {3, 6}, {2, 10}, {7, 9}, {4, 8}};
CombDirRight[[17]

In [77]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdcdrVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=4;
GGFMult[[6]]=4;
GGFMult[[7]]=4;
GGFMult[[8]]=4;
GGFMult[[9]]=4;
GGFMult[[10]]=4;
GGFMult[[11]]=4;
GGFMult[[12]]=4;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=4;
GGFMult[[16]]=4;
GGFMult[[17]]=4;
GGFMult[[18]]=2;
GGFMult[[19]]=2;
GGFMult[[20]]=4;
GGFMult[[21]]=4;
GGFMult[[22]]=4;


There are $22$ second-order right-dressed disjoint direct diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [78]:
Sum[MultdcdrVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint direct diagrams with left-and-right-dressed single-particle propagators</font>

Direct diagrams with dressed 1-body propagator on the left and on the right are processed. Their initial number is $48$ in total.

In [79]:
For[u = 1, u <= 48, u++, Print[AdisjDirect[[u]]]];

{{1, 2}, {3, 7}, {5, 8}, {4, 9}, {6, 10}}
{{1, 2}, {3, 7}, {5, 10}, {4, 9}, {6, 8}}
{{1, 2}, {3, 8}, {5, 7}, {6, 9}, {4, 10}}
{{1, 2}, {3, 8}, {5, 9}, {6, 7}, {4, 10}}
{{1, 2}, {3, 9}, {5, 8}, {4, 7}, {6, 10}}
{{1, 2}, {3, 9}, {5, 10}, {4, 7}, {6, 8}}
{{1, 2}, {3, 10}, {5, 7}, {6, 9}, {4, 8}}
{{1, 2}, {3, 10}, {5, 9}, {6, 7}, {4, 8}}
{{1, 3}, {2, 7}, {5, 8}, {4, 9}, {6, 10}}
{{1, 3}, {2, 7}, {5, 10}, {4, 9}, {6, 8}}
{{1, 3}, {2, 8}, {5, 7}, {6, 9}, {4, 10}}
{{1, 3}, {2, 8}, {5, 9}, {6, 7}, {4, 10}}
{{1, 3}, {2, 9}, {5, 8}, {4, 7}, {6, 10}}
{{1, 3}, {2, 9}, {5, 10}, {4, 7}, {6, 8}}
{{1, 3}, {2, 10}, {5, 7}, {6, 9}, {4, 8}}
{{1, 3}, {2, 10}, {5, 9}, {6, 7}, {4, 8}}
{{1, 4}, {3, 7}, {5, 8}, {2, 9}, {6, 10}}
{{1, 4}, {3, 7}, {5, 10}, {2, 9}, {6, 8}}
{{1, 4}, {3, 8}, {5, 7}, {6, 9}, {2, 10}}
{{1, 4}, {3, 8}, {5, 9}, {6, 7}, {2, 10}}
{{1, 4}, {3, 9}, {5, 8}, {2, 7}, {6, 10}}
{{1, 4}, {3, 9}, {5, 10}, {2, 7}, {6, 8}}
{{1, 4}, {3, 10}, {5, 7}, {6, 9}, {2, 8}}
{{1, 4}, {3, 10}, {5, 9}, {6, 7}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the left-and-right-dressed disjoint direct diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [80]:
AdcdVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcdVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcdVertex[[1]] = AdisjDirect[[1]];
MultdcdVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjDirect[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjDirect[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjDirect[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjDirect[[u, i, j]]];
   If[ AdisjDirect[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjDirect[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjDirect[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjDirect[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjDirect[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjDirect[[u, i, j]]];
   If[ AdisjDirect[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjDirect[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjDirect[[u, i, j]] >= 5 || AdisjDirect[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjDirect[[u, i, j]]];
   Temp[[4, i, j]] = AdisjDirect[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcdVertex[[v]] = MultdcdVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcdVertex[[s]] = AdisjDirect[[u]]; 
   MultdcdVertex[[s]] = 1;];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent left-and-right-dressed disjoint direct contributions found."]];
 ]

Loop 48 completed and 16 inequivalent left-and-right-dressed disjoint direct\
 
>    contributions found.


In [89]:
For[u = 1, u <= 16, u++, Print["CombDir[[", u, "]]=", AdcdVertex[[u]], ";"]];

CombDir[[1]]={{1, 2}, {3, 7}, {5, 8}, {4, 9}, {6, 10}};
CombDir[[2]]={{1, 2}, {3, 7}, {5, 10}, {4, 9}, {6, 8}};
CombDir[[3]]={{1, 2}, {3, 8}, {5, 7}, {6, 9}, {4, 10}};
CombDir[[4]]={{1, 2}, {3, 8}, {5, 9}, {6, 7}, {4, 10}};
CombDir[[5]]={{1, 3}, {2, 7}, {5, 8}, {4, 9}, {6, 10}};
CombDir[[6]]={{1, 3}, {2, 7}, {5, 10}, {4, 9}, {6, 8}};
CombDir[[7]]={{1, 3}, {2, 8}, {5, 7}, {6, 9}, {4, 10}};
CombDir[[8]]={{1, 3}, {2, 8}, {5, 9}, {6, 7}, {4, 10}};
CombDir[[9]]={{1, 3}, {2, 9}, {5, 8}, {4, 7}, {6, 10}};
CombDir[[10]]={{1, 3}, {2, 9}, {5, 10}, {4, 7}, {6, 8}};
CombDir[[11]]={{1, 3}, {2, 10}, {5, 7}, {6, 9}, {4, 8}};
CombDir[[12]]={{1, 3}, {2, 10}, {5, 9}, {6, 7}, {4, 8}};
CombDir[[13]]={{1, 7}, {3, 4}, {5, 8}, {2, 9}, {6, 10}};
CombDir[[14]]={{1, 7}, {3, 4}, {5, 10}, {2, 9}, {6, 8}};
CombDir[[15]]={{1, 8}, {3, 4}, {5, 7}, {6, 9}, {2, 10}};
CombDir[[16]]={{1, 8}, {3, 4}, {5, 9}, {6, 7}, {2, 10}};


In [90]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdcdVertex[[u]], ";"]];

GGFMult[[1]]=2;
GGFMult[[2]]=2;
GGFMult[[3]]=2;
GGFMult[[4]]=2;
GGFMult[[5]]=4;
GGFMult[[6]]=4;
GGFMult[[7]]=4;
GGFMult[[8]]=4;
GGFMult[[9]]=4;
GGFMult[[10]]=4;
GGFMult[[11]]=4;
GGFMult[[12]]=4;
GGFMult[[13]]=2;
GGFMult[[14]]=2;
GGFMult[[15]]=2;
GGFMult[[16]]=2;


There are $16$ second-order left-and-right-dressed disjoint direct diagrams. The multiplicity check is fulfilled.

In [91]:
Sum[MultdcdVertex[[u]], {u, 1, 16}]

48

 ## <font color=#FA8072>Disjoint exchange diagrams with dressed single-particle propagator above</font>

Direct diagrams with unperturbed 1-body propagator below are processed. Their initial number is $72$ in total.

In [92]:
For[u = 1, u <= 72, u++, Print[AdisjExchAbove[[u]]]];

{{1, 2}, {3, 5}, {4, 7}, {6, 10}, {8, 9}}
{{1, 2}, {3, 5}, {4, 10}, {6, 7}, {8, 9}}
{{1, 2}, {3, 6}, {5, 7}, {4, 10}, {8, 9}}
{{1, 2}, {3, 6}, {5, 10}, {4, 7}, {8, 9}}
{{1, 2}, {3, 7}, {4, 5}, {6, 10}, {8, 9}}
{{1, 2}, {3, 7}, {5, 10}, {4, 6}, {8, 9}}
{{1, 2}, {3, 10}, {5, 7}, {4, 6}, {8, 9}}
{{1, 2}, {3, 10}, {4, 5}, {6, 7}, {8, 9}}
{{1, 3}, {2, 5}, {4, 7}, {6, 10}, {8, 9}}
{{1, 3}, {2, 5}, {4, 10}, {6, 7}, {8, 9}}
{{1, 3}, {2, 6}, {5, 7}, {4, 10}, {8, 9}}
{{1, 3}, {2, 6}, {5, 10}, {4, 7}, {8, 9}}
{{1, 3}, {2, 7}, {4, 5}, {6, 10}, {8, 9}}
{{1, 3}, {2, 7}, {5, 10}, {4, 6}, {8, 9}}
{{1, 3}, {2, 10}, {5, 7}, {4, 6}, {8, 9}}
{{1, 3}, {2, 10}, {4, 5}, {6, 7}, {8, 9}}
{{1, 4}, {3, 5}, {2, 7}, {6, 10}, {8, 9}}
{{1, 4}, {3, 5}, {2, 10}, {6, 7}, {8, 9}}
{{1, 4}, {3, 6}, {5, 7}, {2, 10}, {8, 9}}
{{1, 4}, {3, 6}, {5, 10}, {2, 7}, {8, 9}}
{{1, 4}, {3, 7}, {2, 5}, {6, 10}, {8, 9}}
{{1, 4}, {3, 7}, {5, 10}, {2, 6}, {8, 9}}
{{1, 4}, {3, 10}, {5, 7}, {2, 6}, {8, 9}}
{{1, 4}, {3, 10}, {2, 5}, {6, 7}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the above-dressed disjoint exchange diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [94]:
AdceaVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdceaVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdceaVertex[[1]] = AdisjExchAbove[[1]];
MultdceaVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjExchAbove[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjExchAbove[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjExchAbove[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[ AdisjExchAbove[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjExchAbove[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjExchAbove[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjExchAbove[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjExchAbove[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchAbove[[u, i, j]]];
   If[ AdisjExchAbove[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjExchAbove[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjExchAbove[[u, i, j]] >= 5 || 
     AdisjExchAbove[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjExchAbove[[u, i, j]]];
   Temp[[4, i, j]] = AdisjExchAbove[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdceaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceaVertex[[v]] = MultdceaVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdceaVertex[[s]] = AdisjExchAbove[[u]]; 
   MultdceaVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-dressed disjoint exchange contributions found."]];
 ]

Loop 72 completed and 22 inequivalent above-dressed disjoint exchange\
 
>    contributions found.


In [103]:
For[u = 1, u <= 22, u++, Print["CombExcAbove[[", u, "]]=", AdceaVertex[[u]]]];

CombExcAbove[[1]]={{1, 2}, {3, 5}, {4, 7}, {6, 10}, {8, 9}}
CombExcAbove[[2]]={{1, 2}, {3, 5}, {4, 10}, {6, 7}, {8, 9}}
CombExcAbove[[3]]={{1, 2}, {3, 6}, {5, 7}, {4, 10}, {8, 9}}
CombExcAbove[[4]]={{1, 2}, {3, 6}, {5, 10}, {4, 7}, {8, 9}}
CombExcAbove[[5]]={{1, 3}, {2, 5}, {4, 7}, {6, 10}, {8, 9}}
CombExcAbove[[6]]={{1, 3}, {2, 5}, {4, 10}, {6, 7}, {8, 9}}
CombExcAbove[[7]]={{1, 3}, {2, 6}, {5, 7}, {4, 10}, {8, 9}}
CombExcAbove[[8]]={{1, 3}, {2, 6}, {5, 10}, {4, 7}, {8, 9}}
CombExcAbove[[9]]={{1, 3}, {2, 7}, {4, 5}, {6, 10}, {8, 9}}
CombExcAbove[[10]]={{1, 3}, {2, 7}, {5, 10}, {4, 6}, {8, 9}}
CombExcAbove[[11]]={{1, 3}, {2, 10}, {5, 7}, {4, 6}, {8, 9}}
CombExcAbove[[12]]={{1, 3}, {2, 10}, {4, 5}, {6, 7}, {8, 9}}
CombExcAbove[[13]]={{1, 5}, {3, 4}, {2, 7}, {6, 10}, {8, 9}}
CombExcAbove[[14]]={{1, 5}, {3, 4}, {2, 10}, {6, 7}, {8, 9}}
CombExcAbove[[15]]={{1, 5}, {3, 6}, {2, 7}, {4, 10}, {8, 9}}
CombExcAbove[[16]]={{1, 5}, {3, 6}, {2, 10}, {4, 7}, {8, 9}}
CombExcAbove[[17]]={{1, 5}, {3, 7

In [104]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdceaVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=4
GGFMult[[16]]=4
GGFMult[[17]]=4
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=4
GGFMult[[21]]=4
GGFMult[[22]]=4


There are $22$ second-order above-dressed disjoint exchange diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [105]:
Sum[MultdceaVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint exchange diagrams with dressed single-particle propagator below</font>

Direct diagrams with unperturbed 1-body propagator above are processed. Their initial number is $72$ in total.

In [106]:
For[u = 1, u <= 72, u++, Print[AdisjExchBelow[[u]]]];

{{1, 2}, {3, 5}, {4, 8}, {7, 10}, {6, 9}}
{{1, 2}, {3, 5}, {4, 9}, {7, 10}, {6, 8}}
{{1, 2}, {3, 6}, {5, 8}, {7, 10}, {4, 9}}
{{1, 2}, {3, 6}, {5, 9}, {7, 10}, {4, 8}}
{{1, 2}, {3, 8}, {4, 5}, {7, 10}, {6, 9}}
{{1, 2}, {3, 8}, {5, 9}, {7, 10}, {4, 6}}
{{1, 2}, {3, 9}, {5, 8}, {7, 10}, {4, 6}}
{{1, 2}, {3, 9}, {4, 5}, {7, 10}, {6, 8}}
{{1, 3}, {2, 5}, {4, 8}, {7, 10}, {6, 9}}
{{1, 3}, {2, 5}, {4, 9}, {7, 10}, {6, 8}}
{{1, 3}, {2, 6}, {5, 8}, {7, 10}, {4, 9}}
{{1, 3}, {2, 6}, {5, 9}, {7, 10}, {4, 8}}
{{1, 3}, {2, 8}, {4, 5}, {7, 10}, {6, 9}}
{{1, 3}, {2, 8}, {5, 9}, {7, 10}, {4, 6}}
{{1, 3}, {2, 9}, {5, 8}, {7, 10}, {4, 6}}
{{1, 3}, {2, 9}, {4, 5}, {7, 10}, {6, 8}}
{{1, 4}, {3, 5}, {2, 8}, {7, 10}, {6, 9}}
{{1, 4}, {3, 5}, {2, 9}, {7, 10}, {6, 8}}
{{1, 4}, {3, 6}, {5, 8}, {7, 10}, {2, 9}}
{{1, 4}, {3, 6}, {5, 9}, {7, 10}, {2, 8}}
{{1, 4}, {3, 8}, {2, 5}, {7, 10}, {6, 9}}
{{1, 4}, {3, 8}, {5, 9}, {7, 10}, {2, 6}}
{{1, 4}, {3, 9}, {5, 8}, {7, 10}, {2, 6}}
{{1, 4}, {3, 9}, {2, 5}, {7, 10}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the below-dressed disjoint exchange diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [107]:
AdcebVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdcebVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcebVertex[[1]] = AdisjExchBelow[[1]];
MultdcebVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjExchBelow[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjExchBelow[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjExchBelow[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[ AdisjExchBelow[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjExchBelow[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjExchBelow[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjExchBelow[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjExchBelow[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchBelow[[u, i, j]]];
   If[ AdisjExchBelow[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjExchBelow[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjExchBelow[[u, i, j]] >= 5 || 
     AdisjExchBelow[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjExchBelow[[u, i, j]]];
   Temp[[4, i, j]] = AdisjExchBelow[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcebVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcebVertex[[v]] = MultdcebVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcebVertex[[s]] = AdisjExchBelow[[u]]; 
   MultdcebVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent below-dressed disjoint exchange contributions found."]];
 ]

Loop 72 completed and 22 inequivalent below-dressed disjoint exchange\
 
>    contributions found.


In [116]:
For[u = 1, u <= 22, u++, Print["CombExcBelow[[", u, "]]=", AdcebVertex[[u]]]];

CombExcBelow[[1]]={{1, 2}, {3, 5}, {4, 8}, {7, 10}, {6, 9}}
CombExcBelow[[2]]={{1, 2}, {3, 5}, {4, 9}, {7, 10}, {6, 8}}
CombExcBelow[[3]]={{1, 2}, {3, 6}, {5, 8}, {7, 10}, {4, 9}}
CombExcBelow[[4]]={{1, 2}, {3, 6}, {5, 9}, {7, 10}, {4, 8}}
CombExcBelow[[5]]={{1, 3}, {2, 5}, {4, 8}, {7, 10}, {6, 9}}
CombExcBelow[[6]]={{1, 3}, {2, 5}, {4, 9}, {7, 10}, {6, 8}}
CombExcBelow[[7]]={{1, 3}, {2, 6}, {5, 8}, {7, 10}, {4, 9}}
CombExcBelow[[8]]={{1, 3}, {2, 6}, {5, 9}, {7, 10}, {4, 8}}
CombExcBelow[[9]]={{1, 3}, {2, 8}, {4, 5}, {7, 10}, {6, 9}}
CombExcBelow[[10]]={{1, 3}, {2, 8}, {5, 9}, {7, 10}, {4, 6}}
CombExcBelow[[11]]={{1, 3}, {2, 9}, {5, 8}, {7, 10}, {4, 6}}
CombExcBelow[[12]]={{1, 3}, {2, 9}, {4, 5}, {7, 10}, {6, 8}}
CombExcBelow[[13]]={{1, 5}, {3, 4}, {2, 8}, {7, 10}, {6, 9}}
CombExcBelow[[14]]={{1, 5}, {3, 4}, {2, 9}, {7, 10}, {6, 8}}
CombExcBelow[[15]]={{1, 5}, {3, 6}, {2, 8}, {7, 10}, {4, 9}}
CombExcBelow[[16]]={{1, 5}, {3, 6}, {2, 9}, {7, 10}, {4, 8}}
CombExcBelow[[17]]={{1, 5}, {3, 8

In [117]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdcebVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=4
GGFMult[[16]]=4
GGFMult[[17]]=4
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=4
GGFMult[[21]]=4
GGFMult[[22]]=4


There are $22$ second-order below-dressed disjoint exchange diagrams. The multiplicity check is fulfilled.

In [118]:
Sum[MultdcebVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint exchange diagrams with above-and-below-dressed single-particle propagators</font>

Direct diagrams with dressed 1-body propagator above and below are processed. Their initial number is $48$ in total.

In [119]:
For[u = 1, u <= 48, u++, Print[AdisjExchange[[u]]]];

{{1, 2}, {3, 7}, {5, 8}, {4, 10}, {6, 9}}
{{1, 2}, {3, 7}, {5, 9}, {4, 10}, {6, 8}}
{{1, 2}, {3, 8}, {5, 7}, {6, 10}, {4, 9}}
{{1, 2}, {3, 8}, {5, 10}, {6, 7}, {4, 9}}
{{1, 2}, {3, 9}, {5, 7}, {6, 10}, {4, 8}}
{{1, 2}, {3, 9}, {5, 10}, {6, 7}, {4, 8}}
{{1, 2}, {3, 10}, {5, 8}, {4, 7}, {6, 9}}
{{1, 2}, {3, 10}, {5, 9}, {4, 7}, {6, 8}}
{{1, 3}, {2, 7}, {5, 8}, {4, 10}, {6, 9}}
{{1, 3}, {2, 7}, {5, 9}, {4, 10}, {6, 8}}
{{1, 3}, {2, 8}, {5, 7}, {6, 10}, {4, 9}}
{{1, 3}, {2, 8}, {5, 10}, {6, 7}, {4, 9}}
{{1, 3}, {2, 9}, {5, 7}, {6, 10}, {4, 8}}
{{1, 3}, {2, 9}, {5, 10}, {6, 7}, {4, 8}}
{{1, 3}, {2, 10}, {5, 8}, {4, 7}, {6, 9}}
{{1, 3}, {2, 10}, {5, 9}, {4, 7}, {6, 8}}
{{1, 4}, {3, 7}, {5, 8}, {2, 10}, {6, 9}}
{{1, 4}, {3, 7}, {5, 9}, {2, 10}, {6, 8}}
{{1, 4}, {3, 8}, {5, 7}, {6, 10}, {2, 9}}
{{1, 4}, {3, 8}, {5, 10}, {6, 7}, {2, 9}}
{{1, 4}, {3, 9}, {5, 7}, {6, 10}, {2, 8}}
{{1, 4}, {3, 9}, {5, 10}, {6, 7}, {2, 8}}
{{1, 4}, {3, 10}, {5, 8}, {2, 7}, {6, 9}}
{{1, 4}, {3, 10}, {5, 9}, {2, 7}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the above-and-below-dressed disjoint exchange diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [138]:
AdceVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdceVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdceVertex[[1]] = AdisjExchange[[1]];
MultdceVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjExchange[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjExchange[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjExchange[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjExchange[[u, i, j]]];
   If[ AdisjExchange[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjExchange[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjExchange[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjExchange[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjExchange[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjExchange[[u, i, j]]];
   If[ AdisjExchange[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjExchange[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjExchange[[u, i, j]] >= 5 || 
     AdisjExchange[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjExchange[[u, i, j]]];
   Temp[[4, i, j]] = AdisjExchange[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdceVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdceVertex[[v]] = MultdceVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdceVertex[[s]] = AdisjExchange[[u]]; 
   MultdceVertex[[s]] = 1;];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent above-and-below-dressed disjoint exchange contributions found."]];
 ]

Loop 48 completed and 16 inequivalent above-and-below-dressed disjoint\
 
>    exchange contributions found.


In [147]:
For[u = 1, u <= 16, u++, Print["CombExc[[", u, "]]=", AdceVertex[[u]]]];

CombExc[[1]]={{1, 2}, {3, 7}, {5, 8}, {4, 10}, {6, 9}}
CombExc[[2]]={{1, 2}, {3, 7}, {5, 9}, {4, 10}, {6, 8}}
CombExc[[3]]={{1, 2}, {3, 8}, {5, 7}, {6, 10}, {4, 9}}
CombExc[[4]]={{1, 2}, {3, 8}, {5, 10}, {6, 7}, {4, 9}}
CombExc[[5]]={{1, 3}, {2, 7}, {5, 8}, {4, 10}, {6, 9}}
CombExc[[6]]={{1, 3}, {2, 7}, {5, 9}, {4, 10}, {6, 8}}
CombExc[[7]]={{1, 3}, {2, 8}, {5, 7}, {6, 10}, {4, 9}}
CombExc[[8]]={{1, 3}, {2, 8}, {5, 10}, {6, 7}, {4, 9}}
CombExc[[9]]={{1, 3}, {2, 9}, {5, 7}, {6, 10}, {4, 8}}
CombExc[[10]]={{1, 3}, {2, 9}, {5, 10}, {6, 7}, {4, 8}}
CombExc[[11]]={{1, 3}, {2, 10}, {5, 8}, {4, 7}, {6, 9}}
CombExc[[12]]={{1, 3}, {2, 10}, {5, 9}, {4, 7}, {6, 8}}
CombExc[[13]]={{1, 7}, {3, 4}, {5, 8}, {2, 10}, {6, 9}}
CombExc[[14]]={{1, 7}, {3, 4}, {5, 9}, {2, 10}, {6, 8}}
CombExc[[15]]={{1, 8}, {3, 4}, {5, 7}, {6, 10}, {2, 9}}
CombExc[[16]]={{1, 8}, {3, 4}, {5, 10}, {6, 7}, {2, 9}}


In [148]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdceVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=2
GGFMult[[16]]=2


There are $16$ second-order above-and-below-dressed disjoint exchange diagrams. The multiplicity check is fulfilled.

In [149]:
Sum[MultdceVertex[[u]], {u, 1, 16}]

48

 ## <font color=#FA8072>Disjoint Bogoliubov diagrams with dressed single-particle propagator in the antidiagonal</font>

Bogoliubov diagrams with unperturbed 1-body propagator on the diagonal are processed. Their initial number is $72$ in total.

In [150]:
For[u = 1, u <= 72, u++, Print[AdisjBogoAntidiag[[u]]]];

{{1, 2}, {3, 5}, {4, 9}, {7, 8}, {6, 10}}
{{1, 2}, {3, 5}, {4, 10}, {7, 8}, {6, 9}}
{{1, 2}, {3, 6}, {5, 9}, {7, 8}, {4, 10}}
{{1, 2}, {3, 6}, {5, 10}, {7, 8}, {4, 9}}
{{1, 2}, {3, 9}, {4, 5}, {7, 8}, {6, 10}}
{{1, 2}, {3, 9}, {5, 10}, {7, 8}, {4, 6}}
{{1, 2}, {3, 10}, {5, 9}, {7, 8}, {4, 6}}
{{1, 2}, {3, 10}, {4, 5}, {7, 8}, {6, 9}}
{{1, 3}, {2, 5}, {4, 9}, {7, 8}, {6, 10}}
{{1, 3}, {2, 5}, {4, 10}, {7, 8}, {6, 9}}
{{1, 3}, {2, 6}, {5, 9}, {7, 8}, {4, 10}}
{{1, 3}, {2, 6}, {5, 10}, {7, 8}, {4, 9}}
{{1, 3}, {2, 9}, {4, 5}, {7, 8}, {6, 10}}
{{1, 3}, {2, 9}, {5, 10}, {7, 8}, {4, 6}}
{{1, 3}, {2, 10}, {5, 9}, {7, 8}, {4, 6}}
{{1, 3}, {2, 10}, {4, 5}, {7, 8}, {6, 9}}
{{1, 4}, {3, 5}, {2, 9}, {7, 8}, {6, 10}}
{{1, 4}, {3, 5}, {2, 10}, {7, 8}, {6, 9}}
{{1, 4}, {3, 6}, {5, 9}, {7, 8}, {2, 10}}
{{1, 4}, {3, 6}, {5, 10}, {7, 8}, {2, 9}}
{{1, 4}, {3, 9}, {2, 5}, {7, 8}, {6, 10}}
{{1, 4}, {3, 9}, {5, 10}, {7, 8}, {2, 6}}
{{1, 4}, {3, 10}, {5, 9}, {7, 8}, {2, 6}}
{{1, 4}, {3, 10}, {2, 5}, {7, 8}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the antidiagonally-dressed disjoint Bogoliubov diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [160]:
AdcbaVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdcbaVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcbaVertex[[1]] = AdisjBogoAntidiag[[1]];
MultdcbaVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjBogoAntidiag[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[ AdisjBogoAntidiag[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjBogoAntidiag[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjBogoAntidiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   If[ AdisjBogoAntidiag[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjBogoAntidiag[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjBogoAntidiag[[u, i, j]] >= 5 || 
     AdisjBogoAntidiag[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjBogoAntidiag[[u, i, j]]];
   Temp[[4, i, j]] = AdisjBogoAntidiag[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbaVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbaVertex[[v]] = MultdcbaVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; 
   AdcbaVertex[[s]] = AdisjBogoAntidiag[[u]]; 
   MultdcbaVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent antidiagonally-dressed disjoint Bogoliubov contributions found."]];
 ]

Loop 72 completed and 22 inequivalent antidiagonally-dressed disjoint\
 
>    Bogoliubov contributions found.


In [169]:
For[u = 1, u <= 22, u++, Print["CombBogAntidiag[[", u, "]]=", AdcbaVertex[[u]]]];

CombBogAntidiag[[1]]={{1, 2}, {3, 5}, {4, 9}, {7, 8}, {6, 10}}
CombBogAntidiag[[2]]={{1, 2}, {3, 5}, {4, 10}, {7, 8}, {6, 9}}
CombBogAntidiag[[3]]={{1, 2}, {3, 6}, {5, 9}, {7, 8}, {4, 10}}
CombBogAntidiag[[4]]={{1, 2}, {3, 6}, {5, 10}, {7, 8}, {4, 9}}
CombBogAntidiag[[5]]={{1, 3}, {2, 5}, {4, 9}, {7, 8}, {6, 10}}
CombBogAntidiag[[6]]={{1, 3}, {2, 5}, {4, 10}, {7, 8}, {6, 9}}
CombBogAntidiag[[7]]={{1, 3}, {2, 6}, {5, 9}, {7, 8}, {4, 10}}
CombBogAntidiag[[8]]={{1, 3}, {2, 6}, {5, 10}, {7, 8}, {4, 9}}
CombBogAntidiag[[9]]={{1, 3}, {2, 9}, {4, 5}, {7, 8}, {6, 10}}
CombBogAntidiag[[10]]={{1, 3}, {2, 9}, {5, 10}, {7, 8}, {4, 6}}
CombBogAntidiag[[11]]={{1, 3}, {2, 10}, {5, 9}, {7, 8}, {4, 6}}
CombBogAntidiag[[12]]={{1, 3}, {2, 10}, {4, 5}, {7, 8}, {6, 9}}
CombBogAntidiag[[13]]={{1, 5}, {3, 4}, {2, 9}, {7, 8}, {6, 10}}
CombBogAntidiag[[14]]={{1, 5}, {3, 4}, {2, 10}, {7, 8}, {6, 9}}
CombBogAntidiag[[15]]={{1, 5}, {3, 6}, {2, 9}, {7, 8}, {4, 10}}
CombBogAntidiag[[16]]={{1, 5}, {3, 6}, {2, 10}, {

In [170]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdcbaVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=4
GGFMult[[16]]=4
GGFMult[[17]]=4
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=4
GGFMult[[21]]=4
GGFMult[[22]]=4


There are $22$ second-order antidiagonally-dressed disjoint Bogoliubov diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [171]:
Sum[MultdcbaVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint Bogoliubov diagrams with dressed single-particle propagator in the diagonal</font>

Bogoliubov diagrams with unperturbed 1-body propagator on the antidiagonal are processed. Their initial number is $72$ in total.

In [172]:
For[u = 1, u <= 72, u++, Print[AdisjBogoDiag[[u]]]];

{{1, 2}, {3, 5}, {4, 7}, {6, 8}, {9, 10}}
{{1, 2}, {3, 5}, {4, 8}, {6, 7}, {9, 10}}
{{1, 2}, {3, 6}, {5, 7}, {4, 8}, {9, 10}}
{{1, 2}, {3, 6}, {5, 8}, {4, 7}, {9, 10}}
{{1, 2}, {3, 7}, {4, 5}, {6, 8}, {9, 10}}
{{1, 2}, {3, 7}, {5, 8}, {4, 6}, {9, 10}}
{{1, 2}, {3, 8}, {5, 7}, {4, 6}, {9, 10}}
{{1, 2}, {3, 8}, {4, 5}, {6, 7}, {9, 10}}
{{1, 3}, {2, 5}, {4, 7}, {6, 8}, {9, 10}}
{{1, 3}, {2, 5}, {4, 8}, {6, 7}, {9, 10}}
{{1, 3}, {2, 6}, {5, 7}, {4, 8}, {9, 10}}
{{1, 3}, {2, 6}, {5, 8}, {4, 7}, {9, 10}}
{{1, 3}, {2, 7}, {4, 5}, {6, 8}, {9, 10}}
{{1, 3}, {2, 7}, {5, 8}, {4, 6}, {9, 10}}
{{1, 3}, {2, 8}, {5, 7}, {4, 6}, {9, 10}}
{{1, 3}, {2, 8}, {4, 5}, {6, 7}, {9, 10}}
{{1, 4}, {3, 5}, {2, 7}, {6, 8}, {9, 10}}
{{1, 4}, {3, 5}, {2, 8}, {6, 7}, {9, 10}}
{{1, 4}, {3, 6}, {5, 7}, {2, 8}, {9, 10}}
{{1, 4}, {3, 6}, {5, 8}, {2, 7}, {9, 10}}
{{1, 4}, {3, 7}, {2, 5}, {6, 8}, {9, 10}}
{{1, 4}, {3, 7}, {5, 8}, {2, 6}, {9, 10}}
{{1, 4}, {3, 8}, {5, 7}, {2, 6}, {9, 10}}
{{1, 4}, {3, 8}, {2, 5}, {6, 7}, {

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the diagonally-dressed disjoint Bogoliubov diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [182]:
AdcbdVertex = Table[0, {i, 1, 72}, {j, 1, 5}, {k, 1, 2}];
MultdcbdVertex = Table[0, {i, 1, 72}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcbdVertex[[1]] = AdisjBogoDiag[[1]];
MultdcbdVertex[[1]] = 1;
For[u = 1, u <= 72, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjBogoDiag[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjBogoDiag[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjBogoDiag[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[ AdisjBogoDiag[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjBogoDiag[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjBogoDiag[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjBogoDiag[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjBogoDiag[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoDiag[[u, i, j]]];
   If[ AdisjBogoDiag[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjBogoDiag[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjBogoDiag[[u, i, j]] >= 5 || 
     AdisjBogoDiag[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjBogoDiag[[u, i, j]]];
   Temp[[4, i, j]] = AdisjBogoDiag[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbdVertex[[v]] = MultdcbdVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcbdVertex[[s]] = AdisjBogoDiag[[u]]; 
   MultdcbdVertex[[s]] = 1;];
  ];
 If[u == 72, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-dressed disjoint Bogoliubov contributions found."]];
 ]

Loop 72 completed and 22 inequivalent diagonally-dressed disjoint Bogoliubov\
 
>    contributions found.


In [191]:
For[u = 1, u <= 22, u++, Print["CombBogDiag[[", u, "]]=", AdcbdVertex[[u]]]];

CombBogDiag[[1]]={{1, 2}, {3, 5}, {4, 7}, {6, 8}, {9, 10}}
CombBogDiag[[2]]={{1, 2}, {3, 5}, {4, 8}, {6, 7}, {9, 10}}
CombBogDiag[[3]]={{1, 2}, {3, 6}, {5, 7}, {4, 8}, {9, 10}}
CombBogDiag[[4]]={{1, 2}, {3, 6}, {5, 8}, {4, 7}, {9, 10}}
CombBogDiag[[5]]={{1, 3}, {2, 5}, {4, 7}, {6, 8}, {9, 10}}
CombBogDiag[[6]]={{1, 3}, {2, 5}, {4, 8}, {6, 7}, {9, 10}}
CombBogDiag[[7]]={{1, 3}, {2, 6}, {5, 7}, {4, 8}, {9, 10}}
CombBogDiag[[8]]={{1, 3}, {2, 6}, {5, 8}, {4, 7}, {9, 10}}
CombBogDiag[[9]]={{1, 3}, {2, 7}, {4, 5}, {6, 8}, {9, 10}}
CombBogDiag[[10]]={{1, 3}, {2, 7}, {5, 8}, {4, 6}, {9, 10}}
CombBogDiag[[11]]={{1, 3}, {2, 8}, {5, 7}, {4, 6}, {9, 10}}
CombBogDiag[[12]]={{1, 3}, {2, 8}, {4, 5}, {6, 7}, {9, 10}}
CombBogDiag[[13]]={{1, 5}, {3, 4}, {2, 7}, {6, 8}, {9, 10}}
CombBogDiag[[14]]={{1, 5}, {3, 4}, {2, 8}, {6, 7}, {9, 10}}
CombBogDiag[[15]]={{1, 5}, {3, 6}, {2, 7}, {4, 8}, {9, 10}}
CombBogDiag[[16]]={{1, 5}, {3, 6}, {2, 8}, {4, 7}, {9, 10}}
CombBogDiag[[17]]={{1, 5}, {3, 7}, {2, 6}, {4, 8}

In [192]:
For[u = 1, u <= 22, u++, Print["GGFMult[[", u, "]]=", MultdcbdVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=4
GGFMult[[16]]=4
GGFMult[[17]]=4
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=4
GGFMult[[21]]=4
GGFMult[[22]]=4


There are $22$ second-order diagonally-dressed disjoint Bogoliubov diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [193]:
Sum[MultdcbdVertex[[u]], {u, 1, 22}]

72

 ## <font color=#FA8072>Disjoint Bogoliubov diagrams with diagonally-and-antidiagonally dressed single-particle propagators</font>

Bogoliubov diagrams with dressed 1-body propagator on the diagonal and on the antidiagonal are processed. Their initial number is $48$ in total.

In [194]:
For[u = 1, u <= 48, u++, Print[AdisjBogoliubov[[u]]]];

{{1, 2}, {3, 7}, {5, 9}, {4, 8}, {6, 10}}
{{1, 2}, {3, 7}, {5, 10}, {4, 8}, {6, 9}}
{{1, 2}, {3, 8}, {5, 9}, {4, 7}, {6, 10}}
{{1, 2}, {3, 8}, {5, 10}, {4, 7}, {6, 9}}
{{1, 2}, {3, 9}, {5, 7}, {6, 8}, {4, 10}}
{{1, 2}, {3, 9}, {5, 8}, {6, 7}, {4, 10}}
{{1, 2}, {3, 10}, {5, 7}, {6, 8}, {4, 9}}
{{1, 2}, {3, 10}, {5, 8}, {6, 7}, {4, 9}}
{{1, 3}, {2, 7}, {5, 9}, {4, 8}, {6, 10}}
{{1, 3}, {2, 7}, {5, 10}, {4, 8}, {6, 9}}
{{1, 3}, {2, 8}, {5, 9}, {4, 7}, {6, 10}}
{{1, 3}, {2, 8}, {5, 10}, {4, 7}, {6, 9}}
{{1, 3}, {2, 9}, {5, 7}, {6, 8}, {4, 10}}
{{1, 3}, {2, 9}, {5, 8}, {6, 7}, {4, 10}}
{{1, 3}, {2, 10}, {5, 7}, {6, 8}, {4, 9}}
{{1, 3}, {2, 10}, {5, 8}, {6, 7}, {4, 9}}
{{1, 4}, {3, 7}, {5, 9}, {2, 8}, {6, 10}}
{{1, 4}, {3, 7}, {5, 10}, {2, 8}, {6, 9}}
{{1, 4}, {3, 8}, {5, 9}, {2, 7}, {6, 10}}
{{1, 4}, {3, 8}, {5, 10}, {2, 7}, {6, 9}}
{{1, 4}, {3, 9}, {5, 7}, {6, 8}, {2, 10}}
{{1, 4}, {3, 9}, {5, 8}, {6, 7}, {2, 10}}
{{1, 4}, {3, 10}, {5, 7}, {6, 8}, {2, 9}}
{{1, 4}, {3, 10}, {5, 8}, {6, 7}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the antidiagonally-and-diagonally-dressed disjoint Bogoliubov diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [204]:
AdcbVertex = Table[0, {i, 1, 48}, {j, 1, 5}, {k, 1, 2}];
MultdcbVertex = Table[0, {i, 1, 48}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdcbVertex[[1]] = AdisjBogoliubov[[1]];
MultdcbVertex[[1]] = 1;
For[u = 1, u <= 48, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ AdisjBogoliubov[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ AdisjBogoliubov[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ AdisjBogoliubov[[u, i, j]] >= 3, 
    Temp[[1, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[ AdisjBogoliubov[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ AdisjBogoliubov[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ AdisjBogoliubov[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ AdisjBogoliubov[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ AdisjBogoliubov[[u, i, j]] >= 5, 
    Temp[[2, i, j]] = AdisjBogoliubov[[u, i, j]]];
   If[ AdisjBogoliubov[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ AdisjBogoliubov[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ AdisjBogoliubov[[u, i, j]] >= 5 || 
     AdisjBogoliubov[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = AdisjBogoliubov[[u, i, j]]];
   Temp[[4, i, j]] = AdisjBogoliubov[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdcbVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdcbVertex[[v]] = MultdcbVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdcbVertex[[s]] = AdisjBogoliubov[[u]]; 
   MultdcbVertex[[s]] = 1;];
  ];
 If[u == 48, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent diagonally-and-antidiagonally-dressed disjoint Bogoliubov contributions found."]];
 ]

Loop 48 completed and 16 inequivalent diagonally-and-antidiagonally-dressed\
 
>    disjoint Bogoliubov contributions found.


In [213]:
For[u = 1, u <= 16, u++, Print["CombBog[[", u, "]]=", AdcbVertex[[u]]]];

CombBog[[1]]={{1, 2}, {3, 7}, {5, 9}, {4, 8}, {6, 10}}
CombBog[[2]]={{1, 2}, {3, 7}, {5, 10}, {4, 8}, {6, 9}}
CombBog[[3]]={{1, 2}, {3, 9}, {5, 7}, {6, 8}, {4, 10}}
CombBog[[4]]={{1, 2}, {3, 9}, {5, 8}, {6, 7}, {4, 10}}
CombBog[[5]]={{1, 3}, {2, 7}, {5, 9}, {4, 8}, {6, 10}}
CombBog[[6]]={{1, 3}, {2, 7}, {5, 10}, {4, 8}, {6, 9}}
CombBog[[7]]={{1, 3}, {2, 8}, {5, 9}, {4, 7}, {6, 10}}
CombBog[[8]]={{1, 3}, {2, 8}, {5, 10}, {4, 7}, {6, 9}}
CombBog[[9]]={{1, 3}, {2, 9}, {5, 7}, {6, 8}, {4, 10}}
CombBog[[10]]={{1, 3}, {2, 9}, {5, 8}, {6, 7}, {4, 10}}
CombBog[[11]]={{1, 3}, {2, 10}, {5, 7}, {6, 8}, {4, 9}}
CombBog[[12]]={{1, 3}, {2, 10}, {5, 8}, {6, 7}, {4, 9}}
CombBog[[13]]={{1, 7}, {3, 4}, {5, 9}, {2, 8}, {6, 10}}
CombBog[[14]]={{1, 7}, {3, 4}, {5, 10}, {2, 8}, {6, 9}}
CombBog[[15]]={{1, 9}, {3, 4}, {5, 7}, {6, 8}, {2, 10}}
CombBog[[16]]={{1, 9}, {3, 4}, {5, 8}, {6, 7}, {2, 10}}


In [214]:
For[u = 1, u <= 16, u++, Print["GGFMult[[", u, "]]=", MultdcbVertex[[u]]]];

GGFMult[[1]]=2
GGFMult[[2]]=2
GGFMult[[3]]=2
GGFMult[[4]]=2
GGFMult[[5]]=4
GGFMult[[6]]=4
GGFMult[[7]]=4
GGFMult[[8]]=4
GGFMult[[9]]=4
GGFMult[[10]]=4
GGFMult[[11]]=4
GGFMult[[12]]=4
GGFMult[[13]]=2
GGFMult[[14]]=2
GGFMult[[15]]=2
GGFMult[[16]]=2


There are $16$ second-order diagonally-and-antidiagonally-dressed disjoint Bogoliubov diagrams. The multiplicity check is fulfilled.

In [215]:
Sum[MultdcbVertex[[u]], {u, 1, 16}]

48

# <font color=#71797E>Disconnected Diagrams</font>

The fully-contracted terms corresponding to disconnected diagrams with a one-body and a two-body interaction vertex at second order are $153$ in total. 

In [216]:
Adisc = Table[0, {i, 1, 250}, {j, 1, 5}, {k, 1, 2}];
l = 1;
For[i = 1, i <= 945, i++,
  DiscV1 = False;
  DiscV2 = False;
  DiscV12 = False;
  Link12 = False; 
  Conn7V1 = False;
  Conn7V2 = False;
  Conn8V1 = False;
  Conn8V2 = False;
  Conn9V1 = False;
  Conn9V2 = False;
  Conn10V1 = False;
  Conn10V2 = False;
  Bridge78 = False;
  Bridge79 = False;
  Bridge710 = False;
  Bridge89 = False;
  Bridge810 = False;
  Bridge910 = False;
  For[j = 1, j <= 5, j++,
   If[Acombsort[[i, j]] == {7, 8}, Bridge78 = True];
   If[Acombsort[[i, j]] == {7, 9}, Bridge79 = True];
   If[Acombsort[[i, j]] == {7, 10}, Bridge710 = True];
   If[Acombsort[[i, j]] == {8, 9}, Bridge89 = True];
   If[Acombsort[[i, j]] == {8, 10}, Bridge810 = True];
   If[Acombsort[[i, j]] == {9, 10}, Bridge910 = True];
   If[Acombsort[[i, j]] == {5, 7} || Acombsort[[i, j]] == {6, 7}, 
    Conn7V1 = True];
   If[Acombsort[[i, j]] == {5, 8} || Acombsort[[i, j]] == {6, 8}, 
    Conn8V1 = True];
   If[Acombsort[[i, j]] == {5, 9} || Acombsort[[i, j]] == {6, 9}, 
    Conn9V1 = True];
   If[Acombsort[[i, j]] == {5, 10} || Acombsort[[i, j]] == {6, 10}, 
    Conn10V1 = True];
   If[Acombsort[[i, j]] == {1, 7} || Acombsort[[i, j]] == {2, 7} || 
     Acombsort[[i, j]] == {3, 7} || Acombsort[[i, j]] == {4, 7} , 
    Conn7V2 = True];
   If[Acombsort[[i, j]] == {1, 8} || Acombsort[[i, j]] == {2, 8} || 
     Acombsort[[i, j]] == {3, 8} || Acombsort[[i, j]] == {4, 8} , 
    Conn8V2 = True];
   If[Acombsort[[i, j]] == {1, 9} || Acombsort[[i, j]] == {2, 9} || 
     Acombsort[[i, j]] == {3, 9} || Acombsort[[i, j]] == {4, 9} , 
    Conn9V2 = True];
   If[Acombsort[[i, j]] == {1, 10} || Acombsort[[i, j]] == {2, 10} || 
     Acombsort[[i, j]] == {3, 10} || Acombsort[[i, j]] == {4, 10} , 
    Conn10V2 = True];
   If[Acombsort[[i, j]] == {1, 5} || Acombsort[[i, j]] == {1, 6} || 
     Acombsort[[i, j]] == {2, 5} || Acombsort[[i, j]] == {2, 6} || 
     Acombsort[[i, j]] == {3, 5} || 
     Acombsort[[i, j]] == {3, 6} || Acombsort[[i, j]] == {4, 5} || 
     Acombsort[[i, j]] == {4, 6}, Link12 = True;];
   ];
  If[Link12 == False && Conn7V1 == False && Conn8V1 == False && 
    Conn9V1 == False && 
    Conn10V1 == 
     False && (Conn7V2 == True || Conn8V2 == True || Conn9V2 == True || 
      Conn10V2 == True), DiscV1 = True];
  If[Link12 == 
     False && (Conn7V1 == True || Conn8V1 == True || Conn9V1 == True || 
      Conn10V1 == True) && Conn7V2 == False && Conn8V2 == False && 
    Conn9V2 == False && Conn10V2 == False, DiscV2 = True];
  If[Link12 == True && Conn7V1 == False && Conn8V1 == False && 
    Conn9V1 == False && Conn10V1 == False && Conn7V2 == False && 
    Conn8V2 == False && Conn9V2 == False && Conn10V2 == False, 
   DiscV12 = True];
  If[Link12 == False && Conn7V1 == False && Conn8V1 == False && 
    Conn9V1 == False && Conn10V1 == False && Conn7V2 == False && 
    Conn8V2 == False && Conn9V2 == False && Conn10V2 == False, 
   DiscV12 = True];
  If[DiscV1 == True || DiscV2 == True || DiscV12 == True, 
   Adisc[[l]] = Acombsort[[i]]; l++];
  If[Mod[i, 100] == 0 || i == 945, 
   Print["Loop ", i, " completed and ", l - 1, 
    " disconnected fully-contracted terms found."] ];];

Loop 100 completed and 33 disconnected fully-contracted terms found.
Loop 200 completed and 66 disconnected fully-contracted terms found.
Loop 300 completed and 96 disconnected fully-contracted terms found.
Loop 400 completed and 108 disconnected fully-contracted terms found.
Loop 500 completed and 117 disconnected fully-contracted terms found.
Loop 600 completed and 126 disconnected fully-contracted terms found.
Loop 700 completed and 141 disconnected fully-contracted terms found.
Loop 800 completed and 156 disconnected fully-contracted terms found.
Loop 900 completed and 168 disconnected fully-contracted terms found.
Loop 945 completed and 177 disconnected fully-contracted terms found.


Disconnected diagrams are processed. Their initial number is $177$ in total.

In [219]:
For[u = 1, u <= 177, u++, Print[Adisc[[u]]]];

{{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}}
{{1, 2}, {3, 4}, {5, 6}, {7, 9}, {8, 10}}
{{1, 2}, {3, 4}, {5, 6}, {7, 10}, {8, 9}}
{{1, 2}, {3, 4}, {5, 7}, {6, 8}, {9, 10}}
{{1, 2}, {3, 4}, {5, 7}, {6, 9}, {8, 10}}
{{1, 2}, {3, 4}, {5, 7}, {6, 10}, {8, 9}}
{{1, 2}, {3, 4}, {5, 8}, {6, 7}, {9, 10}}
{{1, 2}, {3, 4}, {5, 8}, {7, 9}, {6, 10}}
{{1, 2}, {3, 4}, {5, 8}, {7, 10}, {6, 9}}
{{1, 2}, {3, 4}, {5, 9}, {7, 8}, {6, 10}}
{{1, 2}, {3, 4}, {5, 9}, {6, 7}, {8, 10}}
{{1, 2}, {3, 4}, {5, 9}, {7, 10}, {6, 8}}
{{1, 2}, {3, 4}, {5, 10}, {7, 8}, {6, 9}}
{{1, 2}, {3, 4}, {5, 10}, {7, 9}, {6, 8}}
{{1, 2}, {3, 4}, {5, 10}, {6, 7}, {8, 9}}
{{1, 2}, {3, 5}, {4, 6}, {7, 8}, {9, 10}}
{{1, 2}, {3, 5}, {4, 6}, {7, 9}, {8, 10}}
{{1, 2}, {3, 5}, {4, 6}, {7, 10}, {8, 9}}
{{1, 2}, {3, 6}, {4, 5}, {7, 8}, {9, 10}}
{{1, 2}, {3, 6}, {4, 5}, {7, 9}, {8, 10}}
{{1, 2}, {3, 6}, {4, 5}, {7, 10}, {8, 9}}
{{1, 2}, {3, 7}, {5, 6}, {4, 8}, {9, 10}}
{{1, 2}, {3, 7}, {5, 6}, {4, 9}, {8, 10}}
{{1, 2}, {3, 7}, {5, 6}, {4, 10}, 

### <font color=#E9967A>Filtration of the fully-contracted terms</font>

Filtration of the disconnected diagrams. At second order with a one-body interaction vertex plus a two-body one, transpositions between single-particle indices of different two-body vertices (external permutations) are not possible and the overall corresponding combinatorial factor is $1!$. On the other hand, transposition between single-particle index of the same two-body vertex are available. Fully-contracted terms which are mapped one another by the permutation $p \mapsto q$  and $r \mapsto s$  and $p \mapsto q \wedge r \mapsto s$ are identified and summed, eventually canceling out the $(2!)^2$ at the denominator, arising from the partial antisymmetry of the $\bar{V}_{pqrs}$ interaction vertex. The cancellation is only partial when one-body propagators linking a vertex to itself are present.

In [220]:
AdVertex = Table[0, {i, 1, 177}, {j, 1, 5}, {k, 1, 2}];
MultdVertex = Table[0, {i, 1, 177}];
Ifrepeat = False;
Temp = Table[0, {i, 1, 4}, {j, 1, 5}, {k, 1, 2}];
IfTemp = Table[0, {i, 1, 4}, {k, 1, 5}];

s = 1;
AdVertex[[1]] = Adisc[[1]];
MultdVertex[[1]] = 1;
For[u = 1, u <= 177, u++,
 For[i = 1, i <= 5, i++,
  For[j = 1, j <= 2, j++,
   If[ Adisc[[u, i, j]] == 1, Temp[[1, i, j]] = 2];
   If[ Adisc[[u, i, j]] == 2, Temp[[1, i, j]] = 1];
   If[ Adisc[[u, i, j]] >= 3, Temp[[1, i, j]] = Adisc[[u, i, j]]];
   If[ Adisc[[u, i, j]] == 1, Temp[[2, i, j]] = 2];
   If[ Adisc[[u, i, j]] == 2, Temp[[2, i, j]] = 1];
   If[ Adisc[[u, i, j]] == 3, Temp[[2, i, j]] = 4];
   If[ Adisc[[u, i, j]] == 4, Temp[[2, i, j]] = 3];
   If[ Adisc[[u, i, j]] >= 5, Temp[[2, i, j]] = Adisc[[u, i, j]]];
   If[ Adisc[[u, i, j]] == 3, Temp[[3, i, j]] = 4];
   If[ Adisc[[u, i, j]] == 4, Temp[[3, i, j]] = 3];
   If[ Adisc[[u, i, j]] >= 5 || Adisc[[u, i, j]] <=  2, 
    Temp[[3, i, j]] = Adisc[[u, i, j]]];
   Temp[[4, i, j]] = Adisc[[u, i, j]];
   ]];
 For[i = 1, i <= 4, i++,
  If[Temp[[i, 1, 1]] > Temp[[i, 1, 2]], t2 = Temp[[i, 1, 2]]; 
   t1 = Temp[[i, 1, 1]]; Temp[[i, 1, 1]] = t2; Temp[[i, 1, 2]] = t1];
  If[Temp[[i, 2, 1]] > Temp[[i, 2, 2]], t2 = Temp[[i, 2, 2]]; 
   t1 = Temp[[i, 2, 1]]; Temp[[i, 2, 1]] = t2; Temp[[i, 2, 2]] = t1];
  If[Temp[[i, 3, 1]] > Temp[[i, 3, 2]], t2 = Temp[[i, 3, 2]]; 
   t1 = Temp[[i, 3, 1]]; Temp[[i, 3, 1]] = t2; Temp[[i, 3, 2]] = t1];
  If[Temp[[i, 4, 1]] > Temp[[i, 4, 2]], t2 = Temp[[i, 4, 2]]; 
   t1 = Temp[[i, 4, 1]]; Temp[[i, 4, 1]] = t2; Temp[[i, 4, 2]] = t1];];
 Ifrepeat = False;
 If[u != 1,
  For[v = 1, v <= s, v++,
   Vrepeat = False;
   For[i = 1, i <= 4, i++,
    For[j = 1, j <= 5, j++,
     IfTemp[[i, j]] = 0;
     ]];
   For[i = 1, i <= 5, i++,
    For[j = 1, j <= 4, j++,
      For[k = 1, k <= 5, k++,
        If[AdVertex[[v, i]] == Temp[[j, k]], IfTemp[[j, k]] = 1;];
        ];];];
   If[IfTemp[[1, 1]] + IfTemp[[1, 2]] + IfTemp[[1, 3]] + 
      IfTemp[[1, 4]] + IfTemp[[1, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[2, 1]] + IfTemp[[2, 2]] + IfTemp[[2, 3]] + 
      IfTemp[[2, 4]] + IfTemp[[2, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[3, 1]] + IfTemp[[3, 2]] + IfTemp[[3, 3]] + 
      IfTemp[[3, 4]] + IfTemp[[3, 5]] == 5, Vrepeat = True;];
   If[IfTemp[[4, 1]] + IfTemp[[4, 2]] + IfTemp[[4, 3]] + 
      IfTemp[[4, 4]] + IfTemp[[4, 5]] == 5, Vrepeat = True;];
   If[Vrepeat == True, Ifrepeat = True; 
    MultdVertex[[v]] = MultdVertex[[v]] + 1;];
   ];
  If[Ifrepeat == False , s++; AdVertex[[s]] = Adisc[[u]]; 
   MultdVertex[[s]] = 1;];
  ];
 If[u == 177, 
  Print["Loop ", u, " completed and ", s, 
   " inequivalent disconnected contributions found."]];
 ]

Loop 177 completed and 72 inequivalent disconnected contributions found.


In [229]:
For[u = 1, u <= 72, u++, Print["CombDisc[[", u, "]]=", AdVertex[[u]]]];

CombDisc[[1]]={{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 10}}
CombDisc[[2]]={{1, 2}, {3, 4}, {5, 6}, {7, 9}, {8, 10}}
CombDisc[[3]]={{1, 2}, {3, 4}, {5, 6}, {7, 10}, {8, 9}}
CombDisc[[4]]={{1, 2}, {3, 4}, {5, 7}, {6, 8}, {9, 10}}
CombDisc[[5]]={{1, 2}, {3, 4}, {5, 7}, {6, 9}, {8, 10}}
CombDisc[[6]]={{1, 2}, {3, 4}, {5, 7}, {6, 10}, {8, 9}}
CombDisc[[7]]={{1, 2}, {3, 4}, {5, 8}, {6, 7}, {9, 10}}
CombDisc[[8]]={{1, 2}, {3, 4}, {5, 8}, {7, 9}, {6, 10}}
CombDisc[[9]]={{1, 2}, {3, 4}, {5, 8}, {7, 10}, {6, 9}}
CombDisc[[10]]={{1, 2}, {3, 4}, {5, 9}, {7, 8}, {6, 10}}
CombDisc[[11]]={{1, 2}, {3, 4}, {5, 9}, {6, 7}, {8, 10}}
CombDisc[[12]]={{1, 2}, {3, 4}, {5, 9}, {7, 10}, {6, 8}}
CombDisc[[13]]={{1, 2}, {3, 4}, {5, 10}, {7, 8}, {6, 9}}
CombDisc[[14]]={{1, 2}, {3, 4}, {5, 10}, {7, 9}, {6, 8}}
CombDisc[[15]]={{1, 2}, {3, 4}, {5, 10}, {6, 7}, {8, 9}}
CombDisc[[16]]={{1, 2}, {3, 5}, {4, 6}, {7, 8}, {9, 10}}
CombDisc[[17]]={{1, 2}, {3, 5}, {4, 6}, {7, 9}, {8, 10}}
CombDisc[[18]]={{1, 2}, {3, 5}, {4, 6}, 

In [230]:
For[u = 1, u <= 72, u++, Print["GGFMult[[", u, "]]=", MultdVertex[[u]]]];

GGFMult[[1]]=1
GGFMult[[2]]=1
GGFMult[[3]]=1
GGFMult[[4]]=1
GGFMult[[5]]=1
GGFMult[[6]]=1
GGFMult[[7]]=1
GGFMult[[8]]=1
GGFMult[[9]]=1
GGFMult[[10]]=1
GGFMult[[11]]=1
GGFMult[[12]]=1
GGFMult[[13]]=1
GGFMult[[14]]=1
GGFMult[[15]]=1
GGFMult[[16]]=2
GGFMult[[17]]=2
GGFMult[[18]]=2
GGFMult[[19]]=2
GGFMult[[20]]=2
GGFMult[[21]]=2
GGFMult[[22]]=2
GGFMult[[23]]=2
GGFMult[[24]]=2
GGFMult[[25]]=2
GGFMult[[26]]=2
GGFMult[[27]]=2
GGFMult[[28]]=2
GGFMult[[29]]=2
GGFMult[[30]]=2
GGFMult[[31]]=2
GGFMult[[32]]=2
GGFMult[[33]]=2
GGFMult[[34]]=2
GGFMult[[35]]=2
GGFMult[[36]]=2
GGFMult[[37]]=2
GGFMult[[38]]=2
GGFMult[[39]]=2
GGFMult[[40]]=4
GGFMult[[41]]=4
GGFMult[[42]]=4
GGFMult[[43]]=4
GGFMult[[44]]=4
GGFMult[[45]]=4
GGFMult[[46]]=4
GGFMult[[47]]=4
GGFMult[[48]]=4
GGFMult[[49]]=4
GGFMult[[50]]=4
GGFMult[[51]]=4
GGFMult[[52]]=4
GGFMult[[53]]=4
GGFMult[[54]]=4
GGFMult[[55]]=4
GGFMult[[56]]=4
GGFMult[[57]]=4
GGFMult[[58]]=2
GGFMult[[59]]=2
GGFMult[[60]]=2
GGFMult[[61]]=2
GGFMult[[62]]=2
GGFMult[[63]]=2
G

There are $72$ second-order disconnected diagrams with a one-body and a two-body vertex. The multiplicity check is fulfilled.

In [231]:
Sum[MultdVertex[[u]], {u, 1, 72}]

177